### ISSUE TITLE
Add support for Maps in Fabulous.MauiControls.Maps

### ISSUE THREAD

**Issue by edgarfgp** [fsprojects/Fabulous#1014]
Now that net7 rc1 is out we finally have maps 

- Should we add maps support ?
- Should this be a separate nuget ?

**Comment by TimLariviere** [comment]
@edgarfgp Yes, it would be a good idea to have maps support. We would be able to fully migrate FabulousContacts as well.

>Should this be a separate nuget ?

I would even have a separate nuget for it and host it in the fsharp-mobile org.

**Comment by edgarfgp** [comment]
@TimLariviere Could you create the repos so we can start start 😀

**Comment by TimLariviere** [comment]
Done. :)

Xamarin.Forms: https://github.com/fsharp-mobile/Fabulous.XamarinForms.Maps
Maui.Controls: https://github.com/fsharp-mobile/Fabulous.MauiControls.Maps

Bonus point: We can reuse those 2 repos as templates for other 3rd party extensions :)

Let's continue in those repos
