### ISSUE TITLE
Add Maui Controls ZIndex support

### ISSUE THREAD

**Issue by edgarfgp** [fsprojects/Fabulous#1024]
Now that NET7 has been released and the latest Maui bits are available we could wrap ZIndex + extension method 
See: https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.visualelement.zindex?view=net-maui-7.0

https://askxammy.com/organizing-elements-with-zindex-in-net-maui/

**Comment by TimLariviere** [comment]
Is there a changelog for MAUI net6.0 -> net7.0?
