### ISSUE TITLE
Xamarin Live Reload Support for half-elmish

### ISSUE THREAD

**Issue by slang25** [fsprojects/Fabulous#104]
For the "half elmish" approach of having static XAML files, but still using an elmish model, it would be very compelling to have [Xamarin Live Reload](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload) support.

At the moment if I add the live reload package to this project, the `ResolveAssembly` task in `Xamarin.Android.Common.targets` fails with:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1590,2): error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Xamarin.Live.Reload, Version=0.3.27.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Xamarin.Live.Reload.dll'
```

I think I can work around this, but then I spotted some targets in the live reload package that looks like it will only work in C# & VB projects, it tries to inject some attributes into the assembly, however I don't think F# uses the same targets (yet? see here: https://github.com/Microsoft/visualfsharp/issues/3113).

I might have a dabble with this later this week to see what I can get working.

**Comment by dsyme** [comment]
@slang25 If you can add docs for getting half-elmish to work with Live Reload that would be great

In the meantime we've added a preliminary LiveUpdate experience for Full Elmish, see https://fsprojects.github.io/Elmish.XamarinForms/tools.html

**Comment by cartermp** [comment]
Note that Live Reload has been deprecated: https://github.com/xamarin/Xamarin.Forms/issues/4155#issuecomment-431596130

**Comment by slang25** [comment]
I never got around to looking at this 😞 Given it's dead, I'm closing

**Comment by dsyme** [comment]
Note that the "Live Update" support in this repo is unrelated to "Live Reload" mentioned above :)

**Comment by slang25** [comment]
Yes :) now I dislike XAML even more!
