### ISSUE TITLE
Add Ooui based SPA project to template

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/Fabulous#112]
With ASP.NET Core hosting and PWA capability options

**Comment by dsyme** [comment]
Well this would be interesting.  FOr those lacking context see https://github.com/praeclarum/Ooui

**Comment by xperiandri** [comment]
@jsuarezruiz, you have made a great progress in Ooui templates for Visual Studio
Maybe you can add one for Elmish Ooui.Forms?

**Comment by xperiandri** [comment]
So, we've managed to launch template counter app via Ooui
[Msp.RoadShow.zip](https://github.com/fsprojects/Elmish.XamarinForms/files/2231652/Msp.RoadShow.zip)

Notice that Web does not reference SPA but must depend on it in SLN file.

Could someone add SPA and Web projects to the current dotnet new template?

**Comment by TimLariviere** [comment]
Closing due to a lack of activity on both this issue and the Ooui repository (no new version since April 2018)
If really needed, this issue can be reopened.
