### ISSUE TITLE
Consider not using FileSystemWatcher directly

### ISSUE THREAD

**Issue by nosami** [fsprojects/Fabulous#120]
FileSystemWatcher is known to be flaky on OSX, i.e. not triggering, triggering too many times, uses too many resources (can starve the system of file handles which in turn causes VSMac to stop saving files)

Consider something like [this](https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs) instead and dependencies - it's a wrapper around .Net Core FileSystemWatcher with some tweaks (as that too has issues)

**Comment by slang25** [comment]
I found it flaky on Windows as well, it worked when editing using VS Code, but if I made changes from Visual Studio they would not get detected.

**Comment by zakaluka** [comment]
Took an initial cut at this based on the referenced file.  Not sure if what I've done is enough (or even correct, for that matter) because Changed events were passed straight through even in the MonoDevelop code.

Code can be found in #127

**Comment by nosami** [comment]
@zakaluka: This looks wrong to me. The dependencies to the wrapper are [here](https://github.com/mono/monodevelop/tree/88f4e3116a35c28bbb0975475666549ed3b2d7b3/main/src/core/MonoDevelop.Core/MonoDevelop.FSW)

**Comment by TimLariviere** [comment]
.NET Core's FileSystemWatcher is now used with PR #247.
It works way better.
