### ISSUE TITLE
AllControls sample - Add consistent back button for all pages

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#137]
It would be great to have a consistent back button on all the pages of the AllControls sample, because currently it is quite painful to browse all the controls in the sample.
Most pages require to shutdown the app to go back to the RootPage.

Examples:
- `TabbedPage #1` has a back button hidden in the `Grid` tab
- `TabbedPage #3` has no back button at all

**Comment by dsyme** [comment]
Agreed

**Comment by SergejDK** [comment]
Is it enough to put a button "Mainpage" to each view? I mean it does not look great but works....

**Comment by TimLariviere** [comment]
I think it should be easier to use a NavigationPage instead. But I guess adding a back button to each view is enough.

AllControls is no longer a sample, it's more like a sandbox really.
