### ISSUE TITLE
Upgrade to XF 3.1

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#145]
I was going to add a missing property [ListView.SelectionMode](https://docs.microsoft.com/dotnet/api/xamarin.forms.listview.selectionmode), but found this was new in XF 3.1 ([link](https://github.com/xamarin/Xamarin.Forms/issues/1801)).

So my question is:
Can we update EXF to use the latest version of XF (templates and all), or is it tied to XF 3.0 for a reason?

**Comment by dsyme** [comment]
I think it's OK to upgrade (though maybe we aim to stay about 2 months behind the curve?)

**Comment by TimLariviere** [comment]
Alright, I agree that we should wait a little for things to settle down. XF 3.1 is only 1 month old for now.
In the meantime, I'll try to find an easy way to extend existing controls without updating EXF (saw some examples in AllControls)
