### ISSUE TITLE
Performance - How to handle StreamImageSource?

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#151]
I'm currently playing with the Image control and displaying in-memory images thanks to `ImageSource.FromStream` (#131)

This leads to some problems.
When using `ImageSource.FromStream(() => stream)`, you don't manage the stream anymore (can't use `use` keyword or call `.Dispose()`)
ImageSource will automatically close the stream when disposed.

But since `ImageSource` is not great having in your Model, you have to create a new one every time the `view` function is called.
It's an object so EXF will compare the references, resulting in reloading the image every time. Disposing the previous ImageSource, disposing the stream.
So we can't reuse the stream.

This is especially bad on Android (blinking image at every keystroke), somehow iOS handles it fine.

The way I managed to mitigate the problem is by having a mutable field that store the ImageSource, replacing it only when the image needs to be changed.

So I was wondering, is there a better way to do that?
Maybe it would be better to directly give EXF the byte array (Structural Equality -> Recycling) and letting it create its own ImageSource?

**Comment by dsyme** [comment]
It's a good question :) 

> But since ImageSource is not great having in your Model, you have to create a new one every time the view function is called.

I suppose an approach like "dependsOn" could work - use a global lookaside table and a key.  See also [`fix`](https://github.com/fsprojects/Elmish.XamarinForms/blob/master/Elmish.XamarinForms/ViewHelpers.fs#L47).  These are "hacks" that use the closure type identity as part of the key.

> The way I managed to mitigate the problem is by having a mutable field that store the ImageSource, replacing it only when the image needs to be changed.

Yes, this makes sense, though I can see it's annoying to have to program that directly.

**Comment by TimLariviere** [comment]
I will take a closer look to `dependsOn` and `fix`, and see if I can do something like that for images.
Tried to use `dependsOn` directly but was getting a disposed ImageSource... :)

**Comment by dsyme** [comment]
> I will take a closer look to dependsOn and fix, and see if I can do something like that for images.
Tried to use dependsOn directly but was getting a disposed ImageSource... :)

Interesting. This is relevant, from https://forums.xamarin.com/discussion/22160/imagesource-fromstream-with-caching

> Xamarin will dispose all streams associated with the current page when you navigate to another page (i.e. PushPageAsync) which is correct to save memory. 

If so that makes things kind of tricky. There's also a discussion there about just using bytes.
