### ISSUE TITLE
Excellent tooling support

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/Fabulous#154]
Yesterday I saw [this episode about Prism](https://channel9.msdn.com/Shows/XamarinShow/Prism-Template-Studio--Developer-Toolkit-for-Visual-Studio-for-Mac-with-Dan-Siegel) and it looks amazing for me in terms of tooling support.
It would be nice for have XF Elmish tools work a similar way.

**Comment by nosami** [comment]
Which tooling? I skimmed through the video quickly. You just mean templates in the IDE?

**Comment by TimLariviere** [comment]
Closing as there is no real request or issue, and it's been dead for almost a year.
