### ISSUE TITLE
NavigationPopped called twice if more than 2 pages deep

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#155]
**Applies to:** iOS (device and simulator)

**Description:**
I'm using a NavigationPage with more than 2 pages in the stack.
As I want to update my model when the user navigates back (back button), I subscribed to the `popped` handler. This works perfectly.

When doing a programmatic back navigation (when clicking a button), I manually remove the page from the model and set a flag to prevent `popped` to navigate back further (otherwise it would loop until no page is left).

But in this particular case, on iOS only, `popped` is called 2 times even though logs say no 2nd PopAsync was done.
The first time it stumbles on my flag and reset it but do nothing to the page stack.
The second time, no more flag, so it removes the current page from the stack, triggering another round of NavigationPopped events. (until no page left)

Curiously this does not affect Android.
Maybe a Xamarin.Forms.iOS bug?

**Logs:**

> **Message: NavigateToChildPage**
> Updated model: {Depth = 1; ManualPop = true;}
> View, model = {Depth = 1; ManualPop = true;}
> View result: NavigationPage(...)@-6348843
> Updating NavigationPage, prevCount = 1, newCount = 2
> Adjust page number 0
> PushAsync, page number 1
> **Message: NavigateToChildPage**
> Updated model: {Depth = 2; ManualPop = true;}
> View, model = {Depth = 2; ManualPop = true;}
> View result: NavigationPage(...)@-465422631
> Updating NavigationPage, prevCount = 2, newCount = 3
> Adjust page number 0
> Adjust page number 1
> PushAsync, page number 2
> **Message: NavigateBack**
> Updated model: {Depth = 1; ManualPop = true;}
> View, model = {Depth = 1; ManualPop = true;}
> View result: NavigationPage(...)@1855095253
> Updating NavigationPage, prevCount = 3, newCount = 2
> **_PopAsync, page number 2_**
> Adjust page number 0
> Adjust page number 1
> **Message: NavigationPopped**
> Updated model: {Depth = 1; ManualPop = false;}
> View, model = {Depth = 1; ManualPop = false;}
> View result: NavigationPage(...)@-1463102424
> Updating NavigationPage, prevCount = 2, newCount = 2
> Adjust page number 0
> Adjust page number 1
> **Message: NavigationPopped <---------------------------------- Here**
> Updated model: {Depth = 0; ManualPop = false;}
> View, model = {Depth = 0; ManualPop = false;}
> View result: NavigationPage(...)@-1654874669
> Updating NavigationPage, prevCount = 2, newCount = 1
> Updating NavigationPage --> PopToRootAsync
> Adjust page number 0

**Repro:**
I made a small sample with a repro: https://github.com/TimLariviere/EXF_ReproNavPagePoppedBug

1. Start the repro app
2. Click "Next page"
3. Click "Next page"
4. Click "< Depth 1"
5. Working! Click "Next page"
6. Click "Previous page"
7. Not working...

**Comment by TimLariviere** [comment]
After investigating the problem, this is definitely a Xamarin.Forms iOS bug.

XF NavigationPage on iOS always triggers 2 Popped events when we call PopAsync(),.

The first event comes from the Pop action, which is what is expected.
The second one is triggered by `DidMoveToParentViewController`, I don't know why this is needed but I think this is the culprit.

https://github.com/xamarin/Xamarin.Forms/blob/e3b6e4755eda0e7611694929d6b0529ee2c40d4b/Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs#L1240-L1245

I think the Xamarin team also had this problem but decided to work around it directly in the renderer, leaving the NavigationPage affected.

https://github.com/xamarin/Xamarin.Forms/blob/e3b6e4755eda0e7611694929d6b0529ee2c40d4b/Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs#L842-L851

So I tried to work around it in Elmish, but every attempts failed.
There's no way I could thought of to keep the model in sync with page stack.

Either I'm not listening to the Popped event and I go out of sync when the user hits the iOS Back Button, or I listen to it but got it by multiple Popped events.

Even increasing the number of times I don't want to react to Popped event, somehow Xamarin.Forms keeps send it.

I reproduced the problem in a C# Xamarin.Forms app, so I will open an issue on the XF repo.

In the meantime, if you have any idea of how we could mitigate the problem in EXF...

**Comment by TimLariviere** [comment]
Looks like someone else noticed the problem.
https://github.com/xamarin/Xamarin.Forms/issues/3509

**Comment by TimLariviere** [comment]
Maybe I can work around it by storing the last popped page identifier and whenever `Popped` is called check if the id is the same ?

If true, do nothing.
If false, dispatch an Elmish message.

**Comment by TimLariviere** [comment]
This has just been fixed in the Xamarin.Forms repo.
It should be available in XF 3.5.0 from what I understand.
https://github.com/xamarin/Xamarin.Forms/pull/3851

**Comment by dsyme** [comment]
That's great!

**Comment by SergejDK** [comment]
@TimLariviere 
did you made a workaround here? With the upgrade it should be fixed, so if you changed something we have to change it back and test if it is working correct now?

**Comment by TimLariviere** [comment]
@SergejDK Not in Fabulous. I did it in ElmishContacts. So we're good to go and close this issue if it's solved.
Will try it with ElmishContacts once v0.34.0 is released

**Comment by TimLariviere** [comment]
Can confirm this is fixed in Fabulous 0.34
