### ISSUE TITLE
How stable is the View API? 

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fsprojects/Fabulous#173]
Hello there! 
I am building a library on top of the `View` API that unifies optional properties and fluent mehtods into lists of attributes, (IMO they are easier to work with and are very readable) the same way with the Elmish on the web but it might take quite the effort. So before I dive deep into this I wanted to ask about how stable the View api is, the potential changes that can be applied to it and whether you are thinking of a rewrite.

**Comment by dsyme** [comment]
@Zaid-Ajaj I think it's pretty much stable, but we don't expect binary compatibilty

I liked your DSL and can see some people would want it as an alternative.

Once you've finished your prototype I'd recommend integrating it into this repo under "extensions", e.g. "Fabulous.DynamicViews.Alternative" or something better named.  Then it can be a regular part of the toolkit

One problem is that you end up wrapping-the-wrappers (Maps, SkiaSharp etc.).  Not sure what to do about those cases though those are really tiny APIs do far.

**Comment by Zaid-Ajaj** [comment]
> I think it's pretty much stable, but we don't expect binary compatibilty

Thanks for the quick answer, I am glad to hear this! 

I will see if I can move the prototype here, last time I cloned the repo I couldn't run any sample but that was a while ago, so I will try again. 

> One problem is that you end up wrapping-the-wrappers (Maps, SkiaSharp etc.). Not sure what to do about those cases though those are really tiny APIs do far.

I don't think that is a problem since the API has a small surface and the overhead of the wrapping is negligible
