### ISSUE TITLE
TimePicker does not have argument to set the event handler for when a time gets selected

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fsprojects/Fabulous#179]
There is no `onTimeChanged` or similar for `View.TimePicker`

Any idea's on where I should look if I wanted to fix this issue?

**Comment by TimLariviere** [comment]
Hmm. Seems like a missing feature in Xamarin.Forms.
I think you're best bet would be to subclass `TimePicker`, add a `OnTimeChanged` event, and in your renderers listen to PropertyChanged and check that the property being changed is `Time` and then trigger your event.

You can also make a PR into [xamarin/Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms) but it will take longer. :)

Found a thread on that dating back from 2014.
https://forums.xamarin.com/discussion/19221/which-event-will-be-raised-after-selecting-time-in-timepicker

**Comment by Zaid-Ajaj** [comment]
@TimLariviere Thanks for the quick response! I will try to workaround it, I will keep this issue open until I come up with something :smile:

**Comment by TimLariviere** [comment]
Closing the issue, as this is more a Xamarin.Forms issue than Fabulous.
@Zaid-Ajaj You can reopen it if needed.
