### ISSUE TITLE
Add RestoreProjectStyle --> PackageReference to Android and iOS projects?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#181]
I've noticed occasions where dependencies added or updated in the core F# project (SDK-style) don't seem to be copied correctly to the Android and iOS apps (old-style)

I'm not 100% sure why but it looks related to this issue: https://github.com/dotnet/standard/issues/481

The recomendation there is to add 

    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>

I'm not 100% sure but we should probably add this to our Android/iOS app projects

**Comment by TimLariviere** [comment]
`packages.config` is quite annoying when it comes to indirect references.

Switching to hybrid mode is a good idea. (PackageReference in classic project)

Also I'm currently playing with [`MSBuild.Sdk.Extras`](https://github.com/onovotny/MSBuildSdkExtras) which allows to SDK-Style pretty much any framework.
Might be a good solution too.

For example: (removed `Configuration|Platform` specific attributes to make it easier to read)
```xml
<Project Sdk="MSBuild.Sdk.Extras/1.6.55">
  <PropertyGroup>
    <TargetFramework>Xamarin.iOS10</TargetFramework>
  </PropertyGroup>
    
  <Import Project="$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.iOS.FSharp.targets" Condition="Exists('$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.iOS.FSharp.targets')" />

  <ItemGroup>
    <Reference Include="System.Numerics" />
    <Reference Include="Xamarin.iOS" />
    <Reference Include="System" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Core" />
    <Reference Include="mscorlib" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fabulous.Core" Version="0.20.0" />
  </ItemGroup>

  <ItemGroup>
    <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Contents.json" />
    <ImageAsset Include="Assets.xcassets\Contents.json" />
    <InterfaceDefinition Include="LaunchScreen.storyboard" />
    <None Include="Info.plist" />
    <None Include="Entitlements.plist" />
    <InterfaceDefinition Include="Main.storyboard" />
    <Compile Include="ViewController.fs" />
    <Compile Include="AppDelegate.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>
</Project>
```

**Comment by TimLariviere** [comment]
Migrating to PackageReference would also allow to remove the .nuget folder from the template.
This is only required by msbuild when testing (unnecessary for Visual Studio).

It happens to me several times to have a build failed because I moved files around and forgot to copy the hidden .nuget folder... (explicitly referenced in fsproj)

**Comment by dsyme** [comment]
> Migrating to PackageReference would also allow to remove the .nuget folder from the template.

That would be great

**Comment by TimLariviere** [comment]
`RestoreProjectStyle` is not supported by `fsproj` old format. (despite working in csproj)
VS continues to use the `packages.config` file.

**Comment by TimLariviere** [comment]
Based on my discussion with @nosami on Gitter, this limitation seems to apply to VS tooling only.
RestoreProjectStyle should be taken into account by MSBuild.
Will try to migrate the projects.

But if it works, should we also migrate the templates?
Is having better dependency transitivity worth losing the ability to manage the packages through Visual Studio? (for Android/iOS only)

**Comment by TimLariviere** [comment]
Closing the issue for now.
Will migrate to SDK-Style projects when Xamarin.Android and Xamarin.iOS will support it.
