### ISSUE TITLE
GettingStarted almost awesome, and example links broken

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [fsprojects/Fabulous#207]
Your simple here's a full app sample is so much closer to perfect than any other I've seen. so short and sweet to the point.

However, without proper `open` clauses it still won't run after adding `Fabulous.Core` via NuGet.
As far as I know intellisense in F# is incredibly unreliable for figuring out where `View` or `Application` lives.

Then the first 3 sample links are broken
https://github.com/fsprojects/Fabulous/blob/master/Samples/CounterApp/CounterApp/CounterApp.fs
https://github.com/fsprojects/Fabulous/blob/master/Samples/TicTacToe/TicTacToe/TicTacToe.fs
https://github.com/fsprojects/Fabulous/blob/master/Samples/AllControls/AllControls/AllControls.fs

**Comment by TimLariviere** [comment]
Thanks!
I've fixed the links (Github is case sensitive apparently) and updated the sample (added open clauses and fixed a missing parameter).
