### ISSUE TITLE
EntryCell has no TextChanged Event

### ISSUE THREAD

**Issue by garethhubball** [fsprojects/Fabulous#225]
I'm trying to use an EntryCell in my application and the `completed` event only fires when the done button is pressed on the keyboard. This is Xamarin.Forms intended behaviour.

There is, however, no simple way that I can find of getting an event to fire when the focus is lost or when the text has changed. This makes the EntryCell far less useful in my opinion. Could we add an event to it somehow in Fabulous or find some other way of getting the text from said EntryCell without resorting to methods that make the architecture impure?

**Comment by garethhubball** [comment]
Would anyone mind if I had a go at implementing this? I don't know the source well so it might be a big ask for the support but I think it might be nice to contribute to the project. I'll also add a request to the Xamarin.Forms repo and have a crack at implementing it there too.

**Comment by TimLariviere** [comment]
You're welcome to implement it. :)
Don't hesitate to ask if you need help.

As a starting point, you can take a look at ListView and its custom control.
The idea is to create a custom control that will support `TextChanged`
https://github.com/fsprojects/Fabulous/blob/e6407ce0058152f123d9faba1f559906b9af7d95/src/Fabulous.Core/ViewConverters.fs#L109-L110

Then you can use your control in the bindings file and add your event.
https://github.com/fsprojects/Fabulous/blob/e6407ce0058152f123d9faba1f559906b9af7d95/tools/Generator/Xamarin.Forms.Core.json#L1592-L1593

**Comment by TimLariviere** [comment]
Yes, the Generator tries to infer some infos like the type of the property/event by doing reflection.
But it uses the field "Name" (currently set to `Xamarin.Forms.Entry`) to find the control, so it won't find your new event, thus the error.

So to do that, you'll need to do it a bit differently than the CustomListView.

First you'll need to load `Fabulous.Core.dll` at the start of the json file
```json
"assemblies": [
    "packages/neutral/Xamarin.Forms/lib/netstandard1.0/Xamarin.Forms.Core.dll",
    "src/Fabulous.Core/bin/Release/netstandard2.0/Fabulous.Core.dll",
],
```
Then you'll need to set your new control in the `Name` field.
But we still want the Generator to use the name "EntryCell". You can force it by setting the `ModelName` field
And now you can add your new property:
```json
    {
      // Extends Xamarin.Forms.EntryCell
      "name": "Fabulous.DynamicViews.CustomEntryCell",
      "modelName": "EntryCell",
      "members": [
        {
          "name": "TextChanged",
          "defaultValue": "null",
          "inputType": "Xamarin.Forms.TextChangedEventArgs -> unit",
          "convToModel": "(fun f -> System.EventHandler<Xamarin.Forms.TextChangedEventArgs>(fun _sender args -> f args))"
        },
```

Currently there's a limitation in the Generator. It will crash if you load another assembly.
A pull request has been made to fix this.

**Comment by TimLariviere** [comment]
I'm just realizing that while the fix should be good, using `Fabulous.Core.dll` in the binding file could cause problems.
This will create a conflict in the dependency chain when building (FAKE run the Generator before compiling Fabulous.Core, but the Generator will depend on Fabulous.Core for reflection).

So maybe we need to create a new project where we store all our custom Xamarin.Forms controls?
`CustomListView` and such only work because the Generator treats them as simple strings and doesn't do any reflection on it.

@garethhubball @dsyme What do you think?

**Comment by garethhubball** [comment]
I'm on stream now, thank you for this update - I'll have a go with the new project idea now.

**Comment by TimLariviere** [comment]
Fixed by #227.

v0.27.0 has been released. NuGet is currently indexing the packages.
Should be available in 15 minutes

**Comment by dsyme** [comment]
@TimLariviere Fantastic work!  Great to see another release :) 

I wonder if we should call it all version 1.0.0 now :)

**Comment by TimLariviere** [comment]
@dsyme Thanks. We're getting closer to 1.0.0 :)
But I think we need to fix 2 bugs before releasing a stable version. (the infinite loop and the Cmd+Navigation ones)
I think I have a good solution for the former, so I'll do a PR to add a debounce (both standalone and `textChangedDebounced`)
The latter will prove more complex.

Also I will take a look at performance on Android. Even in release, I can still feel it's a bit slow.

**Comment by dsyme** [comment]
👍 👍 👍

**Comment by dsyme** [comment]
I'm just catching up on some Fabulous things. Question about this: should we move all the other control extensions like `ViewElementCell` into Fabulous.CustomControls.dll?

**Comment by TimLariviere** [comment]
@dsyme Yes, I think it will be better.
We created CustomControls because we wanted the Generator to do reflection on CustomEntry.
The other controls don't need that (they're treated just like strings by the Generator), so we haven't moved them.

But this will be better for maintainability/extensibility to have only one place for those controls.
