### ISSUE TITLE
Update to Xamarin.Forms 3.4

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#243]
We're currently using Xamarin.Forms 3.1.
XF 3.3 will be 2 months old in a few days, so it might be good to update and provide wrappers for the new controls.

**Comment by rbrogan-git** [comment]
Any reason not to go to XF 3.4?

**Comment by TimLariviere** [comment]
We're waiting 2 months after a release before moving to it as a general rule, to wait for the first few bug fixes.
But I think we can safely go to XF 3.4 now.

**Comment by rbrogan-git** [comment]
@TimLariviere I submitted a pull request for this one.

**Comment by TimLariviere** [comment]
Closed by #257
