### ISSUE TITLE
Program --> AppLogic?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#248]
The Elmish term `Program` feels a little awkward in the Xamarin programming model, which already has `Application` and often `App`.

I wonder if a better word in this context would be `AppLogic`, since that's really what it is.  `Program` has the usual advantages of being clear to people who already know Elmish, but I'm sure people who don't get confused by things like `app.Program.Dispatch` whereas `app.AppLogic.Dispatch` seems simpler somehow.

Maybe it's ok though, close if you like

**Comment by dsyme** [comment]
I'll close this, it's just a late night thought, reopen if you consider important

**Comment by TimLariviere** [comment]
I agree that there's a general naming conflict between the Xamarin programming model and Elmish. (#170)
But I believe that the advantage of keeping the Elmish naming convention outweighs this problem.

This might set a higher entry barrier, especially for those coming from Xamarin.
But in my opinion, using Fabulous is more about the Elmish programming model than Xamarin's .
So it makes sense to use the same naming convention, even if it conflicts with Xamarin.

I guess this boils down to one question: Who should we be closest to? Xamarin or Elmish? :)

For your particular example, the property name `Program` is up to the user.
We can change it to `Runner` in the docs if you prefer. :)
`app.Runner.Dispatch`

**Comment by jwosty** [comment]
Just my two cents: I don't come from an Elmish background, and I found it useful to be able to search these terms in the Elmish and Elm documentation and get relevant information. If the names were to change to be more Xamarin-friendly, there'd have to be a lot more documentation and samples.
