### ISSUE TITLE
Image disappear on Live Update

### ISSUE THREAD

**Issue by magnushammar** [fsprojects/Fabulous#250]
I just started to look at Fabulous and tested Live Update with Android and its awesome, but I discovered a problem with Images.  The following image from an embedded resource will disappear on reload.

```fsharp
  View.Image(source=ImageSource.FromResource("SqueakyLiveImageProblem.iamatest.jpg"))
```

I recreated it in the Squeaky template app. Diff here -> [magnushammar/SqueakyLiveImageProblem](https://github.com/magnushammar/SqueakyLiveImageProblem/commit/1f4425d0d64678bf2003f55947600f7ecbf1e2ea#diff-865ce1c50a79ceec2975cdcf469a7c41)

**Comment by TimLariviere** [comment]
Thanks for the report. We'll take a look.
But this wouldn't surprise me it's a limitation of Live Update.
The interpreter recompiles on the fly the source code, not the whole project so the image might be ignored in the process.

**Comment by magnushammar** [comment]
Without knowing the bigger picture, I see this more like a feature request than a bug. It would be great to get the Live Debugger to work with embedded resources but...

- The Library works just fine.
- FromUrl works in the debugger
- FromFile works in the debugger

**Comment by TimLariviere** [comment]
LiveUpdate has been abandoned in v2. Might come back in the future
