### ISSUE TITLE
Add Accelerator property to MenuItem

### ISSUE THREAD

**Issue by jwosty** [fsprojects/Fabulous#251]
MenuItem is missing ``Accelerator`` (which define keyboard shortcuts). It's apparently defined in [Xamarin.Forms.Core.json#L1513](https://github.com/fsprojects/Fabulous/blob/60d2bf7875830b49e52e6d1abe505a9b2a139fe0/tools/Generator/Xamarin.Forms.Core.json#L1513), but it doesn't seem to be correct; there's no "Accelerator" anywhere to be found in any types. I assume it is a simple correction.

**Comment by zakaluka** [comment]
Isn't `Accelerator` pointing to `MenuItem.AcceleratorProperty` https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.menuitem.acceleratorproperty?view=xamarin-forms ?
