### ISSUE TITLE
Add Xamarin.Forms.Menu support

### ISSUE THREAD

**Issue by jwosty** [fsprojects/Fabulous#252]
``MenuItem`` is already supported, but it would be nice if we could also build ``Menu``s using the View module.

**Comment by SergejDK** [comment]
@TimLariviere is it right that we need only `Text` and `Items` property here? Or do I miss something else?

**Comment by TimLariviere** [comment]
@SergejDK Yes, after reading the MSDN doc, only Text and Items stand out. The others are read-only, so they don't interest us for ViewElement.

Regarding the update function, I'm not sure it's necessary.
StackLayout manages fine without it.
https://github.com/fsprojects/Fabulous/blob/0e43355c5b3ba24c7ad6e61c65711bf767873a33/tools/Generator/Xamarin.Forms.Core.json#L1275-L1283

**Comment by SergejDK** [comment]
Thank you that you took a look !

Will try to make it work today or tommorw!

**Comment by TimLariviere** [comment]
I added `Menu` in #530 , but even after trying to replicate https://github.com/xamarin/Xamarin.Forms/blob/723f2de43980bf66989f4e7d40d12ad00b63d06a/Xamarin.Forms.ControlGallery.MacOS/AppDelegate.cs#L59

It just won't work on MacOS

**Comment by TimLariviere** [comment]
Closing this one since we added support for `Menu`, even though we couldn't find a proper way to use it (no docs on the XF side...)

Will be available in v0.50
