### ISSUE TITLE
Creating new project using Visual Studio For Mac, Adding Fabulous, Wrong Version of FSharp.Core

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/Fabulous#253]
I have a Blank Forms App for F# where I added Fabulous via Nuget.  When I try and add the sample code, it fails with the error:

FSC : error FS0193: The module/namespace 'Xamarin.Forms' from compilation unit 'Xamarin.Forms.Core' did not contain the namespace, module or type 'ScrollBarVisibility'

Is this related to this bug?  https://github.com/fsprojects/Fabulous/issues/116

**Comment by dsyme** [comment]
> I have a Blank Forms App for F# where I added Fabulous via Nuget. When I try and add the sample code, it fails with the error:

This won't work.  You should create the app via the Fabulous template https://fsprojects.github.io/Fabulous/index.html#getting-started

**Comment by jamessdixon** [comment]
Ugh!!!

**Comment by TimLariviere** [comment]
@jamessdixon Do you still have the issue?

**Comment by jamessdixon** [comment]
Same issue.  I am dreading porting all of my code from the existing app to the new solution using the fabulous template

**Comment by jamessdixon** [comment]
I was still getting this error after follow those steps:
“Missing reference to Fabulous.Core”
So I added that nugget reference to all three projects and it compiled

Thanks for the help - you can close the issue
