### ISSUE TITLE
What is  Program.mkSimple ?

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/Fabulous#254]
The sample code uses this line of code:

`let runner = Program.mkSimple init update view`

what is mkSimple?  Is it makeSimple?  If so, can it be renamed to something more intuitive?

**Comment by jamessdixon** [comment]
and while we are at it, what is "dispatch" in the sample ?

`let view (model: Model) dispatch = `

It is of type 'a from the same namespace of my project

and it is used here

`command=(fun () -> dispatch Pressed)`

I assumed it was a function signature but not really?

**Comment by Nhowka** [comment]
Those came from Elmish. You can find the documentation [here](https://elmish.github.io/elmish/program.html).

**Comment by jamessdixon** [comment]
Is that an idiom that can't be replaced then?  It doesn't follow any F# or general functional naming conventions AFAIK

**Comment by TimLariviere** [comment]
Closing the issue.
Currently we will stick to the Elmish convention.

If you want to make a suggestion to replace those conventions, please open a new issue.
