### ISSUE TITLE
Can't build test suite (MacOS)

### ISSUE THREAD

**Issue by jwosty** [fsprojects/Fabulous#255]
I was trying to build the test suite so I could potentially make a contribution or two, but it's not working for me. I cloned, ran ``dotnet tool install fake-cli -g``, then ``./build.sh``, as per the instructions. Then when I ran ``./build.sh Test``, it chewed through for a while but finally failed with this:

```
Build FAILED.

"/Users/jwostenberg/Code/FSharp/Fabulous/testapp269/testapp269.sln" (default target) (1) ->
"/Users/jwostenberg/Code/FSharp/Fabulous/testapp269/testapp269.Android/testapp269.Android.fsproj" (default target) (3) ->
(_SetLatestTargetFrameworkVersion target) -> 
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(703,2): error XA5300: The Android SDK Directory could not be found. Please set via /p:AndroidSdkDirectory. [/Users/jwostenberg/Code/FSharp/Fabulous/testapp269/testapp269.Android/testapp269.Android.fsproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:13.41
Finished (Failed) 'TestTemplatesNuGet' in 00:00:21.1238510

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target               Duration
------               --------
Clean                00:00:00.0138390
Restore              00:00:12.3326550
UpdateVersion        00:00:00.2859880
BuildTools           00:00:13.7118690
BuildControls        00:00:11.4435060
RunGenerator         00:00:00.9983180
Build                00:02:39.5993640
RunTests             00:01:15.5881380
TestTemplatesNuGet   00:00:21.1234890   (msbuild testapp269/testapp269.sln /p:Platform="Any CPU" /p:Configuration=Debug /p:PackageSources=\"https://api.nuget.org/v3/index.json;/Users/jwostenberg/Code/FSharp/Fabulous/build_output\" failed, error code 1)
BuildSamples         00:00:00           (skipped)
Test                 00:00:00           (skipped)
Total:               00:04:55.4026270
Status:              Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'TestTemplatesNuGet' failed.
-> One or more errors occurred. (msbuild testapp269/testapp269.sln /p:Platform="Any CPU" /p:Configuration=Debug /p:PackageSources=\"https://api.nuget.org/v3/index.json;/Users/jwostenberg/Code/FSharp/Fabulous/build_output\" failed, error code 1)
-> msbuild testapp269/testapp269.sln /p:Platform="Any CPU" /p:Configuration=Debug /p:PackageSources=\"https://api.nuget.org/v3/index.json;/Users/jwostenberg/Code/FSharp/Fabulous/build_output\" failed, error code 1
Hint: To further diagnose the problem you can run fake in verbose mode `fake -v run ...` or set the 'FAKE_DETAILED_ERRORS' environment variable to 'true'
Performance:
 - Cli parsing: 501 milliseconds
 - Packages: 33 milliseconds
 - Script analyzing: 54 milliseconds
 - Script running: 4 minutes, 55 seconds
 - Script cleanup: 25 milliseconds
 - Runtime: 4 minutes, 56 seconds
```

I don't know how this project is supposed to work, so I'm kind of at a loss.

**Comment by jwosty** [comment]
Wait, hold on. I just noticed that further up in the log it can't find the android test suite... Duh.

**Comment by TimLariviere** [comment]
I would be interested if you find what caused the issue.
I've seen it randomly pops up on my machine and the CI build.
Usually re-running the build made the error go away...

**Comment by jwosty** [comment]
Well, I can say that even though I know I've let VSfM install the Android SDK before, it's not showing up in ``Preferences>Projects>SDK Locations``. (Suffice to say, retrying the build didn't work)

**Comment by TimLariviere** [comment]
What's strange about it is that the samples have been built successfully (Android included)
It only fails at the last build step where FAKE try building a test project created from the template (`dotnet new fabulous-app -n testappXXX`)

**Comment by jwosty** [comment]
Oh, that's strange. I don't know what to make of that.

I just got VSfM to find the Android SDK, but it still doesn't know where the JDK is, even though I just reinstalled it. Worth giving another recompile a shot.

**Comment by TimLariviere** [comment]
You can execute `.\build.sh BuildSamples`
This will run everything except TestTemplatesNuGet, which is the step that fails.

**Comment by TimLariviere** [comment]
@rbrogan-git Great!
21 minutes is not a bad build time actually, building the samples and testing the template do take a lot of time. Everything is built in Release mode so building/linking is slow.

**Comment by SergejDK** [comment]
I was trying to run `.\build Test` but I get the following Error:

` Expected string length 374 but was 378. Strings differ at index 95.
  Expected: "....EditorBrowsableState.Never)>]\n    static member val _Prop..."
  But was:  "....EditorBrowsableState.Never)>]\r\n    static member val _Pro..."
  ---------------------------------------------^`

I already tried the suggested solution above but did not help me.

**Comment by TimLariviere** [comment]
@SergejDK This error is from the new unit tests on the Generator.
Seems like `printfn` appends different characters depending on the environment (I mostly tested it on MacOS)

Could you try to change 
https://github.com/fsprojects/Fabulous/blob/5150a8f3a4d6c0d43247a15628cd3501e90ad7e4/tests/Generator.Tests/CodeGeneratorTests.fs#L14
to
```fsharp
let actual = w.ToString().Replace("\r\n", "\n")
```
before re-running `.\build.sh Test`?

**Comment by SergejDK** [comment]
@TimLariviere  this worked! 
Should I include this into the pr ?

**Comment by TimLariviere** [comment]
@SergejDK Yes, please.

**Comment by SergejDK** [comment]
@TimLariviere the pr is: #274 where i added the mainpagebutton

**Comment by TimLariviere** [comment]
I'm closing this PR.
@jwosty Feel free to reopen if you still have the issue.
