### ISSUE TITLE
GTK Template

### ISSUE THREAD

**Issue by NatElkins** [fsprojects/Fabulous#259]
GTK is a supported platform for Xamarin Forms: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/gtk?tabs=macos

What would it take to add a GTK template?

**Comment by TimLariviere** [comment]
We would need to add a GTK project in this folder https://github.com/fsprojects/Fabulous/tree/master/templates/content/blank
And apply some modifications to it to make it template-compatible

- Replace package versions by their corresponding tokens ([packages.config](https://github.com/fsprojects/Fabulous/blob/master/templates/content/blank/NewApp.macOS/packages.config) and [NewApp.macOS.fsproj](https://github.com/fsprojects/Fabulous/blob/master/templates/content/blank/NewApp.macOS/NewApp.macOS.fsproj))
- Use the namespace `NewApp` (will be replaced automatically at creation - [AppDelegate.fs](https://github.com/fsprojects/Fabulous/blob/master/templates/content/blank/NewApp.macOS/AppDelegate.fs))
- Add a condition to create the GTK project only when we give the flag `--GTK` (like WPF is `--WPF` - [template.json](https://github.com/fsprojects/Fabulous/blob/master/templates/content/blank/.template.config/template.json) and [NewApp.sln](https://github.com/fsprojects/Fabulous/blob/master/templates/content/blank/NewApp.sln))


@jimbobbennett has already made a sample GTK app that matches the Fabulous template https://github.com/jimbobbennett/SqueakyAppLinuxAndMac

**Comment by TimLariviere** [comment]
Released in version 0.30.0
