### ISSUE TITLE
So what the heck is "dispatch"?

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/Fabulous#263]
Not sure where to ask this question - but I am have a hard time understanding where the dispatch function is defined in the samples.  I see it is used in the View and dispatch is passed into an anonymous function tied to the event of the visual controls.  But I don't see where dispatch is defined - only it is passed into the View function and is then inferred by usage.  Is there some docs that I am not aware of?

**Comment by Zaid-Ajaj** [comment]
Hello @jamessdixon, `dispatch` is defined from within Elmish module and it is given to your root view function internally when you construct the `Program` along with the `update` function etc. it is a neat inversion of control technique where the library (Elmish in this case) implements what `dispatch` does but let's *you* decide when to actually call it, from your view function. 

As for the implementation details, think about it roughly along the lines of: 
```fs
let dispatch msg = 
  // 1 - compute next state by passing (msg, current state) to update function
  // 2 - calculate next view diffs based on next state
  // 3 -  re-render the view
  // 4 - repeat
```
implementation details are different per implementation (Elmish/Fabulous) but the idea is the same

**Comment by jamessdixon** [comment]
I think my confusion is b/c Visual Studio For Mac was not showing a reference to Fabulous
<img width="294" alt="screen shot 2018-12-23 at 1 43 18 pm" src="https://user-images.githubusercontent.com/1394644/50386633-dfccc980-06b8-11e9-9601-2fab454ac92b.png">


Thanks - it makes more sense now
