### ISSUE TITLE
Missing "Archive..." context menu

### ISSUE THREAD

**Issue by kerams** [fsprojects/Fabulous#266]
I'm running a fresh installation of the mobile development workload in VS 2019 Preview and after creating a new solution with the `fabulous-app` template, I cannot find a way to create an APK from the Android project. The `Archive...` context menu is not present on the project (whereas I see it when I create a solution in VS using the standard Xamarin.Forms template) and while I can open the Archive Manager via Tools, there's nothing that would let me start the process there. This is my first time trying Xamarin, so apologies if I'm missing something obvious. Thanks.

I've just noticed that on the Android Manifest tab in project propertie it says it cannot find AndroidManifest.xml even though it's both on disk and in fsproj.

**Comment by TimLariviere** [comment]
Your issue seems more like a tooling issue in VS 2019.
It's still in early preview for now, and as far as I can tell it has some issues with the Xamarin/F# tooling (for instance, this repo won't open in VS 2019).

**Comment by kerams** [comment]
Good to know, thank you.
