### ISSUE TITLE
LiveUpdate failures

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#281]
Here is a list of some cases where LiveUpdate fails to run.

- Assigning an event callback produces an "AddToObservable not supported" error (https://github.com/fsprojects/Fabulous/issues/281#issuecomment-457137755)
- After a few iterations of simple changes the app started throwing OutOfMemoryException (https://github.com/fsprojects/Fabulous/issues/281#issuecomment-455768379)
- Named fields in DU cases produces "couldn't find field NumberOfRepetitions in type DNamedType" (https://github.com/fsprojects/Fabulous/issues/281#issuecomment-460947730)

Fixed:
- Using ViewRef<T> produces a "No member found for key Fabulous.DynamicViews.ViewRef" error (https://github.com/fsprojects/Fabulous/issues/281#issuecomment-454885771) - Fixed by #286 
- Using a list a "No member found for key Microsoft.FSharp.Collections.FSharpList" error (https://github.com/fsprojects/Fabulous/issues/281#issuecomment-455767701) - Fixed by #286 
- Calling a function that takes unit from a module in a separate dll produces a "No member found for key" error (https://github.com/fsprojects/Fabulous/issues/281#issuecomment-455538037) - Fixed by #286

**Comment by TimLariviere** [comment]
From kevkov on Slack

Code:
```
let theRef = ViewRef<Label>()
```

Result:
```
{"Quacked":"couldn't quack! the evaluation of the decalarations in the code package failed: System.Exception: No member found for key (REntity Fabulous.DynamicViews.ViewRef`1[T], \".ctor\",\n RTypes [|Microsoft.FSharp.Core.Unit|])\n 
```

**Comment by kevinha** [comment]
Assigning an event callback produces an "AddToObservable not supported" error, e.g.
`fun (entry:Entry) -> entry.Unfocused.Add(fun args ...`

**Comment by kevinha** [comment]
Calling a function that takes `unit` from a module in a separate dll:

`let allSubjects = Database.getProfilesSummary ()`

produces

`android.runtime.JavaProxyThrowable: System.Exception: No member found for key (REntity Storage+Database, "getProfilesSummary", RTypes [|Microsoft.FSharp.Core.Unit|])`

while 

`let allSubjects = Database.getProfilesSummary 1`

is ok.

**Comment by dsyme** [comment]
I'll try to get these fixed today, thanks

**Comment by kevinha** [comment]
After a few iterations of simple changes the app started throwing OutOfMemoryException:
```
fscd: GOT PortaCode for C:\...\HomePage.fs
fscd: GOT JSON for C:\...\HomePage.fs, length = 11847451
```

```
01-19 10:16:48.987 9504-12035/com.moodsnmoves I/mono-stdout: LiveUpdate: setting response code to 500, msg = <html><body><pre>System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
        at (wrapper alloc) System.Object.AllocVector(intptr,intptr)
      at System.Text.StringBuilder.ExpandByABlock (System.Int32 minBlockCharCount) [0x00085] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
      at System.Text.StringBuilder.Append (System.Char* value, System.Int32 valueCount) [0x00082] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
      at System.Text.StringBuilder.Append (System.Char[] value, System.Int32 startIndex, System.Int32 charCount) [0x00081] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
      at System.IO.StreamReader+<ReadToEndAsyncInternal>d__63.MoveNext () [0x00046] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
```

**Comment by dsyme** [comment]
> Assigning an event callback produces an "AddToObservable not supported" error, e.g.
>      fun (entry:Entry) -> entry.Unfocused.Add(fun args ...

Any chance of a full repro for this? Just so I'm not guessing :)

**Comment by kevinha** [comment]
Sorry, only just seen your replies. For the event handler one:

```
View.Editor(created=(fun editor -> editor.Unfocused.Add(fun args -> ())))
```
produces
```
fscd: GOT PortaCode for C:\...\HomePage.fs
fscd: ERROR SENDING TO WEBHOOK: "System.Exception: error converting rhs of view
System.Exception: NYI: extension of generic type, needs FCS support: AddToObservable
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
...
 ```

The app is not open source but I can give you access if you want.

**Comment by kevinha** [comment]
@dsyme I've put the app in a private repo on GH and you have been invited. I have been using a Google Pixel API 27 emulator. The memory starts at about 12mb for a newly installed app but then goes up 64mb after a few live update changes and then throws an OOM. It should be fairly easy to reproduce. The code for the inital page is HomePage.fs and you can change the Label at line 138 to get live update feedback.

Please bear in mind this is very much a work in progress, discovery and accruing of technical debt. You can use the code as a source of how not to do things if you like, along as you **don't** acknowledge the authors. Of course we'd be glad for any feedback as along as we can respond with weak excuses.

**Comment by kevinha** [comment]
Named fields in DU cases don't work. For example:

```
    type Metric =
        | Timed of Duration:TimeSpan
        | Repeated of NumberOfRepetitions:int
```
produces
```
   System.Exception: couldn't find field NumberOfRepetitions in type DNamedType
      (DEntityRef
         "Models+Metric, Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
       [||])
      at FSharp.Compiler.PortaCode.Interpreter+EvalContext.EvalApplicationOfArg (FSharp.Compiler.PortaCode.Interpreter+Env env, FSharp.Compiler.PortaCode.Interpreter+Value funcV, System.Object[] argsV) [0x0013a] in <5c59d3b72f731447a7450383b7d3595c>:0 
...
```

**Comment by davidtme** [comment]
I get the same error using live update in a WPF app:

`
System.Exception: 'couldn't find field Item in type DNamedType
  (DEntityRef
     "Microsoft.FSharp.Core.FSharpChoice`2, FSharp.Core, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
   [|DNamedType
       (DEntityRef
          "Microsoft.FSharp.Collections.FSharpList`1, FSharp.Core, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
        [|DNamedType
            (DEntityRef
               "System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
             [||])|]);
     DNamedType
       (DEntityRef
          "System.Exception, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
        [||])|])'
`

**Comment by TimLariviere** [comment]
Right now in v2, we abandon LiveUpdate. Might come back later in the future.
