### ISSUE TITLE
nuget.targets bug in Templates

### ISSUE THREAD

**Issue by jiangzhen3s** [fsprojects/Fabulous#288]
https://github.com/fsprojects/Fabulous/blob/master/templates/content/blank/.nuget/NuGet.targets#L53

> <PaddedSolutionDir Condition=" '$(OS)' == 'Windows_NT'">"$(SolutionDir) "</PaddedSolutionDir>

==》    "$(SolutionDir)\\"

**Comment by mallibone** [comment]
Hey @jiangzhen3s thanks for finding this one, I just stumbled over it myself. There seems to be another issue with that line that it ends with a `\` which is a problem when running `build.cmd Test` on Windows. I hope I'll have a fix later today so we can run the build and tests on Windows.

@TimLariviere this would mean we could also adapt [Azure DevOps CI](https://github.com/fsprojects/Fabulous/pull/285) to run the tests on every commit/pull request.
