### ISSUE TITLE
TitleView on NavigationPage doesn't work

### ISSUE THREAD

**Issue by chrisseed** [fsprojects/Fabulous#292]
The ```titleView``` argument of ```View.NavigationPage``` has no effect; nor does using the ```TitleView``` method on ```ViewElement```.

This is because ```NavigationPage.TitlePage``` is actually an attached property that needs to be applied to the pages you add to a ```NavigationPage```, rather than a property you set on ```NavigationPage``` itself.

**Comment by chrisseed** [comment]
I've got the fix for this, will submit a PR just as soon as I figure out how to do it ...

**Comment by TimLariviere** [comment]
Fixed in #305
