### ISSUE TITLE
Nullreferenceexception on MacOS changing Page

### ISSUE THREAD

**Issue by SergejDK** [fsprojects/Fabulous#295]
There is a problem with e.g. the AllControls sample on mac.
When you click on "MainPage" button it will crash.

This issue is from XF itself so we do not really need to change a thing at our side.

Here to track: [https://github.com/xamarin/Xamarin.Forms/issues/4156](https://github.com/xamarin/Xamarin.Forms/issues/4156)

**Comment by SergejDK** [comment]
This issue seems to be resolved. In the next Version of XF this issue should be gone!
I don't know which version it is but I think 3.5 or 4.0.

**Comment by SergejDK** [comment]
Seems like XF 3.5 is out.
So when we update in the next time this problem should be gone.

**Comment by sergey-tihon** [comment]
Simple update of Xamarin.Forms to 4.5.0 does not solve this issue for me
I hope that it will gone with fresh update of Fabulous

**Comment by SergejDK** [comment]
The update will maybe not enough. Just saw an issue in XF where the issue still appears...

**Comment by SergejDK** [comment]
With 3.6 it seems to work on my mac.
So we can close this?

**Comment by SergejDK** [comment]
Tests are fine so can be closed here.
