### ISSUE TITLE
dotnet new fabulous-app doesn't build

### ISSUE THREAD

**Issue by jtourlamain** [fsprojects/Fabulous#298]
After installing the dotnet template on WSL I can create a new template and the solution builds. 

**Problem:**
When doing the same thing via powershell you can create a solution but it doesn't build. 
You get an error on the NuGet packages:
```
1>D:\\Fab2\Fab2\.nuget\NuGet.targets(92,9): error : Could not find a part of the path 'D:\\Fab2\Fab2\ \packages\FSharp.Core.4.5.2'.
```

**Possible cause:**
Notice the space in the error message between `\Fab2\` and `\packages\` 

**Reproduction steps:**
- Open powershell
- install the template `dotnet new -i Fabulous.Templates`
- create a new Fabulous solution `dotnet new fabulous-app -n Fab2`
- open the solution in Visual Studio (I used VS2017 version 15.9.5)
- build the solution

**Temporary workaround:**
Create a new solution via WSL.

**Comment by mallibone** [comment]
Thanks for reporting the issue - the good news is that this should be fixed in the next release with #290.
