### ISSUE TITLE
Extracting out fscd (Fabulous.Cli)

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#302]
`fscd` (aka Fabulous.Cli) is really a general purpose tool for watching F# projects and sending them to a web hook, plus code to interpret the resulting code package on-device against an appropriate set of DLLs.

I'd like to extract out this component with a view to reusing it in other settings and looking at realigning this with other F# project watching tools.  This will allow other projects to benefit from interpretation when it makes sense to use it, and allow this project to benefit from improvements to project cracking and watching made by other tools

This is not an easy task.  For reference, some tools that do project-cracking and watching are
* [FAKE 5](https://fake.build/apidocs/v5/fake-io-changewatcher.html)
* [FsAutoComplete](https://github.com/fsharp/FsAutoComplete)
* [FscWatch](https://github.com/humhei/FCSWatch/)
* I have some other projects where I also plan to implement live-project-watching or live-script-interpretation.

Aligning the functionality of all these into a single tool is hard or impossible and not necessarily what we want.  However the interpreter and CodeModel of this repo should at least be reusable in other projects.  Also the send-code-package-updates-to-webhook seems reasonably general.

Anyway I propose doing this step by step so that at least this repo and other repos I'm working in can share functionality.  Proposed steps might be:

1. Move most of the files to `fsprojects/FSharp.Compiler.PortaCode` and put them in a nuget with a dependency on the FCS nuget. The `Interpreter.fs` would be a source file in the nuget package to ensure it matches the package release.

2. Possibly create a new general-purpose global CLI tool (though I think it's kind of good that fabulous has one of its own)

**Comment by davidglassborow** [comment]
For other interested, the code is now in https://github.com/fsprojects/FSharp.Compiler.PortaCode

**Comment by TimLariviere** [comment]
@dsyme Should we close this issue now that PortaCode has been put in its own repo?
