### ISSUE TITLE
Add documentation on updating fabulous-cli when upgrading to a new Fabulous version

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#306]
`fabulous-cli` and `Fabulous.LiveUpdate` need to use the exact same version in order to work correctly.

In the docs, we don't give the steps to upgrade or downgrade the installed fabulous-cli.

**Comment by SergejDK** [comment]
@TimLariviere 
wouldn't this be just:
`dotnet tool install -g fabulous-cli`
`dotnet tool update -g fabulous-cli`
or for downgrade:
`dotnet tool install -g fabulous-cli --version {versionnumber}`

**Comment by TimLariviere** [comment]
Seems to be exactly that. :)
