### ISSUE TITLE
Consider using Debug.WriteLine instead of Console.WriteLine/printfn

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#307]
Most output generated by Fabulous goes to the console through `Console.WriteLine` or `printfn`.
For platforms like WPF, Visual Studio doesn't show console outputs into the Output window.

`Program` is extensible to use a tracing function that can print elsewhere, but some outputs from Fabulous don't go through this function.
We need to provide an extension point where the developers can get all the messages from Fabulous.

`Debug.WriteLine` seems a good candidate.
It can be extended using Listeners like
```fsharp
System.Diagnostics.Debug.Listeners.Add(new ConsoleTraceListener()) |> ignore
System.Diagnostics.Debug.WriteLine("Hello")
```

**Comment by edgarfgp** [comment]
I would like to contribute to this project. And this look like a good first one due to my knowledge of fsharp let me know if this still available .

**Comment by TimLariviere** [comment]
@edgarfgp Yes. It's still available.
Feel free to contribute on this one!

The main issue is mostly with WPF.
When executing it, the output is not visible in the Debug window of Visual Studio.
But when executing it as a Console app (can be changed in the Properties of the WPF project), the output is visible in the opened Console.

I think it's because we are using `Console.WriteLine()` and not `Debug.WriteLine()`.

**Comment by edgarfgp** [comment]
Update : I'm currently working in this issue

**Comment by TimLariviere** [comment]
Great! :)
No, nothing particular has changed regarding this issue. It's basically the same code.
