### ISSUE TITLE
Prefered way of making pull requests

### ISSUE THREAD

**Issue by pauldorehill** [fsprojects/Fabulous#314]
On making my first pull request I went over the [Contributor Guide](https://github.com/fsprojects/Fabulous/blob/master/DEVGUIDE.md) and I couldn't find anything about branches? Is the preferred method to do a topic branch?

**Comment by TimLariviere** [comment]
We don't have a policy over the Git strategy.
Usually we fork from Fabulous/master, do a branch for the feature/fix we want, and then do a Pull Request to Fabulous/master.

**Comment by pauldorehill** [comment]
ok great - if you're happy I'll add something along those lines to the guide?

**Comment by TimLariviere** [comment]
Thanks, that would be great. :)
