### ISSUE TITLE
Fabulous logo for Fabulous

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/Fabulous#319]
Today on twitter we started discussion about logo candidates for Fabulous
https://twitter.com/kunjee/status/1093008978332864512

### Option 1:
Currently we have one proposal with [3 positive feedbacks](https://twitter.com/sergey_tihon/status/1093052372467761152):
![fabulous_log](https://user-images.githubusercontent.com/1197905/52371637-2444d680-2a67-11e9-9afa-bd35ff203320.png)

Happy to hear other options/opinions.

**Comment by MangelMaxime** [comment]
I find the angles of the `F` really sharp.

If you look at the Xamarin logo, you can see that they put a small border-radius.

**Comment by sergey-tihon** [comment]
@MangelMaxime Good catch! (said my wife)

### Option 2 (with border radius):
![fabulous_logo](https://user-images.githubusercontent.com/1197905/52372623-b0f09400-2a69-11e9-820b-9a22e69741ab.png)

**Comment by MangelMaxime** [comment]
I do prefer this version :)

**Comment by TimLariviere** [comment]
Good initiative!

Option 2 is better. :)
Perhaps with a different color?
It's a little too close to the Xamarin logo, it might confuse people.

Also I'd like to avoid a "Xamarin" logo, as lots of people are asking support for other frameworks like Avalonia/Uno as well.
Something we might be able to do in a distant future.

I must say I've never been a fan of the Xamarin logo, so partial here. :)

**Comment by dsyme** [comment]
> Also I'd like to avoid a "Xamarin" logo, as lots of people are asking support for other frameworks like Avalonia/Uno as well.

Yes.... I said "yes" to Xamarin-like logo on twitter, I thought it over and wondered the same thing....   But equally I'm no good at logo design.....

Note also that the React/Flux/Flow... technologies all use logos which carry a "flowing information around the app, reacting to changes".  That might be a place to start.

**Comment by TimLariviere** [comment]
I was thinking:
Maybe we should play on the word "Fabulous" for the logo.
Make it memorable for people, instead of an abstract logo.

Do like Fable and use something related to "fabulous". Like a mythical beast for example.

There's a lot of phoenix logo on the web, it seems... :)
![image](https://user-images.githubusercontent.com/6429007/52556537-230c0480-2ded-11e9-80c2-f7598ea9066c.png)

**Comment by drk-mtr** [comment]
Not particularly serious suggestions these, just playing around with ideas...

![fabulous1](https://user-images.githubusercontent.com/40315783/52902121-475c4c80-3204-11e9-851a-9987c78e5ac5.png)

![fabulous3](https://user-images.githubusercontent.com/40315783/52902122-4aefd380-3204-11e9-891d-50f410170569.png)

**Comment by Happypig375** [comment]
What about the signature F# operator?
![image](https://user-images.githubusercontent.com/19922066/55289935-4b80aa00-53ff-11e9-8742-d4213b29c669.png)

Credits: Good ol' Paint on Windows 10

**Comment by TimLariviere** [comment]
Closing since Fabulous as a logo now.
