### ISSUE TITLE
Add `SizeChanged` event

### ISSUE THREAD

**Issue by johannesegger** [fsprojects/Fabulous#326]
I would like to store the size of an `AbsoluteLayout` control within my model, because based on that I can tell whether some controls (i.e. players) within this layout are touching the border. Xamarin.Forms has `VisualElement.SizeChanged`, but in Fabulous I couldn't find something similar. The only thing I found was `OnSizeAllocatedCallback` which only works when attached to a `ContentPage`.

Would it be possible for you to enable `SizeChanged` events for `ViewElement`s or how else could I store the size of a specific control within my Elmish model?

**Comment by TimLariviere** [comment]
Thanks for reporting.
We will add `SizeChanged` and the other missing events from VisualElement.

**Comment by johannesegger** [comment]
Awesome, thanks a lot for adding this so fast.

**Comment by johannesegger** [comment]
Hm, not sure if this helps me a lot, though:

```fsharp
View.AbsoluteLayout(...)
|> sizeChanged (fun _ -> dispatch (SetSceneSize ???))
```

How do I get the size now from within the event handler? I neither get the sender nor do I get useful event args.

**Comment by TimLariviere** [comment]
Ah. Xamarin.Forms does not send the new size...
>SizeChanged?.Invoke(this, EventArgs.Empty);

As I would prefer not to pass the sender, I think we can create a new type `SizeChangedEventArgs` which will store the width and height of the control.
This will allow this kind of code:

```fsharp
View.AbsoluteLayout(...)
|> sizeChanged (fun args -> dispatch (SetSceneSize (args.Width, args.Height)))
```

**Comment by johannesegger** [comment]
Yeah, I would also prefer that, thanks a lot.
