### ISSUE TITLE
Upgrade to Xamarin.Forms 3.5

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#329]
Now that Xamarin.Forms 3.5.0 is out, we can start work to integrate this new version.
This should fix #155 and #295 as well

**Comment by TimLariviere** [comment]
For reference, here's the delta between XF 3.4.009999 and 3.5.0.129452
https://www.fuget.org/packages/Xamarin.Forms/3.5.0.129452/lib/netstandard2.0/diff/3.4.0.1009999/

**Comment by SergejDK** [comment]
Are there some parts which we can say we won't add them, so we can make a more clearly list? So define which things we need.  
E.g. interfaces and enums we do not have to look at, right?
Are there some other parts which you know about?
