### ISSUE TITLE
Consider moving the half-elmish approach in another project

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#333]
Today both the Half-Elmish and Full-Elmish approaches are in the same project `Fabulous.Core`.
Some code is shared between the two (not much though), but enough to make us wonder if we should  duplicate out the half-elmish approach to allow us to make changes easier. (like adding better type annotation https://github.com/fsprojects/Fabulous/pull/313#issuecomment-460846596)

As we're not actively supporting half elmish, it has been suggested to either move it out of `Fabulous.Core` or deprecate it. https://github.com/fsprojects/Fabulous/pull/313#issuecomment-461376915

I think we should move out the half elmish approach in another project in this repository to start.
We also need to consider if we should go as far as put it in its own Github repository.

**Comment by pauldorehill** [comment]
@TimLariviere have you had any takers for this one?

**Comment by TimLariviere** [comment]
@pauldorehill No. Feel free to take it if you want. :)
