### ISSUE TITLE
I've made a Xamarin Native demo project that is like Half-Elmish

### ISSUE THREAD

**Issue by RyanBuzzInteractive** [fsprojects/Fabulous#335]
Hey everyone,

I'm not sure what the etiquette is around sharing your own work in the issues thread, apologies if it isn't appropriate, feel free to remove this or tell me to put it elsewhere.

I have recently discovered Elmish/Fabulous and the MVU pattern and I really wanted to get involved as I use Xamarin at work and have started doing all my core code in F#.

The thing is, we don't use Xamarin Forms, the UI guys all only use C#, and are only familiar with MVVMLight.

Although I haven't ever used Elmish or Fabulous directly, I read the docs and thought about it and decided to roll my own based on the Half-Elmish approach. I have a totally different implementation but have used the same naming where possible and have pinched the Cmd module. It should be easy to read for anyone familiar with this project I think (hope!).

It also allows unit testing of the commands, I know you guys have been discussing approaches to this, so maybe something will be useful there. 

I have put to together a basic sample app and I would love to hear what people think. There is a full explanation in the readme. I think it is really promising and I can't wait to use it in my next production app if possible :)

Thanks for all the inspiration!

https://github.com/RyanBuzzInteractive/Xamarin-Native-Elmish-Style

**Comment by TimLariviere** [comment]
Awesome. Will take it for a spin when I have some time.

>It also allows unit testing of the commands, I know you guys have been discussing approaches to this, so maybe something will be useful there.

I'm curious how you managed to handle cases where a Cmd might not return a message (what we called `Cmd.ofMsgOption` or `Cmd.ofAsyncMsgOption`) and cases where a Cmd might return dispatch several messages.
Is it something you allow?

**Comment by RyanBuzzInteractive** [comment]
I think I can handle that - I'll walk through what I do and you can tell me if I have misunderstood or missed something out.

My tests for this are perhaps a little unidiomatic in that they use some mutable flags, but there was a reason for this, which is that the mailboxes run on separate threads to the test so any assertions inside them or things they execute are missed by the test runner. I found that assigning to a var in the body of the test and introducing a small async delay was a way around this. I'm sure there is probably a better approach.

As I parameterise all of an updater's child-updater dependencies I can easily pass in test doubles which act however I want, and I can set them to return a particular command so I can check that it is being mapped and batched properly with the parent's commands.

I take the output from the updater under test and actually pass it to Cmd.execute, but with a lambda dispatch func so I can spy on the output from the commands and check for expected values.

In the case of an async Cmd which doesn't dispatch anything to spy on, again the async func being executed will have been passed into the updater on construction, so we can pass in any async func we want which will set a flag if it has been run with the correct args.

Of course the updaters have all their dependencies partially applied during construction of Program so the version used by consumers is just a plain mailbox.

I'll paste some code from my sample project, but strip out most of it apart from the relevant bit. 

It is the increment counter message, which I added a behaviour to in order to test chaining cmds. If it is a multiple of 5, it will dispatch a message to start an async request. 

I wanted to test that 
a.) The child counter cmd returned from its updater was mapped and batched with the pain page's cmd
b.) The main page's command was a Make Request command

A Make Request message returns an Cmd.ofAsync which wraps the injected async operation. In this case I want to test that the operation is returned and also passed the correct Success and Failure handlers.

Main page updater:

` let update 
        asyncOperation
        (counterUpdate : MailboxProcessor<CounterMsg*CounterModel*AsyncReplyChannel<CounterModel*Cmd<CounterMsg>>>) =
        MailboxProcessor<MainMsg*MainModel*AsyncReplyChannel<MainModel*Cmd<MainMsg>>>.Start (fun inbox ->
            let rec innerLoop (maybeProgram : MailboxProcessor<ProgramMsg> option) =
                async {
                    
                    let! (message, model, replyChannel) = inbox.Receive()
    
                    let! newModel, newCommand, newProgram = 
                        async{
                            match message with
                            | MainMsg.Increment position -> 
                                let! newCountModel, countCmd =
                                    match position with 
                                    | One -> counterUpdate.PostAndAsyncReply (fun asyncReplyChannel -> CounterMsg.Increment, model.Count1, asyncReplyChannel)
                                    | Two -> counterUpdate.PostAndAsyncReply (fun asyncReplyChannel -> CounterMsg.Increment, model.Count2, asyncReplyChannel)
                                
                                if newCountModel % 5 = 0 && model.Loading = false
                                then
                                    let newModel = 
                                        match position with 
                                        | One -> {model with Count1 = newCountModel; Result = "Multiple of 5 reached, requesting odd number..."}
                                        | Two -> {model with Count2 = newCountModel; Result = "Multiple of 5 reached, requesting odd number..."}
                                    return newModel, Cmd.batch [ Cmd.ofMsg MainMsg.MakeRequest
                                                                 (Cmd.mapWithId MainMsg.CounterMessage (countCmd, position)) ], maybeProgram
                                else
                                    let newModel = 
                                        match position with 
                                        | One -> {model with Count1 = newCountModel;}
                                        | Two -> {model with Count2 = newCountModel;}
                                    return newModel, (Cmd.mapWithId MainMsg.CounterMessage (countCmd, position)), maybeProgram
                           
                            | MainMsg.MakeRequest ->
                                if model.Loading = false 
                                then
                                    let newModel = { model with Loading = true }
                                    let newCommand = Cmd.ofAsync asyncOperation () MainMsg.ShowSuccess MainMsg.HandleError
                                    return newModel, newCommand, maybeProgram
                                else
                                    return model, Cmd.none, maybeProgram
                            | MainMsg.ShowSuccess result -> return {model with Result = string result; Loading = false}, Cmd.none, maybeProgram
                            | MainMsg.HandleError error -> return {model with Result = error.Message; Loading = false}, Cmd.none, maybeProgram
                            | MainMsg.CounterMessage (msg, position) ->
                                let! countModel, countCmd = 
                                    counterUpdate.PostAndAsyncReply (fun asyncReplyChannel -> msg, model.Count1, asyncReplyChannel)
                                let newModel =
                                    match position with
                                    | One -> 
                                        {model with Count1 = countModel}
                                    | Two ->
                                        {model with Count2 = countModel}
                                return newModel, (Cmd.mapWithId MainMsg.CounterMessage (countCmd,position)), maybeProgram
                        }
                    
                    replyChannel.Reply(newModel, newCommand)
                    do! innerLoop newProgram
                }

            innerLoop None) `

Test for Increment child cmd batching with Make Request cmd :

`[<Test>][<AutoData>][<AsyncStateMachine(typeof<Task>)>]
    let ``Increment returns MakeRequest cmd if counter multiple of 5 and wraps counter cmds`` 
        () =

        let inputModel = Main.init
        let newCounterModel = 5
        let mutable makeRequestCmdTriggered = false;
        let mutable counterCmdTriggered = false;

        let counterUpdate =
            MailboxProcessor<CounterMsg*CounterModel*AsyncReplyChannel<CounterModel*Cmd<CounterMsg>>>.Start (fun inbox ->
                let rec innerLoop () =
                    async {
                        let! (message, model, replyChannel) = inbox.Receive()
                        match message with 
                        | CounterMsg.Increment -> replyChannel.Reply(newCounterModel, Cmd.ofMsg CounterMsg.Increment)
                        | CounterMsg.Decrement -> failwith "Wrong message"
                        do! innerLoop ()
                    }
                innerLoop ())

        let sut = Main.update Main.longRunningOperationThatCanThrow counterUpdate

        async
            {
                let! _, nextCmd = 
                    sut.PostAndAsyncReply(fun asyncReplyChannel -> MainMsg.Increment CounterTag.One, inputModel, asyncReplyChannel)
                
                Cmd.exec (fun msg ->
                            match msg with
                            | MakeRequest -> makeRequestCmdTriggered <- true
                            | CounterMessage (m,id) ->
                                match m, id with
                                | (CounterMsg.Increment, CounterTag.One) -> counterCmdTriggered <- true
                                | _ -> ()
                            | _ -> ()) nextCmd

                do! Async.Sleep 1

                makeRequestCmdTriggered |> shouldEqual true
                counterCmdTriggered |> shouldEqual true

            }|> Async.StartImmediateAsTask :> Task`

Test for MakeRequest async message dispatch with Success:

`[<Test>][<AutoData>][<AsyncStateMachine(typeof<Task>)>]
    let ``Make request passes async op with correct Success handler`` 
        (opResult : int) =

        let inputModel = Main.init
        let mutable asyncOpSuccess = false
        let mutable asyncOpFailed = false

        let asyncOperation () = 
            async{
                return opResult
            }

        let sut = Main.update asyncOperation Counter.update

        async
            {
                let! _, nextCmd = 
                    sut.PostAndAsyncReply(fun asyncReplyChannel -> MainMsg.MakeRequest, inputModel, asyncReplyChannel)

                Cmd.exec (fun msg ->
                            match msg with
                            | ShowSuccess msg -> asyncOpSuccess <- true
                            | MainMsg.HandleError ex -> asyncOpFailed <- true
                            | _ -> ()) nextCmd

                do! Async.Sleep 1

                asyncOpSuccess |> shouldEqual true
                asyncOpFailed |> shouldEqual false

            }|> Async.StartImmediateAsTask :> Task`

Test for MakeRequest async message dispatch with Failure:

`[<Test>][<AutoData>][<AsyncStateMachine(typeof<Task>)>]
    let ``Make request passes async op with correct Failed handler`` 
        (opResult : int)
        (error : string) =

        let inputModel = Main.init
        let mutable asyncOpSuccess = false
        let mutable asyncOpFailed = false

        let asyncOperation () = 
            async{
                failwith error
                return opResult
            }

        let sut = Main.update asyncOperation Counter.update

        async
            {
                let! _, nextCmd = 
                    sut.PostAndAsyncReply(fun asyncReplyChannel -> MainMsg.MakeRequest, inputModel, asyncReplyChannel)

                Cmd.exec (fun msg ->
                            match msg with
                            | ShowSuccess msg -> asyncOpSuccess <- true
                            | MainMsg.HandleError ex -> asyncOpFailed <- true
                            | _ -> ()) nextCmd

                do! Async.Sleep 1

                asyncOpSuccess |> shouldEqual false
                asyncOpFailed |> shouldEqual true

            }|> Async.StartImmediateAsTask :> Task`

**Comment by RyanBuzzInteractive** [comment]
Also, disclaimer - the sample I made isn't production code, it isn't very pretty at all, it was really trying to test as many aspects of it as fast as I could, trying to find things it couldn't do and prove to myself I had covered all the main bases of UI interaction, inter-screen data passing, parent/child relationships, async etc etc. I will make something a lot nicer and more thought out soon.

**Comment by RyanBuzzInteractive** [comment]
Closed this as I have moved on to creating a full production-ready app using Xamarin Native MVU and the code has moved on a lot from my first experiment that I linked to here.  I will post back when it is at a reasonable state and public.
