### ISSUE TITLE
When using LiveUpdate, old async dispatches affect new app instance

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#340]
When using LiveUpdate, async invokes of the `dispatch` function from the "old" app that complete after the app has been updated are still triggered.

This is wrong in the current model since we don't migrate app state yet.  

In some cases this seems to cause odd behaviour - e.g. the time on the CounterApp just runs on very fast - I'm not entirely sure why - perhaps many updates effectively cause many timer-trigger sequences to be active.

I believe the root cause is the use of [a global dispatch thunk](https://github.com/fsprojects/Fabulous/blob/master/src/Fabulous.Core/ElmishProgram.fs#L14) - the old `dispatch` is the same as the new `dispatch` and the message gets dispatched .  (A global dispatch thunk is used to make "old" view elements in the `dependsOn` table  usable at later points in program execution).  We should probably just reset the `dispatch` thunk and flush the `dependsOn` table on app update, or find another way to allow old view elements to be reused while still capturing `dispatch`.

**Comment by TimLariviere** [comment]
Right now in v2, we abandon LiveUpdate. Might come back later in the future.
