### ISSUE TITLE
ofAsyncMsg is blocking UI

### ISSUE THREAD

**Issue by albertwoo** [fsprojects/Fabulous#345]
Why we are using Async.StartImmediate? In my project it is blocking the UI. I think we should use Async.Start instead.
https://github.com/fsprojects/Fabulous/blob/e6407ce0058152f123d9faba1f559906b9af7d95/src/Fabulous.Core/ElmishCmd.fs#L47

**Comment by TimLariviere** [comment]
`Async.StartImmediate` seems to be the recommended way when dealing with UI.
It runs by default on the current thread (UI thread) and only switches to another thread when needed, coming back to the first one when done.
Also it's more or less the default behavior of `async`/`await` of C#.

I also think it helps performance by preventing unnecessary thread switching.
Like the timer example, no need to start a new thread to ask another thread to wait for 200ms before going back to the UI thread.
Thread switching is really costly, especially on mobile.

If you need to do a long running operation, take a look at the docs:
https://fsprojects.github.io/Fabulous/update.html#threading-and-long-running-operations

**Comment by dsyme** [comment]
Note that nearly all of Fabulous's program update loop could in theory be run of the UI thread in a dedicated background thread, only switching to the UI to actually update the view elements.

The problem is, some user operations like calls to various Xamarin.Essentials operations need the UI thread, and the user would have to code for that.  So at the moment they know that both `view` and `update` and called on the UI thread.  

@TimLariviere I do wonder what the right thing is here - perhaps I made the wrong call - keep it in mind? Thread switching is costly, but blocking the UI thread is more costly still?

**Comment by albertwoo** [comment]
Thanks for reply. If the ofAsyncMsg is designed to be like this, it is ok for me, because I can just extend the Cmd module very easily by myself.

**Comment by TimLariviere** [comment]
>Thread switching is costly, but blocking the UI thread is more costly still?

@dsyme From what I saw in general for Xamarin, in async block, people tend to only do asynchronous I/O via the .NET Framework (web request, file access, etc. -- which don't block the calling thread) and almost never do any computation that could impact the UI responsiveness.
If they do, they quickly learn to start a new thread (`Task.Run`) and this seems commonly accepted.

So all in all, I think it's ok to let the user choose when to actually switch to the thread pool.
Most of the time, it won't be needed and this prevents unwanted performance issues.

**Comment by mallibone** [comment]
I agree with @TimLariviere. Most Xamarin Apps run on the UI thread and execute non-blocking async calls. I would question if the work performed on the background thread would be justified in general. Plus having to sync to the UI thread for certain operations, e.g. Xamarin.Essentials would be a headscratcher for newcomers.

**Comment by dsyme** [comment]
OK, well, good to have this checked. 

Keep it in mind should people start hitting scenarios where the cost of view reevaluation and diffing becomes a cause of significant UI thread blocks. It might be easy and safe to add an option to do those specific operations off the UI thread. (That might mean skipping UI updates should model updates be triggered faster than the view updates are processed, eg by a flood of async events)
