### ISSUE TITLE
Is it possible to set breakpoints in App?

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/Fabulous#346]
I've set a breakpoint in App but it is not fired at all.
Is this behavior intentional?

**Comment by xperiandri** [comment]
![image](https://user-images.githubusercontent.com/2365592/53406039-c6e6da00-39c1-11e9-8287-ad3db9d0c8d7.png)
While breakpoint is here
![image](https://user-images.githubusercontent.com/2365592/53406053-cf3f1500-39c1-11e9-9f9f-a77bb53de926.png)

**Comment by SergejDK** [comment]
Normally it should work.
Which version of VS and Fabulous do you use? 

Could you provide a sample project where the problem can be reproduced?

**Comment by xperiandri** [comment]
VS 2019 Enterprise Preview 3.0
It works for UWP but not for Android

**Comment by SergejDK** [comment]
I'll take a look but I think this might be a vs 2019 bug. 
Do you use a real device or emulator? Which android version?

**Comment by TimLariviere** [comment]
@xperiandri Do you still have the issue?
