### ISSUE TITLE
Upgrade to Xamarin.Forms 3.6

### ISSUE THREAD

**Issue by mallibone** [fsprojects/Fabulous#357]
Xamarin.Forms 3.6 has been released. Fuget API changes since 3.5 [here](https://www.fuget.org/packages/Xamarin.Forms/3.6.0.220655/lib/netstandard2.0/diff/3.5.0.169047/).

**Comment by SergejDK** [comment]
After the PR with the upgrade to 3.5 I can upgrade to 3.6.
Seems like not much changed.

**Comment by PureWeen** [comment]
go straight to 4.0 👍
