### ISSUE TITLE
Lottie Animation Non-Xaml Sample working with Fabulous ContentPage

### ISSUE THREAD

**Issue by sdaves** [fsprojects/Fabulous#358]
Does anyone have a non xaml example of Lottie working with Fabulous?

Here's a basic Com.Airbnb.Xamarin.Forms.Lottie example using xaml:

```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    xmlns:lottie="clr-namespace:Lottie.Forms;assembly=Lottie.Forms" 
    x:Class="AnimationDemo.SplashPage" >
    <ContentPage.Content>
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="*" />
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*" />
            </Grid.ColumnDefinitions>
            <lottie:AnimationView
                Grid.Row="0" Grid.Column="0"
                Loop="true" AutoPlay="true" Animation="material_wave_loading.json" />
        </Grid>
    </ContentPage.Content>
</ContentPage>
```

https://github.com/codemillmatt/forms-animations/blob/dbb1c0b7563cdfdcbfe8c364d8599c5ba82ee440/src/AnimationDemo/AnimationDemo/SplashPage.xaml

My best guess would be to create the Lottie.Forms.AnimationView class and try to render that as a ViewElement, or use custom renderers, but I would love feedback if there's an easier way.

**Comment by TimLariviere** [comment]
@sdaves If you don't need to interact with the animation (apart from displaying it, remove it from the screen), you can write a simple Fabulous wrapper for it.
See https://fsprojects.github.io/Fabulous/views-extending.html

Something like that
```fsharp
[<AutoOpen>]
module LottieExtensions =

    open Fabulous.Core
    open Fabulous.DynamicViews

    let LottieAnimationFileAttribKey = AttributeKey<string> "LottieAnimationView_AnimationFile"

    type Fabulous.DynamicViews.View with
        static member LottieAnimationView(?animationFile: string) =
            let attribCount = 0
            let attribCount = match animationFile with Some _ -> attribCount + 1 | None -> attribCount

            let attribs = new AttributesBuilder(attribCount)
            match animationFile with None -> () | Some v -> attribs.Add (LottieAnimationFileAttribKey, v)

            // The creation method
            let create () = new Lottie.Forms.AnimationView()

            // The incremental update method
            let update (prev: ViewElement voption) (source: ViewElement) (target: ABC) =
                source.UpdatePrimitive (prev, target, LottieAnimationFileAttribKey, (fun target -> target.Animation), (fun target v -> target.Animation <- v))

            ViewElement.Create<Lottie.Forms.AnimationView>(create, update, attribs)
```

**Comment by sdaves** [comment]
You're a badass @TimLariviere 👍 Thanks

**Comment by dsyme** [comment]
@sdaves Any chance you could you add an extension under `extensions` for Lottie? Then we all get to use it :)

**Comment by dsyme** [comment]
@sdaves `extensions` is sort of a `contrib` folder. Perhaps we could rename it to that

**Comment by anhlt** [comment]
views-extending work well in android but not working in IOS. Any idea to work around with this issue?
@TimLariviere 
@sdaves 

https://stackoverflow.com/questions/54386715/lottie-animationview-not-working-in-ios-but-is-working-in-android-c-sharp-implem
