### ISSUE TITLE
LiveUpdate issue when using custom compiler define symbols

### ISSUE THREAD

**Issue by sandeep-eroad** [fsprojects/Fabulous#361]
Live update works fine if DEBUG compiler define is used, but if a custom compiler define is used then live update fails.

A possible solution would be to make live update work with custom compiler define symbols or make it work with LIVE_UPDATE compiler define.

**Comment by TimLariviere** [comment]
@sandeep-eroad I think you're hitting the same problem as I did.
The interpreter ignores custom compiler instructions.
https://github.com/fsprojects/FSharp.Compiler.PortaCode/issues/12

**Comment by willsam100** [comment]
It is possible to define custom compiler symbols on the comand line when starting the live update tool `--define:LIVE_UPDATE`. 
The full command is then `fabulous --watch --send --define:LIVE_UPDATE`
Note this does not work if you specify the `fsproj` file as well - https://github.com/fsprojects/FSharp.Compiler.PortaCode/blob/7bc5e17b32d848024e4635553eda3fc0afbb5156/src/ProcessCommandLine.fs#L118

**Comment by TimLariviere** [comment]
Would be great to write documentation on that subject.
As well as see if a simple change to PortaCode would allow to support fsproj files

**Comment by TimLariviere** [comment]
Right now in v2, we abandon LiveUpdate. Might come back later in the future.
