### ISSUE TITLE
How do I set an AbsoluteLayout.Background Image property?

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/Fabulous#368]
I am porting legacy code to Fabulous, but I can't seem to get an AbsoluteLayout's background property to set.  Intellisense shows it in the .ctor, but when I set it, I get a compile error

<img width="851" alt="Screen Shot 2019-03-28 at 4 49 18 PM" src="https://user-images.githubusercontent.com/1394644/55191804-79ed5380-5179-11e9-92e8-5c1fd8762f86.png">

<img width="471" alt="Screen Shot 2019-03-28 at 4 44 38 PM" src="https://user-images.githubusercontent.com/1394644/55191614-03505600-5179-11e9-9a38-4d4588e20ea8.png">

Note that setting the same image via the children parameter does work...

**Comment by TimLariviere** [comment]
I've always found IntelliSense in VS for Mac to be a bit misleading.
Here it's not showing you the parameters of the constructor, but everything it can find in Fabulous.

It's showing you the `backgroundImage` function.
>    /// Adjusts the BackgroundImage property in the visual element
>    let backgroundImage (value: string) (x: ViewElement) = x.BackgroundImage(value)

AbsoluteLayout has no `BackgroundImage` property, only `BackgroundColor`.
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.absolutelayout?view=xamarin-forms#properties

**Comment by jamessdixon** [comment]
I don’t think that is right -> The old code worked fine and there defiantly was a BackgroundImage property.

Maybe AbsoluteLayout inherits from a lower class that has a BackgroundImage property?

**Comment by SergejDK** [comment]
The Page-Class defines a BackgroundImage.
[https://docs.microsoft.com/de-de/dotnet/api/xamarin.forms.page.backgroundimage?view=xamarin-forms#Xamarin_Forms_Page_BackgroundImage](https://docs.microsoft.com/de-de/dotnet/api/xamarin.forms.page.backgroundimage?view=xamarin-forms#Xamarin_Forms_Page_BackgroundImage)

Maybe you can add it to the contentpage and the content is an absolutelayout....

**Comment by TimLariviere** [comment]
>Maybe AbsoluteLayout inherits from a lower class that has a BackgroundImage property?

@jamessdixon The link I provided lists all the properties of the control, inherited or not. (visible with the `inherited from ...` mentions)
There is no BackgroundImage property on AbsoluteLayout in Xamarin.Forms.
Maybe you're using a custom control that adds BackgroundImage to AbsoluteLayout?

Otherwise like @SergejDK said, we do provide `BackgroundImage` on `Page` (and to the controls that inherit from it, like `ContentPage`)

**Comment by jamessdixon** [comment]
I’ll go back and look at the old code
And yes, I’ll look at the View.Page 

Thanks!

**Comment by jamessdixon** [comment]
QQ
View.Page(backgroundImage="background00")  

backgroundImage is a string, but for me to use it in the shared project, it needs to be something like
View.Image(source=ImageSource.FromResource("background00"), aspect = Aspect.AspectFill) 
 
Do you see any way for me to override this implementation?

**Comment by TimLariviere** [comment]
@jamessdixon Unfortunately `Page` only supports string for BackgroundImage in Xamarin.Forms...
What you could do is add an image as the first child of AbsoluteLayout.

```fsharp
View.AbsoluteLayout(
    children=[
        View.Image(source=ImageSource.Resource("background00"), aspect=Aspect.AspectFill)
            .LayoutBounds(0.0,0.0,1.0,1.0).LayoutFlags(AbsoluteLayoutFlags.All),

        // Your content
    ]
)
```

If you need several of them, you can make a function for it
```fsharp
let makeAbsoluteLayoutWithBackground bgImageSource children =
    View.AbsoluteLayout(
        children=[
            yield View.Image(source=bgImageSource, aspect=Aspect.AspectFill)
                      .LayoutBounds(0.0,0.0,1.0,1.0).LayoutFlags(AbsoluteLayoutFlags.All),

            // Your content
            for element in children do
                yield element
        ]
)
```

**Comment by jamessdixon** [comment]
Thanks for the pointer
What I did was make the height really large so that it gets clipped to the entire page

    let getBackgroundImage =
        View.Image(source=ImageSource.FromResource("background00"), 
                    aspect = Aspect.AspectFill, heightRequest=1000.0)
