### ISSUE TITLE
Remove commandParameter attribute

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fsprojects/Fabulous#369]
The common `commandParameter` attribute in many elements such as buttons takes in `System.Object` but that value is never retrieved because `command` attribute is `unit -> unit`.

Please correct me if I am wrong, I think the property only made sense in classic view models where you can specify the command parameter in Xaml and have it bound the delegate of command but here there are no view models and a user doesn't need to keep track of the `commandParameter` since he/she already have all the data in their (elmish) data model

**Comment by TimLariviere** [comment]
@Zaid-Ajaj You're absolutely right. We need to remove this.
