### ISSUE TITLE
Fabulous.Oxyplot is referring to a nonexistent version of OxyPlot.Xamarin.Forms

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#370]
When installing [Fabulous.Oxyplot 0.33.2](https://www.nuget.org/packages/Fabulous.OxyPlot/0.33.2
), it is pointing to `OxyPlot.Xamarin.Forms (>= 1.1.0-unstable0013)` while the newest available version of Oxyplot.Xamarin.Forms is [1.1.0-unstable0011.](https://www.nuget.org/packages/OxyPlot.Xamarin.Forms/1.1.0-unstable0011)

This causes NuGet to try to fetch the unlisted `Oxyplot.Xamarin.Forms 2015.1.688-alpha` on iOS and fail to install because that version did not support .NET Standard or Xamarin.iOS. Android works though, for some reason.

I'm surprised no one has reported this yet, as all versions of Fabulous.Oxyplot reference this same version.

**Comment by TimLariviere** [comment]
Fabulous references the OxyPlot's MyGet package repo instead of NuGet.
`1.1.0-unstable0013` seems to never have been released on NuGet.
https://www.myget.org/feed/oxyplot/package/nuget/OxyPlot.Xamarin.Forms/1.1.0-unstable0013

**Comment by Happypig375** [comment]
Thanks. This is not obvious at all though.

**Comment by Happypig375** [comment]
Turns out that there's a pretty serious bug with Oxyplot 1.0.0: https://github.com/oxyplot/oxyplot-xamarin/issues/34
We might want to up the dependency again.
