### ISSUE TITLE
Crash on Android startup on VS2019

### ISSUE THREAD

**Issue by jimbobbennett** [fsprojects/Fabulous#372]
To Reproduce:

Using VS2019 Preview 4.4
Create a new app using the templates.
Build and run it on an Android device.

Boom!

03-31 22:10:23.384 D/Mono    (14150): Loading reference 2 of /storage/emulated/0/Android/data/com.companyname/files/.__override__/FSharp.Core.dll asmctx DEFAULT, looking for System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
mono_pe_file_map: Error opening file System.dll (3): No such file or directory03-31 22:10:23.384 W/Mono    (14150): The request to load the assembly System v4.0.0.0 was remapped to v2.0.5.0

03-31 22:10:23.386 D/Mono    (14150): Unloading image System.dll [0x90846400].
03-31 22:10:23.386 D/Mono    (14150): Image addref System[0x90b37a20] (asmctx DEFAULT) -> System.dll[0xac2b4200]: 5
03-31 22:10:23.386 D/Mono    (14150): Config attempting to parse: 'System.dll.config'.
03-31 22:10:23.387 D/Mono    (14150): Config attempting to parse: '/Users/builder/jenkins/workspace/xamarin-android-d16-0/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/etc/mono/assemblies/System/System.config'.
03-31 22:10:23.387 D/Mono    (14150): Assembly Ref addref FSharp.Core[0xa406bf80] -> System[0xa406cee0]: 5

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================03-31 22:10:23.894 E/mono-rt (14150): /proc/self/maps:

03-31 22:10:23.894 E/mono-rt (14150): 12c00000-12ce1000 rw-p 00000000 00:04 7796       /dev/ashmem/dalvik-main space (deleted)

=================================================================
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x909518b0):0x909518a0  50 4d e4 92 5c 4d e4 92 68 4d e4 92 74 4d e4 92  PM..\M..hM..tM..
0x909518b0  18 1d e7 91 1b 00 00 00 00 d5 05 a4 b8 0e df 92  ................
0x909518c0  b8 e8 2d ac 00 04 00 00 00 01 10 00 00 00 00 00  ..-.............
0x909518d0  00 00 00 00 00 40 e4 92 0c 40 e4 92 18 40 e4 92  .....@...@...@..

No native Android stacktrace (see debuggerd output).

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================03-31 22:10:23.894 E/mono-rt (14150): 12ce1000-12ee1000 rw-p 000e1000 00:04 7796       /dev/ashmem/dalvik-main space (deleted)

03-31 22:10:23.894 E/mono-rt (14150): 12ee1000-1ac00000 ---p 002e1000 00:04 7796       /dev/ashmem/dalvik-main space (deleted)
03-31 22:10:23.894 E/mono-rt (14150): 22c00000-22c01000 rw-p 00000000 00:04 7797       /dev/ashmem/dalvik-main space 1 (deleted)
03-31 22:10:23.894 E/mono-rt (14150): 22c01000-2ac00000 ---p 00001000 00:04 7797       /dev/ashmem/dalvik-main space 1 (deleted)
03-31 22:10:23.894 E/mono-rt (14150): 6f47c000-6f9e8000 rw-p 00000000 b3:16 128279     /data/dalvik-cache/arm/system@framework@boot.art
03-31 22:10:23.894 E/mono-rt (14150): 6f9e8000-6facb000 rw-p 00000000 b3:16 128280     /data/dalvik-cache/arm/system@framework@boot-core-libart.art
03-31 22:10:23.894 E/mono-rt (14150): 6facb000-6fae6000 rw-p 00000000 b3:16 128281     /data/dalvik-cache/arm/system@framework@boot-conscrypt.art
03-31 22:10:23.894 E/mono-rt (14150): 6fae6000-6fb09000 rw-p 00000000 b3:16 128282     /data/dalvik-cache/arm/system@framework@boot-okhttp.art
03-31 22:10:23.894 E/mono-rt (14150): 6fb09000-6fb0a000 rw-p 00000000 b3:16 128283     /data/dalvik-cache/arm/system@framework@boot-core-junit.art
03-31 22:10:23.894 E/mono-rt (14150): 6fb0a000-6fb2e000 rw-p 00000000 b3:16 128284     /data/dalvik-cache/arm/system@framework@boot-bouncycastle.art
03-31 22:10:23.894 E/mono-rt (14150): 6fb2e000-6fb4b000 rw-p 00000000 b3:16 128285     /data/dalvik-cache/arm/system@framework@boot-ext.art
03-31 22:10:23.894 E/mono-rt (14150): 6fb4b000-6ff83000 rw-p 00000000 b3:16 128286     /data/dalvik-cache/arm/system@framework@boot-framework.art
03-31 22:10:23.894 E/mono-rt (14150): 6ff83000-6ffbb000 rw-p 00000000 b3:16 128287     /data/dalvik-cache/arm/system@framework@boot-telephony-common.art
03-31 22:10:23.894 E/mono-rt (14150): 6ffbb000-6ffbf000 rw-p 00000000 b3:16 128288     /data/dalvik-cache/arm/system@framework@boot-voip-common.art
03-31 22:10:23.894 E/mono-rt (14150): 6ffbf000-6ffc9000 rw-p 00000000 b3:16 128289     /data/dalvik-cache/arm/system@framework@boot-ims-common.art
03-31 22:10:23.894 E/mono-rt (14150): 6ffc9000-6ffe1000 rw-p 00000000 b3:16 128290     /data/dalvik-cache/arm/system@framework@boot-apache-xml.art
03-31 22:10:23.894 E/mono-rt (14150): 6ffe1000-6fff2000 rw-p 00000000 b3:16 128291     /data/dalvik-cache/arm/system@framework@boot-org.apache.http.legacy.boot.art
03-31 22:10:23.894 E/mono-rt (14150): 6fff2000-6fff6000 rw-p 00000000 b3:16 128292     /data/dalvik-cache/arm/system@framework@boot-mediatek-common.art
03-31 22:10:23.894 E/mono-rt (14150): 6fff6000-6fffc000 rw-p 00000000 b3:16 128293     /data/dalvik-cache/arm/system@framework@boot-mediatek-framework.art
03-31 22:10:23.894 E/mono-rt (14150): 6fffc000-6fffd000 rw-p 00000000 b3:16 128294     /data/dalvik-cache/arm/system@framework@boot-mediatek-telephony-common.art
03-31 22:10:23.894 E/mono-rt (14150): 6fffd000-7056a000 r--p 00000000 b3:14 979        /system/framework/arm/boot.oat
03-31 22:10:23.894 E/mono-rt (14150): 7056a000-70859000 r-xp 0056d000 b3:14 979        /system/framework/arm/boot.oat
03-31 22:10:23.894 E/mono-rt (14150): 70859000-7085a000 r--p 0085c000 b3:14 979        /system/framework/arm/boot.oat
03-31 22:10:23.894 E/mono-rt (14150): 7085a000-7085b000 rw-p 0085d000 b3:14 979        /system/framework/arm/boot.oat
03-31 22:10:23.900 F/libc    (14150): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x909518b0 in tid 14150 (com.companyname)

**Comment by SergejDK** [comment]
Could only test with 2019 v. 5.0 because it is not possible to update to 4.4.
in 5.0 it works fine on my phone.
Maybe try it with version 5.0...

Which Android and Fabulous Version did you try it with?

**Comment by jimbobbennett** [comment]
Still happens with 5.

Using Fabulous 0.33.2, on a phone running Android 7. Works fine with 2017, and worked fine in the past with 2019.

**Comment by jimbobbennett** [comment]
Tried with 5.0 - same thing.

Fabulous 0.33.2, so the latest version as of now. Using a phone running Android 7. Works fine with VS2017, not with VS2019. Haven't tried VS for Mac yet.

**Comment by TimLariviere** [comment]
The error message refers to FSharp.Core. Which version do you use?
Maybe it has something to do with F# 4.6?

**Comment by jimbobbennett** [comment]
Tried F# 4.5.2 and 4.6, same thing.

Works fine on an emulator running Oreo, not on my Nougat device.

**Comment by jimbobbennett** [comment]
Gah - more 2019 woes. It won't let me edit the file to test the live update during debugging!

**Comment by TimLariviere** [comment]
> Gah - more 2019 woes. It won't let me edit the file to test the live update during debugging! Will try this out some more and raise a new issue...

@jimbobbennett Might be the `Edit and Continue` option under `Tools > Options > Debugging` is off
I'll try to install the Android SDK on a Windows today to check if I can reproduce.

**Comment by Cheesebaron** [comment]
Might be related to: https://github.com/xamarin/xamarin-android/issues/2920

**Comment by jimbobbennett** [comment]
@TimLariviere - Edit and continue was turned **ON**. I had to turn it **OFF** so that I could edit files!

PR raised for the docs for this.

**Comment by jimbobbennett** [comment]
Also closing this issue, as it is definitely a Xamarin issue. Raised it internally.

**Comment by hasanoruc** [comment]
https://github.com/xamarin/xamarin-android/issues/2920#issuecomment-496015620_
