### ISSUE TITLE
Don't require global FAKE

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/Fabulous#381]
Currently, a global FAKE install is required when building this repo. That can be avoided by having a local (and properly versioned) FAKE be automatically restored using a top-level `.proj` file. See e.g. [MangelMaxime/fulma-demo](https://github.com/MangelMaxime/fulma-demo/) or [cmeeren/fable-elmish-electron-material-ui-demo](https://github.com/cmeeren/fable-elmish-electron-material-ui-demo) (the relevant files in both repos are `build.proj`, `fake.cmd`, `fake.sh`, and the build group in `paket.dependencies`).

Would that be interesting for this repo?

**Comment by TimLariviere** [comment]
@cmeeren Yes, it's definitely interesting!
I wondered if there was a way to do exactly this. The documentation didn't have any satisfying way.

**Comment by dsyme** [comment]
I actually prefer [this technique](https://github.com/fsprojects/FsLexYacc/blob/master/build.cmd), though I suppose a `build.proj` is not too bad.

**Comment by cmeeren** [comment]
> I actually prefer [this technique](https://github.com/fsprojects/FsLexYacc/blob/master/build.cmd)

Does that technique allow specifying the versions of e.g. all Fake packages, as in the [FakeBuild group here](https://github.com/cmeeren/fable-elmish-electron-material-ui-demo/blob/f79420feddcd24b24d375de7a36dce4cccb0efe2/paket.dependencies)?

I might be wrong, but it seems like the technique you link to is based on installing tools via CLI and is limited to tools, whereas using `build.proj` allows to do manage everything - both tools and packages - using Paket. Is this correcft?

**Comment by dsyme** [comment]
The FAKE build script specifies that directly, e.g. https://github.com/fsprojects/FsLexYacc/blob/master/build.fsx#L1, with corresponding `build.fsx.lock`.

**Comment by dsyme** [comment]
I dunno really, there's not much difference. I suppose it lets you isolate the use of Paket, e.g. if you only want to use paket for this bit.
