### ISSUE TITLE
BuildTools target fails with error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/Fabulous#382]
Cloned and tried to build according to [DEVGUIDE.md](https://github.com/fsprojects/Fabulous/blob/e1766f312200d33a8b80afa44d7e127ae247c6cf/DEVGUIDE.md), but when running `.\build`, the `BuildTools` target fails:

```
Starting task 'MSBuild': C:\Users\Christer\Source\Repos\Fabulous\tools\Generator\Generator.fsproj
> "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /version /nologo (In: false, Out: true, Err: true)
C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe "C:\Users\Christer\Source\Repos\Fabulous\tools\Generator\Generator.fsproj" /t:Restore /m /nodeReuse:False /p:RestorePackages=False /p:OutputPath=C:%5CUsers%5CChrister%5CSource%5CRepos%5CFabulous%5Cbuild_output%5Ctools%5CGenerator%5C /p:Configuration=Release "/logger:BinaryLogger,C:\Users\Christer\.nuget\packages\msbuild.structuredlogger\2.0.64\lib\net46\StructuredLogger.dll;C:\Users\Christer\AppData\Local\Temp\tmp26FF.tmp.binlog"
C:\Users\Christer\Source\Repos\Fabulous> "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "C:\Users\Christer\Source\Repos\Fabulous\tools\Generator\Generator.fsproj" /t:Restore /m /nodeReuse:False /p:RestorePackages=False /p:OutputPath=C:%5CUsers%5CChrister%5CSource%5CRepos%5CFabulous%5Cbuild_output%5Ctools%5CGenerator%5C /p:Configuration=Release "/logger:BinaryLogger,C:\Users\Christer\.nuget\packages\msbuild.structuredlogger\2.0.64\lib\net46\StructuredLogger.dll;C:\Users\Christer\AppData\Local\Temp\tmp26FF.tmp.binlog" (In: false, Out: false, Err: false)
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 06.04.2019 21.33.02.
     1>Project "C:\Users\Christer\Source\Repos\Fabulous\tools\Generator\Generator.fsproj" on node 1 (Restore target(s)).
     1>C:\Users\Christer\Source\Repos\Fabulous\tools\Generator\Generator.fsproj(2,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
     1>Done Building Project "C:\Users\Christer\Source\Repos\Fabulous\tools\Generator\Generator.fsproj" (Restore target(s)) -- FAILED.
```

**Comment by SergejDK** [comment]
It could be that you need a newer version of MS Build.
I use 15.0 which is included in vs 2017.

Maybe this helps...

**Comment by cmeeren** [comment]
I'm using VS2019, so I expect that is fine...

**Comment by cmeeren** [comment]
Builds fine on my laptop, where I have both VS2017 and VS2019 (there are likely other environment-specific differences I don't know about). On my desktop computer, where I experienced the build error, I only have VS2019. Could that be the problem? Seems weird, but you never know...

**Comment by SergejDK** [comment]
2019 has still some bugs so it is possible that it does not set env-variables or does not install something that is default in 2017. 

Maybe check which buildtools are running on your notebook and desktop. And take a look at the global env variables on Windows. Possible that something is not set?

**Comment by TimLariviere** [comment]
For some reasons, FAKE with VS 2019 prefers to use `c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe` (which doesn't support the new fsproj format) instead of `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe`

I will change the build script a bit to use the correct compiler (`msbuild` is no longer need for the `BuildTools` task)
