### ISSUE TITLE
Fix slowdowns when navigating

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/Fabulous#383]
Continued from https://github.com/fsprojects/Fabulous/issues/373#issuecomment-480486017

I just tried the `AllControls` sample on my Android device (release mode) and WPF on my beefy desktop computer. There are fairly noticeable slowdowns when navigating on Android, and less so (sub-second, but still noticeable) on WPF. After a cold start on Android, navigating to TabbedPage 3 takes around 2 seconds. I have a hard time imagining clients/employers (or users) accepting that, regardless of maintenance/agility benefits of an Elmish architecture.

* What is the root cause of the navigation slowdown, particularly on Android?
* Which factors influence it? (Devices? Model size? etc.)
* Can anything be done about it? What?

**Comment by cmeeren** [comment]
I tried profiling using AllControls.WPF in VS. According to "Application Timeline", the majority of the time is spent in Application Code (as opposed to rendering). Unfortunately I couldn't get "Instrumentation" to work, so I can't see which parts of Fabulous are hotspots.

**Comment by TimLariviere** [comment]
@cmeeren #241 was open for this problem as well.
I suspect Fabulous spends to much time browsing the whole UI tree to determine whether or not create new controls.
This is especially bad for low end devices.

I think some simple fixes should give big boost in the first time.

We have yet to profile it.

**Comment by cmeeren** [comment]
> I think some simple fixes should give big boost in the first time.

Would be great if there was some low-hanging fruit.

For inspiration, check out [the React docs on Reconciliation](https://reactjs.org/docs/reconciliation.html)

**Comment by cmeeren** [comment]
Regarding profiling, if you need R# you can probably apply for a [free OS license](https://www.jetbrains.com/buy/opensource/).

**Comment by cmeeren** [comment]
> I suspect Fabulous spends to much time browsing the whole UI tree to determine whether or not create new controls.

I have taken a (very) brief look at some of the updating code in `ViewConverters.fs`. I might have overlooked something, or not looked carefully enough, but initially it seems to me that Fabulous follows the React heuristics I linked to: It re-uses the control if it's the same type, or skips any reconciliation and reconstructs the subtree if it's another type.

Does this match your understanding of Fabulous's reconciliation? Are there any places you know or suspect there might be fairly low-hanging performance improvements?

**Comment by cmeeren** [comment]
Just want to say that I'd like to help if there's anything I can do. I'm not here to just complain. 😊 But as I explained in the comment above, I can't immediately see something obviously wrong (which would be surprising, given the Fabulous authors).

Do let me know if there's anything I can do, places I can look, things I can look for, etc. I really want to use Fabulous but need better performance, and can't figure out how to scratch this itch. 😛

**Comment by dsyme** [comment]
Note that the AllControls app has not been performance optimized, i.e. there are relatively few `dependsOn` calls which are pretty much necessary to get good performance for incremental view update.

A more general question is how we might best guide the user as to the best place to insert `dependsOn` calls.   

For example, could there be a mode (or Debug mode) that reports when large parts of the View tree re being re-created (as objects) but are in fact identical (and perhaps even relate this to exact source line locations or stacks where the uppermost invariant ViewElements were created?)

Note also I don't think `dependsOn` is the only way to avoid recomputation of view sub-trees under invariant sub-models., it's just one relatively simple way.  I'd like to hear of other suggestions and hacks that do this.

**Comment by cmeeren** [comment]
> Note that the AllControls app has not been performance optimized, i.e. there are relatively few `dependsOn` calls which are pretty much necessary to get good performance for incremental view update.

Does that explain the poor performance when navigating, but much better performance at the page after navigation?

> A more general question is how we might best guide the user as to the best place to insert `dependsOn` calls.
> 
> For example, could there be a mode (or Debug mode) that reports when large parts of the View tree re being re-created (as objects) but are in fact identical (and perhaps even relate this to exact source line locations or stacks where the uppermost invariant ViewElements were created?)

I like the idea. The question is how to set the thresholds so the warnings are real and not spammy.

Also, I think clear documentation can get you far on its own. :)

> Note also I don't think `dependsOn` is the only way to avoid recomputation of view sub-trees under invariant sub-models., it's just one relatively simple way. I'd like to hear of other suggestions and hacks that do this.

Some kind of `Key` property might be good for collections. It would allow you to do smarter differential update of collections. AFAIK it's an important optimization in React (they throw warnings at you if you don't supply it in collections). Not sure how easy it is though, given that you can add any attribute to any HTML DOM element, but here we are working with objects with a limited set of properties.

**Comment by aspnetde** [comment]
Just leaving this here: I've built a quite simple application which consists of basically one navigation page and one child page. Whenever there's another child page pushed from that, I can literally watch it freeze for maybe half a second. For no obvious reason, as I run only once through the app's message loop to trigger the navigation. I took `Program.withConsoleTrace` out of the equation, but with no noticeable effect.

That's on the iOS Simulator right now in DEBUG mode. Will check again as soon as I can get it deployed to some hardware device.

We even have a word for that in German: _Gedenksekunde_ ;-).

**Comment by humhei** [comment]
Does **reflection**  slow down the performance?
For example, 
1 model containers 10 models, 
1 model container 10 properties,

Then every model comparision will compare 100 properties from reflection

It's a bit slow when get property from reflection first time,
So we will get a slowdowns when we navigate to a new page

May be we should done the comparision of models by pre-compiling

Some related work may be helpful: 
https://github.com/MoiraeSoftware/myriad
https://github.com/Fody/

**Comment by TimLariviere** [comment]
>Does reflection slow down the performance?

Yes, reflection can slow down performance.
But you will only notice performance issue if you make intensive use of it.
Individually, it's not that bad.

That's why we tried to limit reflection to a minimum in Fabulous.XamarinForms.

The line you're referencing is one of the few (if not the only one) to use reflection.
So I don't think it's the source of the slowdowns...

Instead, I think we're a bit too heavy on the memory.
Every time I noticed slowdowns, a corresponding output in the console indicated the GC triggered.
GC pauses the app for several milliseconds, enough to make it noticeable sometimes.

So we either don't clean up enough memory, or we're instantiating too many small objects that clutter up the memory forcing the garbage collector to pass.

This seems to fit because iOS is not plagued by those slowdowns, while Android takes it fully.
On iOS, it's fully native no GC (only reference counting) - on Android, there's 2 of them (.NET GC and JVM GC)

**Comment by davidglassborow** [comment]
As an aside, if/when we have to use reflection, its always worth considering if we can make use of Delegate.CreateDelegate for better performance - see [Jon Skeet's article](https://codeblog.jonskeet.uk/2008/08/09/making-reflection-fly-and-exploring-delegates/)

**Comment by TimLariviere** [comment]
Slowdowns were a result of Fabulous doing too many allocations on the heap, and GC triggering.
v2 fixes that
