### ISSUE TITLE
ImageButton not working

### ISSUE THREAD

**Issue by JordanMarr** [fsprojects/Fabulous#388]
The ImageButton does not show an image, and I cannot get it to fire a clicked event.
Ex:

```
View.ImageButton(
    source = "Images/pieces_black/king.png",
    aspect=Aspect.AspectFit,
    command = (fun () -> dispatch (PickCell cell))
)
```

The same image source works with a regular "View.Image".  The image is stored as "Content", not as "Resource" if that matters (it didn't for the "View.Image").
Neither "command" nor "clicked" worked.

I ended up doing a workaround by using a combination of a "View.Image" and a "View.Button".

Full code here:
https://github.com/JordanMarr/FsharpChess/blob/master/Chess.FabUI/Chess.FabUI.fs

**Comment by TimLariviere** [comment]
@JordanMarr Thanks for reporting it!
I made a PR with a fix for `Command`.

For the Source, I tested it on iOS/Android. It's working as expected.
Maybe there's a special constraint for WPF?
I will check that when I have some more time.

**Comment by JordanMarr** [comment]
I just found this: ://github.com/xamarin/Xamarin.Forms/issues/4991
Apparently there is no such thing as an "ImageButton" in WPF.  

This is how I would typically implement this in WPF:
```
<Button Background="Transparent">
    <Image Source="/Images/pieces_black/king.png" />
</Button>
```

So it seems that the easiest solution would be to implement the WPF `View.ImageButton` as a button with a nested image and transparent background.  

As a bonus, it would be nice if it was possible to set the `content` or maybe `template` of a `View.Button`.  This would be very similar to what is possible in WPF (although I don't know if iOS/Android would jive with that...  maybe that is why they came up with the "ImageButton" in the first place).

**Comment by TimLariviere** [comment]
>So it seems that the easiest solution would be to implement the WPF View.ImageButton as a button with a nested image and transparent background.

The purpose of Fabulous.DynamicViews is to provide an wrapper around Xamarin.Forms for MVU style app, and not really to provide what Xamarin.Forms itself doesn't want to do/didn't do.
Especially when such thing is already underway on the Xamarin.Forms repo.

In the meantime, you can check your platform at runtime and choose which control to use `View.ImageButton` vs your workaround.
```fsharp
let createImageButton source command =
    match Xamarin.Forms.Device.RuntimePlatform with
    | platform when platform = Xamarin.Forms.Device.WPF -> yourWorkaround source command
    | _ -> View.ImageButton(source=source, command=command)
```

>As a bonus, it would be nice if it was possible to set the content or maybe template of a View.Button. This would be very similar to what is possible in WPF (although I don't know if iOS/Android would jive with that... maybe that is why they came up with the "ImageButton" in the first place).

Unfortunately Xamarin.Forms doesn't support putting content inside a button.
This is specific to WPF and UWP, no other platform can do that.

**Comment by JordanMarr** [comment]
It sounds like this should work itself out if/when Xamarin implements an ImageButton for WPF.

In the meantime, I have found a nice workaround (perhaps even better than the original attempt):

```
View.Image(
    backgroundColor=color,
    source = imageSource,
    gestureRecognizers = [View.TapGestureRecognizer(command=(fun () -> dispatch ImageClicked))]
)
```

Thanks!
