### ISSUE TITLE
Live Update - System.Net.WebException

### ISSUE THREAD

**Issue by JordanMarr** [fsprojects/Fabulous#391]
When I try to use LiveUpdate in [my app](https://github.com/JordanMarr/FsharpChess), I get a "System.Net.WebException" (below).

I am using Visual Studio 2019 Professional.

> fscd: CHANGE DETECTED (Renamed), COMPILING....
> fscd: COMPILED C:\_git\FsharpChess\Chess.FabUI\obj\Debug\netstandard2.0\Chess.FabUI.AssemblyInfo.fs
> fscd: GOT PortaCode for C:\_git\FsharpChess\Chess.FabUI\obj\Debug\netstandard2.0\Chess.FabUI.AssemblyInfo.fs
> fscd: COMPILED C:\_git\FsharpChess\Chess.FabUI\Chess.FabUI.fs
> fscd: GOT PortaCode for C:\_git\FsharpChess\Chess.FabUI\Chess.FabUI.fs
> fscd: GOT JSON, length = 477358
> fscd: SENDING TO WEBHOOK...
> fscd: ERROR SENDING TO WEBHOOK: "System.Net.WebException: No connection could be made because the target machine actively refused it No connection could be made because the target machine actively refused it ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
>    at System.Net.HttpWebRequest.SendRequest()
>    at System.Net.HttpWebRequest.GetResponse()
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.GetResponse()
>    at System.Net.WebClient.GetWebResponse(WebRequest request)
>    at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
>    at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer)
>    at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
>    at System.Net.WebClient.UploadString(Uri address, String method, String data)
>    at FSharp.Compiler.PortaCode.ProcessCommandLine.sendToWebHook@218.Invoke(String hook, FSharpList`1 fileContents) in C:\projects\elmish-xamarinforms\paket-files\neutral\fsprojects\FSharp.Compiler.PortaCode\src\ProcessCommandLine.fs:line 222"
> fscd: CHANGE DETECTED (Changed), COMPILING....
> fscd: COMPILED C:\_git\FsharpChess\Chess.FabUI\obj\Debug\netstandard2.0\Chess.FabUI.AssemblyInfo.fs
> fscd: GOT PortaCode for C:\_git\FsharpChess\Chess.FabUI\obj\Debug\netstandard2.0\Chess.FabUI.AssemblyInfo.fs
> fscd: COMPILED C:\_git\FsharpChess\Chess.FabUI\Chess.FabUI.fs
> fscd: GOT PortaCode for C:\_git\FsharpChess\Chess.FabUI\Chess.FabUI.fs
> fscd: GOT JSON, length = 477358
> fscd: SENDING TO WEBHOOK...
> fscd: ERROR SENDING TO WEBHOOK: "System.Net.WebException: No connection could be made because the target machine actively refused it No connection could be made because the target machine actively refused it ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
>    at System.Net.HttpWebRequest.SendRequest()
>    at System.Net.HttpWebRequest.GetResponse()
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.GetResponse()
>    at System.Net.WebClient.GetWebResponse(WebRequest request)
>    at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
>    at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer)
>    at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
>    at System.Net.WebClient.UploadString(Uri address, String method, String data)
>    at FSharp.Compiler.PortaCode.ProcessCommandLine.sendToWebHook@218.Invoke(String hook, FSharpList`1 fileContents) in C:\projects\elmish-xamarinforms\paket-files\neutral\fsprojects\FSharp.Compiler.PortaCode\src\ProcessCommandLine.fs:line 222"
> 
> 
> 
> 
> 
> 
> 
>

**Comment by jimbobbennett** [comment]
Is this on Android? Did you forward the port?

**Comment by JordanMarr** [comment]
Jim, your reply prompted me to re-read the instructions, and now it seems clear to me that this is actually not a bug.  I was debugging the WPF project, not the Android or iOS version.  

Are there any plans to extend live update to work for WPF?

**Comment by dsyme** [comment]
> Are there any plans to extend live update to work for WPF?

Please contribute? It may be close to working already just needs testing and the correct instructions...

**Comment by JordanMarr** [comment]
How exciting!  I am happy to help.
Everything builds on my machine, so that's a good start.  👍

**Comment by JordanMarr** [comment]
It works!  

The HttpServer was failing at `listener.Start ()` due to an "Access Denied" error.  The fix was simply to start Visual Studio "as administrator".  

[Updated tools.md](https://github.com/fsprojects/Fabulous/pull/395).
