### ISSUE TITLE
Width of source view should respect screen size

### ISSUE THREAD

**Issue by gdennie** [fsprojects/Fabulous#399]
Presently, the source code view does not respect screen size. This is a nuisance that appears to be alleviated by disabling the `nav` element's `.container-lg` style `max-width` setting from the browser's DOM inspector (`/html/body/div[4]/div/main/div[1]/nav`). Consequently, why is it enabled in the first place?

**Comment by davidglassborow** [comment]
Hi @gdennie, which source code view are you talking about ?  Do you mean the one source code view within Github ?

**Comment by gdennie** [comment]
Hi David,

the following demonstrates the problem at lines 147, 154, and 157 for example. However, it is a recurring issue:
 
https://github.com/fsprojects/Fabulous/blob/master/samples/AllControls/AllControls/AllControls.fs

**Comment by davidglassborow** [comment]
I believe this is a limitation of how Github works, rather than anything that is special to this particular repository, sorry.

**Comment by gdennie** [comment]
It is their default template for presenting source code that unreasonably restricts the width for some reason. As a result, it does not properly utilize available screen real estate. Disabling the aforementioned style's `max_width` property resolves the issue though resulting in a width that both maximizes to the screen usage and display even more text when the font size is further reduced, as one would expect.

**Comment by davidglassborow** [comment]
Maybe its worth raising to Github themselves ? It's not something that can be resolved in this repository.

**Comment by gdennie** [comment]
I thought I was doing that ... woops. :)

**Comment by davidglassborow** [comment]
No worries, would you mind shutting the issue please ?   Thanks.
