### ISSUE TITLE
Loading Page

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#400]
Hello, are there any recommended steps for implementing a loading page before the rest of the application is loaded? It would be awful to watch a blank white page while loading.

**Comment by SergejDK** [comment]
As far as I know Xamarin.Forms does not support `Splashscreens` so you need to do it on each platform.
Therefore I think there is nothing special on Fabulous side.
Maybe this will help you: [https://www.c-sharpcorner.com/article/creating-a-splash-screen-in-xamarin-forms/](https://www.c-sharpcorner.com/article/creating-a-splash-screen-in-xamarin-forms/)
