### ISSUE TITLE
Proposal: A more robust way to unit test views

### ISSUE THREAD

**Issue by aspnetde** [fsprojects/Fabulous#402]
I took at look at the test [examples](https://github.com/fsprojects/Fabulous/blob/master/samples/CounterApp/CounterApp.Tests/Tests.fs#L80) for views and gave it a try. While the `*Viewer` types are very helpful and the overall mechanism works I think it's kind of an anti-pattern on how it is demonstrated here (and in the docs).

Obviously you _can_ build your tests that way, but I don't think you should. Especially not when you're dealing with more complex view hierarchies, and when you're beginning to build your UI which may at that time be subject of change quite often. 

Because **every time the hierarchy changes your tests would break** and require you to update them. Which is a tedious process as you need to scan your hierarchy and replicate it in your tests. So you not only end up with a lot of boilerplate code but very fragile boilerplate code.

### Example

```fs
let loginPage() = 
    View.ContentPage(
        content = View.ScrollView(
            content = View.StackLayout(
                padding = 30.0,
                children = [
                    View.Frame(
                        verticalOptions = LayoutOptions.CenterAndExpand,
                        content = View.StackLayout(children = [
                            View.Entry(
                                placeholder = "User name",
                                isEnabled = (not model.IsBusy),
                                textChanged = (fun args -> (dispatch (LoginUserNameChanged args.NewTextValue))))
                            View.Entry(
                                placeholder = "Password", 
                                isPassword = true,
                                isEnabled = (not model.IsBusy),
                                textChanged = (fun args -> (dispatch (LoginPasswordChanged args.NewTextValue))))
                            View.Button(
                                automationId = "SignInButton",
                                text = "Sign in", 
                                heightRequest = 30.0,
                                isVisible = (not model.IsBusy),
                                command = (fun () -> dispatch LoginStarted),
                                canExecute = model.Login.IsCredentialsProvided)
                            View.ActivityIndicator(
                                isRunning = true,
                                heightRequest = 30.0,
                                isVisible = model.IsBusy)])
                    )
                ]
            )
        )
    )
```

I have that login form and want to make sure the sign in button is enabled only when the `IsCredentialsProvided` property is set to `true`. This is crucial to the whole thing and worth testing (from my point of view).

A test would now look like:

```fs
[<Theory>]
[<InlineData(true)>]
[<InlineData(false)>]
let ``The Sign In Button is only enabled when the Credentials are provided`` credentialsProvided =
    let model = initialModel()
    let model = { model with Login = { model.Login with IsCredentialsProvided = credentialsProvided } }
    
    let view = (App.view model ignore)
    let contentPage = ContentPageViewer(view)
    let scrollView = ScrollViewViewer(contentPage.Content)
    let stackLayout = StackLayoutViewer(scrollView.Content)
    let frame = FrameViewer(stackLayout.Children.[0])
    let stackLayout = StackLayoutViewer(frame.Content)
    let button = ButtonViewer(stackLayout.Children.[2])
    
    button.CanExecute |> should equal credentialsProvided
```

This is not a new problem, though. UI test frameworks seem to agree on unique identifiers within the view hierarchy which they can use to "pick" an element effortlessly. [Xamarin.Forms has those as well](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.element.automationid?view=xamarin-forms) and is turns out they are even part of the Fabulous "bindings".

I wrote a small helper function that covers the most common scenarios right now (Content, Children, and Pages) and is able to find a given element by its `AutomationId` in the hierarchy:

```fs
/// Looks for an view element with the given Automation ID in the view hierarchy.
/// This function is not optimized for efficiency and may execute slowly.
/// Which shouldn't be noticable in pure test scenarios, though.
let rec tryFindViewElement automationId (element:ViewElement) =
    let elementAutomationId = element.TryGetAttributeKeyed(ViewAttributes.AutomationIdAttribKey)
    if elementAutomationId.IsSome && elementAutomationId.Value = automationId then
        Some(element)
    else
        let childElements = ResizeArray<ViewElement>()
                        
        let content = element.TryGetAttributeKeyed(ViewAttributes.ContentAttribKey)
        if content.IsSome then
            childElements.Add content.Value
        else                  
            let pages = element.TryGetAttributeKeyed(ViewAttributes.PagesAttribKey)
            if (pages.IsSome) then
                childElements.AddRange pages.Value
            else                    
                let children = element.TryGetAttributeKeyed(ViewAttributes.ChildrenAttribKey)
                if (children.IsSome) then
                    childElements.AddRange children.Value
           
        let childElementResult =
            childElements
            |> Seq.map (fun e -> e |> tryFindViewElement automationId)
            |> Seq.filter (fun e -> e.IsSome)
            |> Seq.tryHead
            
        match childElementResult with
        | Some result -> result
        | None -> None
```

My test is now much simpler and doesn't rely on the concrete structure of the form as long as the button still is to be found somewhere:

```fs
[<Theory>]
[<InlineData(true)>]
[<InlineData(false)>]
let ``The Sign In Button is only enabled when the Credentials are provided`` credentialsProvided =
    let model = initialModel()
    let model = { model with Login = { model.Login with IsCredentialsProvided = credentialsProvided } }
    
    let view = (App.view model ignore)
    let button = view |> tryFindViewElement "SignInButton"
    button.IsSome |> should be True
    
    let button = ButtonViewer(button.Value)
    button.CanExecute |> should equal credentialsProvided
```

I'm pretty sure `tryFindViewElement` can be optimized in certain ways (bear with me, I'm a C# developer by day :-)). But maybe someone may find it helpful anyway.

**Comment by aspnetde** [comment]
Ironically `AutomationId` seems [broken](https://github.com/fsprojects/Fabulous/issues/403) right now. But `ClassId` works, too.

**Comment by TimLariviere** [comment]
@aspnetde I agree with you.
To be honest, the Viewer API was something I was able to quickly put together [to provide an easier way to unit test UI](https://github.com/fsprojects/Fabulous/issues/204) (with some docs and samples -- even if not really applicable to real world cases).

So any improvement is more than welcome :)

Your `tryFindViewElement` seems like a good helper we can integrate in Fabulous.
It's more akin to what I'm used to when testing C# Xamarin apps (though I mostly do integration testing with App Center)

The samples will also benefit from being redone I think, to be more real world-like.

**Comment by aspnetde** [comment]
@TimLariviere 

> To be honest, the Viewer API was something I was able to quickly put together to provide an easier way to unit test UI (with some docs and samples -- even if not really applicable to real world cases).

Actually it's way more than good enough for now I think. Working with it was straight-forward and it provides all information and data that's needed for testing I think.

> Your tryFindViewElement seems like a good helper we can integrate in Fabulous.

Feel free to do so :-). (I don't know where to put it, otherwise I would prepare a PR myself.)
