### ISSUE TITLE
Rendering of List View Header and Footer 

### ISSUE THREAD

**Issue by aspnetde** [fsprojects/Fabulous#407]
Reproduction: Set a View Element as header for a list view:

```fs
let view (model: Model) _ =
    View.ContentPage(
      content =
        View.ListView(
            model.Items |> List.map (fun item -> View.Label(text = item)),
            header = View.Label(text = "I am a header.")
        )
    )
```

This results in:

![image](https://user-images.githubusercontent.com/1322584/57855021-f8fe2000-77e9-11e9-949a-1f52d22a38ee.png)

So it seems there's a `ToString()` involved somewhere ... Sample: [FabulousListViewHeaderBug.zip](https://github.com/fsprojects/Fabulous/files/3187099/FabulousListViewHeaderBug.zip)

- Fabulous 0.33.2
- iOS + Android

**Comment by aspnetde** [comment]
Checked the footer – same problem. So it affects header and footer then.

**Comment by aspnetde** [comment]
Okay, I figured it out. First: The value of those attributes [can be](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/customizing-list-appearance#headers-and-footers) a string, an object, or a complex view. I don't know about the internals, but passing a `ViewElement` doesn't work. 

What does work, is to call the `Create()` method of a `ViewElement` and pass the resulting object. Like:

```fs
let view (model: Model) _ =
    View.ContentPage(
      content =
        View.ListView(
            model.Items |> List.map (fun item -> View.Label(text = item)),
            header = View.Label(text = "I am a header.").Create()
        )
    )
```

So it's not a bug, but at least some kind of undocumented behavior. I also don't know if calling the `Create()` method is something that should ever be done by a user of Fabulous?

**Comment by SergejDK** [comment]
As far as I know there is a need to call Create(). 
We need to change the "makeheader"(don't know if it is called like this) of the listview so that ViewElements are allowed.

**Comment by TimLariviere** [comment]
I did see mention of this issue a few times on Slack.
We are indeed doing nothing to the value passed to Header/Footer and thus Xamarin.Forms is clueless about ViewElement and calls its `ToString()` method

I added a converter which will first call `ViewElement.Create()` before setting the properties Header/Footer

**Comment by aspnetde** [comment]
Makes sense! I'm closing this issue as the "fix" is coming and the workaround is available anyway.
