### ISSUE TITLE
List View: Deselect the selected item

### ISSUE THREAD

**Issue by aspnetde** [fsprojects/Fabulous#409]
Scenario:

- Given is a list of items, rendered in a List View
- Item x is being selected and triggers to open a another page
- That page is being closed
- Item x is still selected and can't be selected again

Sample:

```fs
module App =
    type Model =
      { Items: string list
        SelectedItem: string option }

    type Msg = SelectItem of index: int

    let initModel =
        { Items = [ "One"; "Two"; "Three"; "Four"; "Five" ]
          SelectedItem = None }

    let init() = initModel, Cmd.none

    let update (msg: Msg) model =
        match msg with
        | SelectItem index ->
            let item = model.Items |> List.tryItem index
            let model = { model with SelectedItem = item }
            model, Cmd.none
   
    let view (model: Model) dispatch =
        View.NavigationPage(pages = [
            yield View.ContentPage(
              content =
                View.ListView(
                    model.Items |> List.map (fun item -> View.Label(text = item)),
                    itemSelected = (fun index -> dispatch (SelectItem index.Value)),
                    selected
                )
            )
            
            if model.SelectedItem.IsSome then
                yield View.ContentPage(
                  title = model.SelectedItem.Value,
                  content =
                    View.Label(text = model.SelectedItem.Value)
                )
        ])

    let program = Program.mkProgram init update view
```

The reason for that is simple: The List View Control holds the information about the selected item, which must be reset. I'm not sure this is intended by design or it's just a bug that people got used to work around, but the behavior exists in XF for at least 3 years and it doesn't seem to be changed anytime soon AFAIK. See [this thread](https://forums.xamarin.com/discussion/128656/same-listview-item-not-getting-selected-after-pressing-back) for example.

So the final questions is: How do we implement that common workaround of setting `List.SelectedItem = null` and then ignoring the event being fired with that null value?

Edit: `itemTapped` works as expected, so there is that.

**Comment by SergejDK** [comment]
I think you could use `ref` here but you could work it out like:

```fsharp
module App =
    type Model =
      { Items: string list
        SelectedItem: string option 
        SItem: int option } // SItem for the index of selected item

    type Msg = 
        | SelectItem of index: int
        | Deselect

    let initModel =
        { Items = [ "One"; "Two"; "Three"; "Four"; "Five" ]
          SelectedItem = None 
          SItem = None
          }

    let init() = initModel, Cmd.none

    let update (msg: Msg) model =
        match msg with
        | SelectItem index ->
            let item = model.Items |> List.tryItem index
            let model = { model with SelectedItem = item; SItem = Some index }
            model, Cmd.none
        | Deselect ->
            {model with SItem = None; SelectedItem = None }, Cmd.none
   
    let view (model: Model) dispatch =
        View.NavigationPage(pages = [
            yield View.ContentPage(
              content =
                View.ListView(
                    model.Items |> List.map (fun item -> View.Label(text = item)),
                    itemSelected = (fun index -> 
                        match model.SelectedItem, model.SItem with
                        | None, None -> dispatch (SelectItem index.Value)
                        | _, _ -> ()
                        ),
                    selectedItem = model.SItem // need int option
                )
            )
            
            if model.SelectedItem.IsSome then
                yield View.ContentPage(
                  title = model.SelectedItem.Value,
                  content =
                    View.Label(text = model.SelectedItem.Value)
                )
        ], popped = (fun _ -> dispatch Deselect)) // call to move back where everything is set back

    let program = Program.mkProgram init update view
`

**Comment by aspnetde** [comment]
Thanks. I think `SelectItem` should return a `Cmd.ofMsg Deselect` immediately in most cases (if one doesn't want the item to stay selected).

(Personally I moved on and used some other way, as selecting is [broking](https://github.com/xamarin/Xamarin.Forms/issues/5920) right now anyway when using the Material Design visual.)

By the way: I would find it quite useful to find samples like this one or those two [[1](https://github.com/fsprojects/Fabulous/issues/402#issue-442698802), [2](https://gitter.im/fsprojects/Fabulous?at=5cde87fb879f4478c793c210)] in the documentation. What do you think @TimLariviere?

**Comment by SergejDK** [comment]
Surely you could send Deselect insteadly. Shouldn't be a problem here.

After all a XF problem where we can't do anything so we wait...

**Comment by TimLariviere** [comment]
In this particular case, I think using `ItemTapped` combined with `ListView.SelectionMode = SelectionMode.None` is better than using selection.

>So the final questions is: How do we implement that common workaround of setting List.SelectedItem = null and then ignoring the event being fired with that null value?

#304 suggests we change the way events work today, and don't trigger any *Changed events when setting a value programmatically.
This has several advantages including this one.

>By the way: I would find it quite useful to find samples like this one or those two [1, 2] in the documentation.

Good idea! Useful samples are always welcome :)
