### ISSUE TITLE
Support for Xamarin.Forms Visual

### ISSUE THREAD

**Issue by aspnetde** [fsprojects/Fabulous#411]
I just upgraded to Fabulous 0.34.0 to check if the new Visual API is now supported which had been introduced with Xamarin.Forms 3.6 ([read more](https://devblogs.microsoft.com/xamarin/beautiful-material-design-android-ios/)).

While the `VisualElement` seems to be there, the attribute on all the view elements is missing (XAML sample: `<Button Text="Material Button" Visual="Material"/>`). I would assume it "just needs to be added and passed through".

If someone can point me in the right direction I could have a look myself.

Cheers.

**Comment by TimLariviere** [comment]
Strange, the `Visual` property is there in Fabulous 0.34.0.
```fsharp
View.Button(visual=Xamarin.Forms.VisualMarker.Material, text="Some button")
```

But you also need to follow the indications from your link to make it work:
- Add the NuGet package `Xamarin.Forms.Visual.Material` to your iOS/Android projects
- Add the flag `Visual_Experimental`
- Call `FormsMaterial.Init()`

In this picture, the `Increment` button is using Visual=Material
<img width="383" alt="image" src="https://user-images.githubusercontent.com/6429007/57910498-bbe76b80-7885-11e9-953c-9d66884c718b.png">

**Comment by aspnetde** [comment]
Oh boy, Rider f***ed up the Nuget update across the solution, so I ended up with the wrong packages in my core library. Got it working now, thank you!
