### ISSUE TITLE
Upgrade to XF 4.0

### ISSUE THREAD

**Issue by SergejDK** [fsprojects/Fabulous#412]
We could perpare the upgrade to XF 4.0.
Shown on fuget: [https://www.fuget.org/packages/Xamarin.Forms/4.0.0.425677/lib/netstandard2.0/diff/3.6.0.344457/](https://www.fuget.org/packages/Xamarin.Forms/4.0.0.425677/lib/netstandard2.0/diff/3.6.0.344457/)

Seems to be unlisted but I think there won't be many changes. [https://github.com/xamarin/Xamarin.Forms/issues/6216](https://github.com/xamarin/Xamarin.Forms/issues/6216)

@TimLariviere what do you think about preparing it?

**Comment by TimLariviere** [comment]
@SergejDK I would wait the official release. Seems it will be available in a few days.
There may be some information in a blog post that we may need to correctly support it.
Though maybe we can start now using the last preview package?

**Comment by SergejDK** [comment]
@TimLariviere 
You're right it could be some important information.

> Though maybe we can start now using the last preview package?
Do you mean this: [4.0.0.394984-pre10](https://www.fuget.org/packages/Xamarin.Forms/4.0.0.394984-pre10/lib/netstandard2.0/diff/3.6.0.344457/)

**Comment by TimLariviere** [comment]
@SergejDK Yes, I meant this version. Better to start with this than an unlisted one.

**Comment by SergejDK** [comment]
@TimLariviere 
will prepare the Update and PR.

**Comment by migueldeicaza** [comment]
XF 4.0 is now public.
