### ISSUE TITLE
Update templates to target Xamarin.Essentials 1.0.0

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#419]
Now that Xamarin.Essentials is officially out of preview, it would be better to update the version we reference in the templates.

Currently we're targeting 0.6.0-preview

**Comment by SergejDK** [comment]
We can use 1.1.0.
[https://www.nuget.org/packages/Xamarin.Essentials/](https://www.nuget.org/packages/Xamarin.Essentials/)

**Comment by TimLariviere** [comment]
I suggested limiting the upgrade to Xamarin.Essentials v1.0.0 because it's the lowest official version.
This way, we don't force our users to uselessly target Xamarin.Essentials v1.1.0+ (Fabulous itself don't require that and our users might need a specific version for X/Y reasons).

If they really want to upgrade to Xamarin.Essentials v1.1.0, they are able to do it on their own.


Generally speaking, that's a concern we're currently ignoring in Fabulous (with the packages of X.F we target for example). We just take the newest one and that's it.

But once we go live (release of Fabulous v1.0), that's something we will need to be careful about.
We don't want to prevent our users from using the package version they need just because we're targeting a package version we don't really need.

I would be interested to find a general guideline on this subject.

**Comment by SergejDK** [comment]
Good point. 
Don't know it myself how to do this right.
When I get time I will try to find sth. about this.
