### ISSUE TITLE
[Generator] Add support for the ObsoleteAttribute

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#421]
Xamarin.Forms 4.0 marked a few properties as obsolete.
To avoid making breaking changes, we should still continue to provide support for these properties, but we need a way to mark them as obsolete in Fabulous as well.

This, for 2 reasons:
- Report to the user that XF obsoleted the property they're using (and maybe later XF and Fabulous will remove this property)
- Avoid having warnings for these obsolete properties when compiling Fabulous

>Fsc: /Git/Github/Fabulous/src/Fabulous.Core/Xamarin.Forms.Core.fs(2985,37): warning FS0044: This construct is deprecated. Image is obsolete as of 4.0.0. Please use ImageSource instead.
Fsc: /Git/Github/Fabulous/src/Fabulous.Core/Xamarin.Forms.Core.fs(2986,37): warning FS0044: This construct is deprecated. Image is obsolete as of 4.0.0. Please use ImageSource instead.
Fsc: /Git/Github/Fabulous/src/Fabulous.Core/Xamarin.Forms.Core.fs(9686,37): warning FS0044: This construct is deprecated. BackgroundImage is obsolete as of 4.0.0. Please use BackgroundImageSource instead.
Fsc: /Git/Github/Fabulous/src/Fabulous.Core/Xamarin.Forms.Core.fs(9687,37): warning FS0044: This construct is deprecated. BackgroundImage is obsolete as of 4.0.0. Please use BackgroundImageSource instead.
Fsc: /Git/Github/Fabulous/src/Fabulous.Core/Xamarin.Forms.Core.fs(9691,37): warning FS0044: This construct is deprecated. Icon is obsolete as of 4.0.0. Please use IconImageSource instead.
Fsc: /Git/Github/Fabulous/src/Fabulous.Core/Xamarin.Forms.Core.fs(9692,37): warning FS0044: This construct is deprecated. Icon is obsolete as of 4.0.0. Please use IconImageSource instead.
Fsc: /Git/Github/Fabulous/src/Fabulous.Core/Xamarin.Forms.Core.fs(10222,45): warning FS0044: This construct is deprecated. SetTitleIcon is obsolete as of 4.0.0. Please use SetTitleIconImageSource instead.
Fsc: /Git/Github/Fabulous/src/Fabulous.Core/Xamarin.Forms.Core.fs(10223,45): warning FS0044: This construct is deprecated. SetTitleIcon is obsolete as of 4.0.0. Please use SetTitleIconImageSource instead.
Fsc: /Git/Github/Fabulous/src/Fabulous.Core/Xamarin.Forms.Core.fs(11248,37): warning FS0044: This construct is deprecated. Icon is obsolete as of 4.0.0. Please use IconImageSource instead.
Fsc: /Git/Github/Fabulous/src/Fabulous.Core/Xamarin.Forms.Core.fs(11249,37): warning FS0044: This construct is deprecated. Icon is obsolete as of 4.0.0. Please use IconImageSource instead.

**Comment by SergejDK** [comment]
Should we include an 'obsolete'-Part like this:
```fsharp
{
"name:": "",
"members": [
{
  "name:": "",
  "obsolete": "true",
}
]
}
```

With this we could make this work? 
Your opinion? 

Maybe a good first issue....

**Comment by TimLariviere** [comment]
>Maybe a good first issue....

I don't think so.
I don't even know how we can proceed on this one.

Marking the property obsolete in the json is one thing, but how should we translate this boolean into the generated code?
Those properties are optional method parameters. And the `[<Obsolete>]` won't work on them.

```fsharp
/// Describes a Button in the view
static member inline Button(?text: string,
                            ?command: unit -> unit,
                            ?canExecute: bool,
                            ...) = 

    let attribBuilder = View.BuildButton(0,
                            ?text=text,
                            ?command=command,
                            ?canExecute=canExecute,
                            ...)

    ViewElement.Create<Xamarin.Forms.Button>(View.CreateFuncButton, View.UpdateFuncButton, attribBuilder)
```

Maybe we could make 2 of those methods (named the same), one obsolete, the other not.
And hopefully, the compiler will choose the right one.

```fsharp
[<Obsolete("The property XYZ is obsolete")>]
static member inline Button(?text: string,
                            ?command: unit -> unit,
                            ?canExecute: bool,
                            ?XYZ: bool,
                            ...) =
    (...)

/// Describes a Button in the view
static member inline Button(?text: string,
                            ?command: unit -> unit,
                            ?canExecute: bool,
                            ...) = 

    View.Button(?text=text, ?command=command, ?canExecute=canExecute, ?XYZ=None)
```

**Comment by TimLariviere** [comment]
So, I haven't really included support for obsoleted properties into the new code gen.
Instead I think we can mitigate obsolete properties ourselves because most of the changes are renaming (e.g. `TitleIconImage` to `TitleIconImageSource`) where we can redirect the `titleIconImage` property directly to the new property without adding breaking changes.
