### ISSUE TITLE
Missing Xamarin.Forms.Core.fs

### ISSUE THREAD

**Issue by StefanBelo** [fsprojects/Fabulous#429]
Just downloaded the source but am not able to compile:

Severity	Code	Description	Project	File	Line	Suppression State
Error	FS0225	Source file 'D:\Samples\Fabulous-master\src\Fabulous.Core\Xamarin.Forms.Core.fs' could not be found	Fabulous.Core	D:\Samples\Fabulous-master\src\Fabulous.Core\FSC	1	Active

**Comment by TimLariviere** [comment]
@StefanBelo Yes, it's a generated file.
You need to run the command `./build.cmd RunGenerator` at minimum, before being able to compile it in Visual Studio
https://github.com/fsprojects/Fabulous/blob/master/DEVGUIDE.md#dev-notes---building

**Comment by StefanBelo** [comment]
Thanks Tim, I have tried, but:

Build started 30. 5. 2019 19:04:43.
     1>Project "D:\Samples\Fabulous-master\tools\Generator\Generator.fsproj" on node 1 (Restore target(s)).
     1>D:\Samples\Fabulous-master\tools\Generator\Generator.fsproj(2,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored
        in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
     1>Done Building Project "D:\Samples\Fabulous-master\tools\Generator\Generator.fsproj" (Restore target(s)) -- FAILED.

Build FAILED.

       "D:\Samples\Fabulous-master\tools\Generator\Generator.fsproj" (Restore target) (1) ->
         D:\Samples\Fabulous-master\tools\Generator\Generator.fsproj(2,1): error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is author
       ed in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2
       format, please convert it to MSBuild 2003 format.

    0 Warning(s)
    1 Error(s)

**Comment by StefanBelo** [comment]
What is strange, when selecting the failed project in VS and clicking on Build, the project: Generator is built without errors.

So this Generator should generate from json the fs file for Fabulous.Core?

**Comment by TimLariviere** [comment]
Do you have all the prerequisites installed, especially the `dotnet` SDK?
https://github.com/fsprojects/Fabulous/blob/master/DEVGUIDE.md#dev-notes---prerequisites

**Comment by StefanBelo** [comment]
I have got following:

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview5-011568\

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview5-27626-15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by TimLariviere** [comment]
Does the generator builds when you run the command `dotnet build "D:\Samples\Fabulous-master\tools\Generator\Generator.fsproj"`?

**Comment by StefanBelo** [comment]
Yes, it builds.

**Comment by TimLariviere** [comment]
Could you try to run the command `./build.cmd RunGenerator` in the Developer Command Prompt for Visual Studio?
I think there's a limitation when building Fabulous on Windows, the classic Cmd and PowerShell use the wrong version of MSBuild.

**Comment by StefanBelo** [comment]
I am sorry Tim, the same result. I used Developer Command Prompt for VS2014, and the exactly same results.

My intention to test Fabulous was just to debug some code and see how the elmish approach is used. 
Last two weeks I tried blazor, and fsbolero that uses elmish as well, and I wanted to get myself some answer on this question I asked on websharper forum: 

https://forums.websharper.com/topic/86905

Today I tested Elmish.WPF, and I have got some answer, there he actually wrapped MVVM internally to bind to WPF controls.

In Fabulous you say you have got WPF support nut it is actually Xamarin Forms support not native WPF, right?

Couple years ago I built my desktop app using devexepress WPF libraries, and I do not think that could be replicated by Fabulos, as xamarin wrapper is actually used, so is fabulous really supporting WPF?
My app is built in F# and for UI I used MVC and great at that time FSharp.Desktop.UI:

http://bfexplorer.net/Products/Bfexplorer

so is Fabulous suitable for such kind of WPF apps?

**Comment by TimLariviere** [comment]
VS2015 won't work. VS2017 or VS2019 are required.

>In Fabulous you say you have got WPF support but it is actually Xamarin Forms support not native WPF, right?

Yes. Fabulous is built on top of Xamarin.Forms.
It's still the native WPF controls that are built, but they are used through the Xamarin.Forms APIs.

>Couple years ago I built my desktop app using devexepress WPF libraries, and I do not think that could be replicated by Fabulos, as xamarin wrapper is actually used, so is fabulous really supporting WPF?

We're supporting WPF as much as Xamarin.Forms does.
Like any cross-platform framework, some choices have been made, and it might not be suitable for some heavy UI apps like yours.
So if your application is too complex to be ported to Xamarin.Forms, you won't have more success with Fabulous sadly...

**Comment by StefanBelo** [comment]
Still the same results using:

Developer Command Prompt for VS 2019 Preview, or
Developer PowerShell for VS 2019 Preview

Thanks for your help Tim, I will try again in 1-2 weeks.

**Comment by SergejDK** [comment]
@StefanBelo 
VS2017 is needed on Windows. Had the same problem when I set up my computer the last day. 
Wanted to investigate on this issue but didn't have the time.  

Normally this should be done with PR #390 

@TimLariviere any suggestions?

**Comment by TimLariviere** [comment]
@SergejDK I will try with a clean VM of Windows + VS2019 and document the exact things I do to make it compile.

**Comment by TimLariviere** [comment]
It appears to be an issue with FAKE not correctly resolving MSBuild when both VS2017 and VS2019 are installed.
The current workaround is to either use the developer command prompt for VS2017 or uninstall VS2017.
https://github.com/fsharp/FAKE/pull/2344
