### ISSUE TITLE
Visual studio and rider cannot load a template project

### ISSUE THREAD

**Issue by nanodesu88** [fsprojects/Fabulous#436]
Can we please have a getting started manual which works?

**Comment by SergejDK** [comment]
Could you give us the steps what exactly you tried?
Else we do not know how we can help you.

**Comment by PureWeen** [comment]
So I ran into this issue today playing with Fabulous on the stream when running the basic SqueekyApp. You can see it here

https://www.twitch.tv/videos/435836117?t=00h28m47s

- The head project has a different version of forms than the cross platform
- I couldn't get it to compile on VS2019
- The templates should probably be updated to latest essentials, forms, fabulous?

**Comment by SergejDK** [comment]
Don't know why but it seems that it uses a very old template.
XF has normally`4.0...` and it is no longer `Elmish.XamarinForms` but `Fabulous....`.

@PureWeen 
did you have an older version on your computer? 
I couldn't see in the video if the installation/update worked correctly.

Could you maybe try the same steps with powershell/bash not the developer prompt?

On my machine it works correct, so it is kinda hard to identify the parts.

**Comment by TimLariviere** [comment]
@PureWeen Ok, I think I know why. Had to rewatch a few times to make sure.

You're creating a new SqueakyApp under your `H:\streamhub\` folder.
But then you open in Visual Studio `H:\SqueakyApp\SqueakyApp.sln` which seems an old version from the time of `Elmish.XamarinForms`

**Comment by PureWeen** [comment]
@TimLariviere That's hilarious.... I guess I should have called it something else when I newed it up hunh? Sorry about that

I reran the template and opened the correct app and look at that it works.

Alright so now that I have a theoretically correct sample :-) 
Can the support libraries be updated to API 28? Since the android project is 9.0? That's also where users will be able to use the material elements as well.

**Comment by TimLariviere** [comment]
>Can the support libraries on those templates be updated to API 28? Since the android project is 9.0? That's also where users will be able to use the material elements as well.

@PureWeen Yes, definitely!
Opened issue #442 to track it
