### ISSUE TITLE
Custom Renderers

### ISSUE THREAD

**Issue by pauldorehill** [fsprojects/Fabulous#440]
Recently I've got to the point where I need to add some custom renderers to my app - its primary use is UWP (this [issue](https://github.com/dotnet/corert/issues/6055) means I'm having to use some C#). All was going smoothly based on the [Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/view) and the [Fabulous](https://fsprojects.github.io/Fabulous/views-extending.html) docs until it came to having the view update on a change to a property on the type I had defined: it wasn't updating. Having spent some time investigating its seems the `OnPropertyChanged` or `OnPropertyChanging` event isn't called for user a defined property and you need to hook this up yourself. I'm new to Xamarin so perhaps this is well known? 

What I came up with is the below: if there is a more typical way/better way of doing this can you let me know? As think it would be good to include something on this in the documentation which I would be happy to add.

In shared project:
```FSharp
type MyTreeView(itemsSource) =
    inherit View()
    let ev = new Event<_,_>()
    let mutable itemsSource = itemsSource
    static member ItemsSourceKey = AttributeKey "ItemsSource"
    member this.ItemsSource
        with get() = itemsSource
        and set value = 
            itemsSource <- value
            this.OnPropertyChanged MyTreeView.ItemsSourceKey.Name
    interface INotifyPropertyChanged with
        [<CLIEvent>] member __.PropertyChanged = ev.Publish
    // Fabulous view extension code
    static member inline View(?itemsSource) =
        // Count the number of additional attributes
        let attribCount = 1
        // Count and populate the inherited attributes
        let attribs = ViewBuilders.BuildView(attribCount)
        // Add additional attributes
        attribs.Add(MyTreeView.ItemsSourceKey, itemsSource)
        // Create method
        let create() = new MyTreeView(itemsSource)
        // The update method
        let update (prevOpt: ViewElement voption) (source: ViewElement) (target: MyTreeView) =
            ViewBuilders.UpdateView(prevOpt, source, target)
            source.UpdatePrimitive(prevOpt, target, MyTreeView.ItemsSourceKey, (fun target v -> target.ItemsSource <- v))
        // Create the view element
        ViewElement.Create<MyTreeView>(create, update, attribs)
```

Custom renderer in UWP project:
```CSharp
public class MyTreeViewRenderer : ViewRenderer<View, TreeView>
{
    protected override void OnElementChanged(ElementChangedEventArgs<View> e)
    {
        base.OnElementChanged(e);
        if (Control == null)
        {
            // Create control
            SetNativeControl(new TreeView());
        }
        if (e.OldElement != null)
        {

        }
        if (e.NewElement != null)
        {
                       
        }
    }

    protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        base.OnElementPropertyChanged(sender, e);
        if (e.PropertyName == MyTreeView.ItemsSourceKey.Name)
        {
            // Do stuff on change to property            
        }
    }
}
```

**Comment by TimLariviere** [comment]
>until it came to having the view update on a change to a property on the type I had defined: it wasn't updating. Having spent some time investigating its seems the OnPropertyChanged or OnPropertyChanging event isn't called for user a defined property and you need to hook this up yourself. I'm new to Xamarin so perhaps this is well known?

@pauldorehill This is typically done by using a `BindableProperty`. It's a special way to declare a property on a control that provides a bunch of additional things like changing/changed events.
https://docs.microsoft.com/xamarin/xamarin-forms/xaml/bindable-properties

Regarding your Fabulous extension, I would recommend to really split it from your UWP control.
For instance, you shouldn't declare the Fabulous attribute key `ItemsSourceKey` inside your UWP control.

Otherwise your control won't be reused outside of Fabulous.

**Comment by pauldorehill** [comment]
@TimLariviere thanks for the pointer to `BindableProperty`... I'd completely overlooked its significance in the example on the custom renderers page.

The example is just my rough sketch of hooking everything up before moving forward with something more serious.
