### ISSUE TITLE
Allow CodeGen to generate bindings for external libraries

### ISSUE THREAD

**Issue by SergejDK** [fsprojects/Fabulous#441]
Today, CodeGen scans existing dlls to automatically extract controls and properties, generating Fabulous-compatible wrappers for them.
The inheritance tree is used to propagate properties across controls (e.g. all controls inheriting from `Element` will have an `AutomationId` field such as `View.Button(automationId=XXX)` is possible).
CodeGen currently assumes the complete hierarchy will be found in the provided dlls.

It would be great to let people use CodeGen to generate wrappers for third party libraries (e.g. Maps, Telerik, etc.).
But for that, CodeGen need to be adapted to support additional inputs, under the form of already written bindings files, to let it know there's already a supported hierarchy on which it can depend.

E.g.
Generating a bindings file for a given dll:
`dotnet run fabulous-xf-generator.dll generate-bindings -d Xamarin.Forms.Maps.dll`

Generating wrappers for a previously created bindings file, with references to other bindings file:
`dotnet run fabulous-xf-generator.dll generate-wrappers -m Xamarin.Forms.Maps.json -o Fabulous.XamarinForms.Maps.dll`

With `Xamarin.Forms.Maps.json` (follows the same structure than `Xamarin.Forms.Core.dll`)
```json
{
  "assemblies": [
    "packages/neutral/Xamarin.Forms.Maps/lib/netstandard2.0/Xamarin.Forms.Maps.dll"
  ],
  "bindings": [
    "Fabulous.XamarinForms/src/Fabulous.XamarinForms.Core/Xamarin.Forms.Core.json"
  ],
  "outputNamespace": "Fabulous.XamarinForms",
  "types": [
     {
         "type": "Xamarin.Forms.Maps.Map",
         (...)
      }
  ]
}
```

The new part is the `"bindings"` field.

This would let users write things like `View.Map(automationId=XXX)`.

Initial message:
>If we want to support a new extension e.g. [Avalonia UI](http://avaloniaui.net/) we have to write a lot of code which can be generated by the Generator.
>So maybe we could use a seperate json file as the `Xamarin.Forms.Core.json` for each extension and let it run through this everyone could make their needed extension work on fabulous. 
There are some changes to make on the Generator part, too but didn't identify them yet.
>Then with a command like `./build.sh RunGenerator {extensionpath}` it can be run and the extension will be created. 
>After all the work for a sample have to be done manually.

**Comment by TimLariviere** [comment]
I agree that we need to simplify the process of creating extensions for Fabulous.
The first and easiest way is to let people use the Generator like you suggested.

>If we want to support a new extension e.g. Avalonia UI

Avalonia UI is not an extension the way Fabulous understands it.
It's a full blown UI framework, like Xamarin.Forms. (see https://github.com/fsprojects/Fabulous/issues/437#issuecomment-499118627 for more info on potential support for other UI frameworks)

An extension for Fabulous, today, is a wrapper for an existing Xamarin.Forms component.
This is a completely different thing 😄 

>Then with a command like ./build.sh RunGenerator {extensionpath}

I would very much prefer to release it as an executable (usable without cloning the Fabulous repository and toying with the build script).

Maybe embed it in Fabulous.Cli so it could be used as a CLI tool?
`dotnet fabulous generate-wrapper my-extension.json`

Also it would be great if we can automate the generation of this json bindings file.
People would then correct this file by hand before running the `generate-wrapper` command.

A quick reflection on a given dll to extract all controls and their properties should be doable. (Generator does that to get the correct types when not set in the json file)
`dotnet fabulous generate-bindings MyControls.dll`

**Comment by SergejDK** [comment]
> An extension for Fabulous, today, is a wrapper for an existing Xamarin.Forms component.
This is a completely different thing 😄

Yes, you are right - just a wrong example of me

> Maybe embed it in Fabulous.Cli so it could be used as a CLI tool?
dotnet fabulous generate-wrapper my-extension.json

This would make it a lot easier to use and less work for us on the build script, so I this approach seems to be a lot better than my idea!

> Also it would be great if we can automate the generation of this json bindings file.

Was thinking about this, too but did not exactly thought about how - your way seems to be good on this so we should include/do it!

**Comment by xperiandri** [comment]
Does this already work? Generator

**Comment by TimLariviere** [comment]
@xperiandri No, and the discussion here is not really what we went with in the end.

The idea today is to use the new CodeGen through the corresponding generator (e.g. for Fabulous.XamarinForms it is `Fabulous.XamarinForms.Generator`).

It is already capable of scanning dlls to generate wrappers for the contained controls.
Though it still need to be slightly modified to support inheritance of the already generated wrappers.
