### ISSUE TITLE
Add nuget package fails (win)/new fabulous project does not build (mac): mono 5.18.1.28

### ISSUE THREAD

**Issue by marcelstuder** [fsprojects/Fabulous#443]
I am having troubles adding nuget packages to a solution created with the latest fabulous template 0.35.0:  **Error: Object reference not set to an instance of an object**

## Remarks

* I am not sure if this is an issue caused by the fabulous template. Actually when writing down this issue I got more and more to the conclusion that this might be caused by the mono framework 5.18.1.28 but VS 2019 16.1.2 doesn't let me connect to a Mac with Mono 5.18.1.3 (after reopening the solution visual studio always shows a Xamarin.iOS versions mismatch warning and downgrades to 5.18.1.28)
* creating a standard xamarin forms application using the same machines lets me add nuget packages without any erros (which is why it still might have to do with the fabulous template)
* the error message on the mac shown when creating a brand new fabulous app (the "GenerateDepsFile" task failed unexpectedly) might be a separate issue but it seems to be related to the mono version

Disclaimer: I am new to xamarin forms/fabulous.

* Does anyone experience the same issues?
* If it is not caused by the fabulous template: where should I post this issue? 

#### Developer machine

Platform: Windows 10 Pro 1809
DevEnv: Visual Studio 2019 (16.1.2) (run as Admin)
.NET Core SDK 2.2.300
Debug in Simulator (iPhone 7 Plus iOS 12.2)

#### Build machine

MacBook Pro Mid 2015 with lates MacOS Mojave 10.14.5, all Updates applied
Visual Studio for Mac Community 8.0.9 (build 5)
Mono Framework: 5.18.1.28 (5.18.1.3 available, but Visual Studio 2019 displays a mono version mismatch when connecting to the build machine and downgrades to 5.18.1.28)
Xamarin.iOS: 12.10.0.153 (installed due to warning whenn connecting to the build machine that version 12.8.0.2 is outdated)

## Steps to reproduce (Windows)

* install app template (only if missing on your machine): `dotnet new -i Fabulous.Templates`
* create new app: `dotnet new fabulous-app -n SqueakyApp`
* Open solution in Visual Studio 2019
* set IOS Project as starting project 
* debug in Simulator -> App starts in Simulator
* stop app
* try to add the nuget package "IdentityModel" (v3.10.10) to all projects (via "Manage NuGet Packages for solution dialog (right click on solution, context menu))

### Expected behaviour

* NuGet Package is added to all three projects

### Actual behaviour

* Error: "Failed to add reference to 'System.Text.Encodings.Web'. Object reference not set to an instance of an object.

### Notes

* the same error shows up on a different developer machine
* it also happens with other nuget packages
* same effect when I try to update Newtonsoft.Json to Version 12.0.2: "Failed to add reference to 'Newtonsoft.Json'. Object reference not set to an instance of an object.

## Steps to reproduce (Mac)

* install app template (only if missing on your machine): `dotnet new -i Fabulous.Templates`
* create new app: `dotnet new fabulous-app -n SqueakyApp`
* Open solution in Visual Studio 2019 in Visual Studio for Mac
* set IOS Project as starting project and hit run

### Expected behaviour

* App starts in Simulator

### Actual behaviour

* Error: the "GenerateDepsFile" task failed unexpectedly

### Workaround

Update Mono on the mac to 5.18.1.3

* build/run in the simulator works
* adding nuget packages (IdentityModel, ...) works

## Workaround

* open Solution on build machine (mac) 
* Update mono framework to 5.18.1.3 (but do not downgrade to 12.8.0.2 which is what visual studio for mac wants to do in the check for updates dialog)
* add packages 

Which basically boils down to: develop on the mac using mono 5.18.1.3

**Comment by marcelstuder** [comment]
This here seems to be related: https://developercommunity.visualstudio.com/content/problem/579489/mono-version-mismatch-between-vs-windows-and-vs-ma.html

**Comment by TimLariviere** [comment]
Thanks for reporting it.
But I don't think these two issues are specific to Fabulous.

Visual Studio (Windows) and Visual Studio for Mac move at a different pace, VSfM usually have a higher version of Xamarin.

Regarding your issue on Windows, I don't think we can do anything. It's an issue with the IDE itself.
Fabulous doesn't do anything special, we're just .NET Standard 2.0 libs, just like Newtonsoft.Json and many others.

And regarding your issue on macOS with Mono 5.18.1.28, it's not crashing in our code.
```/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly.
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018: System.MissingMethodException: Method not found: System.Collections.Generic.IList`1<NuGet.Packaging.Core.PackageDependency> NuGet.ProjectModel.LockFileTargetLibrary.get_Dependencies()
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at Microsoft.NET.Build.Tasks.DependencyContextBuilder+<>c__DisplayClass36_0.<GetLibraries>b__0 (NuGet.ProjectModel.LockFileTargetLibrary export) [0x00000] in <3326f2934caf40ca95ce625057dcebd2>:0 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].MoveNext () [0x0003a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.Linq/src/System/Linq/Select.cs:224 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at System.Linq.Enumerable+<CastIterator>d__34`1[TResult].MoveNext () [0x0005f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.Linq/src/System/Linq/Cast.cs:50 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at System.Collections.Generic.LargeArrayBuilder`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] items) [0x0003d] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs:172 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at System.Collections.Generic.SparseArrayBuilder`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] items) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/System/Collections/Generic/SparseArrayBuilder.cs:106 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at System.Collections.Generic.SparseArrayBuilder`1[T].ReserveOrAdd (System.Collections.Generic.IEnumerable`1[T] items) [0x00017] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/System/Collections/Generic/SparseArrayBuilder.cs:204 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at System.Linq.Enumerable+ConcatNIterator`1[TSource].LazyToArray () [0x00021] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.Linq/src/System/Linq/Concat.cs:291 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at System.Linq.Enumerable+ConcatNIterator`1[TSource].ToArray () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.Linq/src/System/Linq/Concat.cs:269 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:18 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at Microsoft.Extensions.DependencyModel.DependencyContext..ctor (Microsoft.Extensions.DependencyModel.TargetInfo target, Microsoft.Extensions.DependencyModel.CompilationOptions compilationOptions, System.Collections.Generic.IEnumerable`1[T] compileLibraries, System.Collections.Generic.IEnumerable`1[T] runtimeLibraries, System.Collections.Generic.IEnumerable`1[T] runtimeGraph) [0x00068] in <fa4af318e8374ad18eef8b73f115183f>:0 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at Microsoft.NET.Build.Tasks.DependencyContextBuilder.Build () [0x001bd] in <3326f2934caf40ca95ce625057dcebd2>:0 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore () [0x00117] in <3326f2934caf40ca95ce625057dcebd2>:0 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at Microsoft.NET.Build.Tasks.TaskBase.Execute () [0x00000] in <3326f2934caf40ca95ce625057dcebd2>:0 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:573 
/usr/local/share/dotnet/sdk/2.2.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(129,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002a9] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:810 
    0 Warning(s)```

If you have more information that point to Fabulous being the cause of these issues, don't hesitate to reopen this issue.
