### ISSUE TITLE
How does Fabulous handle virtualization for ListView et al.?

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/Fabulous#455]
I've come across a hitch when developing a dynamic UI library for WPF: I can't see a way to enable virtualization. I figured I'd take a look at how Fabulous does things, since Xamarin.Forms also supports virtualization, but I don't see "virtual" of any kind anywhere in this repo. So how is Fabulous handling this?

My naïve approach (similar to all other properties) is to have a property `ListBox.Items` of type `ListBoxItem list`, where `ListBox` and `ListBoxItem` are "shadow DOM" types. But when the control is rendered, all the `ListBoxItem`s are rendered, too, because virtualization in WPF seems to be inextricably linked to data binding - simply put, `ListBox.ItemsSource` is bound to some collection, and the `ListBoxItem`s are defined as a template that is rendered on demand (controlled by, among other things, virtualization). It thus seems that in order to enable virtualization, I either have to implement my own virtualization, or mess around with bindings and probably `ObservableCollection`s, and I'd rather not do either of them and keep the "shadow DOM" conceptually simple (a `ListBox` generates a real `ListBox`, and a `ListBoxItem` generates a real `ListBoxItem`.)

**Comment by TimLariviere** [comment]
Fabulous uses the default virtualization mecanism of Xamarin.Forms / WPF (with `ItemsSource`, `ItemTemplate` and `ObservableCollection`).
We derived our own `ViewCell` (base type for any data in ListView) to support `ViewElement` as a data context.

Then it's this `ViewElementCell` that is responsible for rendering the row from the `ViewElement`.
Xamarin.Forms manages the lifecycle of that cell, by reusing it or destroying it.
We react to that with the event `OnBindingContextChanged`.

https://github.com/fsprojects/Fabulous/blob/dcf5dbe175fa617977a6aa08a5a25dff25f5c292/src/Fabulous.Core/ViewConverters.fs#L177-L179

https://github.com/fsprojects/Fabulous/blob/dcf5dbe175fa617977a6aa08a5a25dff25f5c292/src/Fabulous.Core/ViewConverters.fs#L90-L132

**Comment by davidglassborow** [comment]
I was initially confused when I tried to use a TextCells for ListView children as I would have expected coming from XF and it threw a rather cryptic error from line 100 above.
