### ISSUE TITLE
[Sample] macOS Samples Close

### ISSUE THREAD

**Issue by SergejDK** [fsprojects/Fabulous#458]
Currently the macOS samples dont close the complete sample on click 'x'. Would be good to make them close on close button.

**Comment by davidglassborow** [comment]
I'd be happy to do this, but currently my environment has been broken by some combination for dotnet core and VS for Mac :-(

The change is to add this line to the `AppDelegate.fs`, as part of the `AppDelegate()` class:

`    override __.ApplicationShouldTerminateAfterLastWindowClosed(_) = true`

I'd suggest we add it to the macos template as well as the samples

**Comment by SergejDK** [comment]
> I'd be happy to do this, but currently my environment has been broken by some combination for dotnet core and VS for Mac :-(

Did you updates vs for mac and not dotnetcore? had an issue a few days ago.  Needed the newest dotnet core then it worked again.

> I'd suggest we add it to the macos template as well as the samples

I think that could be helpful!

**Comment by davidglassborow** [comment]
Just found https://docs.microsoft.com/en-us/visualstudio/mac/net-core-support?view=vsmac-2019, which allowed me to resolve the issue, thanks !.

I'll raise a PR.
