### ISSUE TITLE
Clear Entry on refresh of view

### ISSUE THREAD

**Issue by auslavs** [fsprojects/Fabulous#462]
When the model is reloaded, how do you clear an Entry's elements text field?
In the below example the expected behaviour is that when the enter key is pressed, the Scan Message is sent, the label should update and the Entry text is an empty string.

Sorry for such a simple question, but I'm really stumped here.
I assume I need something to force a re-evaluation of the value to allow it to update?

```
  let view (model: Model) dispatch =
    let barcode1 = model.Barcode1 |> Option.defaultValue ""
    let barcode2 = model.Barcode2 |> Option.defaultValue ""
    let feedback = model.Feedback |> Option.defaultValue ""

    View.ContentPage(
      content = View.StackLayout(padding = 20.0, verticalOptions = LayoutOptions.Center,
        children=[
          View.Label(text = barcode1)
          View.Label(text = barcode2)
          View.Label(text = feedback, textColor = Xamarin.Forms.Color.Red)
          View.Entry(text = String.Empty, fontSize = 20, completed = (fun text -> dispatch (Scan text)))
        ]))
```

**Comment by TimLariviere** [comment]
@auslavs Fabulous only checks the difference between 2 calls to the `view` function to determine if something has changed, it doesn't check the actual value of the Entry.

So by setting `View.Entry(text = String.Empty)`, you're telling Fabulous that the Entry has always the same value and doesn't need to be updated.

In general, what we do in that case is we track the text changes in our model and link this model to the View.Entry text field.
That way, each time the text changes Fabulous will know. And if you reset the model's text field, Fabulous will apply it on the UI.

```fsharp
type Model = 
  { Barcode1: string option
    Barcode2: string option
    Feedback: string option
    EntryText: string }

type Msg = 
    | Scan of string
    | TextChanged of string

let initModel = { Barcode1 = None; Barcode2 = None; Feedback = None; EntryText = "" }

let init () = initModel, Cmd.none

let update msg model =
    match msg with
    | Scan text -> { model with Barcode1 = Some "Thing1"; Barcode2 = Some "Thing2"; Feedback = Some "Thing3"; EntryText = "" }, Cmd.none
    | TextChanged text -> { model with EntryText = text }, Cmd.none

let view (model: Model) dispatch =
    let barcode1 = model.Barcode1 |> Option.defaultValue ""
    let barcode2 = model.Barcode2 |> Option.defaultValue ""
    let feedback = model.Feedback |> Option.defaultValue ""

    View.ContentPage(
      content = View.StackLayout(padding = 20.0, verticalOptions = LayoutOptions.Center,
        children=[
          View.Label(text = barcode1)
          View.Label(text = barcode2)
          View.Label(text = feedback, textColor = Xamarin.Forms.Color.Red)
          View.Entry(text = model.EntryText, fontSize = 20, textChanged = (fun e -> dispatch (TextChanged e.NewTextValue)), completed = (fun text -> dispatch (Scan text)))
        ]))
```

Also this allows you to track what your user has written that may crash your app.

**Comment by auslavs** [comment]
@TimLariviere, thank you very much for the quick and detailed feedback.
I have working now :-)
