### ISSUE TITLE
The default background color of PlotView is white, should be transparent?

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#469]
It just seems weird. Having a transparent background by default would make much more sense.

**Comment by SergejDK** [comment]
this is the default of oxyplot. 
We could change that but don't know if we should. Normally the wrappers use the default of the extension. 
@TimLariviere do you think we should change?

**Comment by TimLariviere** [comment]
I would prefer to keep it to the default value. Setting it to another value might confuse people.
We try to only make the fewest adaptations possible, only to make something work in the context of MVU.

**Comment by Happypig375** [comment]
Okay, noted.
