### ISSUE TITLE
Is there a sample showing scroll to last item in list view?

### ISSUE THREAD

**Issue by vshapenko** [fsprojects/Fabulous#470]
Hello! I am wondering if there is  a sample in fabulous samples, which shows scrolling to last item behavior? From docs and experiments i did not figured out how to implement such functionality.

**Comment by TimLariviere** [comment]
@vshapenko Hi. I don't think there is this specific example in the docs or the samples.

However you can take advantage of the `ViewRef` (https://fsprojects.github.io/Fabulous/views-animations.html#viewrefs)

The idea is that it's a specific action on a control, and Fabulous won't expose that directly.
So `ViewRef` will give you a direct access to the Xamarin.Forms control, and then you can do it like you would in Xamarin.Forms.

For example:

```fsharp
let listViewRef = ViewRef<_>

let scrollToLast () =
    match listViewRef.TryValue with
    | None -> () // Do nothing, because there is no ListView
    | Some listView ->
        // We now have access to the Xamarin.Forms.ListView
        let lastItem = listView.ItemsSource |> Seq.last
        listView.ScrollTo(lastItem)

let update msg model =
    match msg with
    | ScrollToLastMsg ->
        scrollToLast()
        model // Model did not change

let view model dispatch =
    (...)
        View.Button(command=(fun () -> dispatch ScrollToLastMsg))
        View.ListView(
            ref=listviewRef, // Associate the ViewRef to the ListView
            items=[ ... ])
```

**Comment by vshapenko** [comment]
Looks like that does not work. I am storing the ref in model and invoking scroll on update cycle when receiving ScrollToLast by following:
` model.Ref.TryValue|>Option.iter (fun x->match (x.ItemsSource.OfType<obj>()|>Seq.tryLast) with
                                                  |Some i->x.ScrollTo(i,ScrollToPosition.End,false)
                                                  |None->() 
                                           )`
But nothing happens with my list view. I guess what should i pass as first param to  ScrollTo. Passing last of ItemsSource does not work at all. 
Another problem that i have different object types in my list(I am building list items from different sources not tied together by types and bind ViewElement list as items )

**Comment by vshapenko** [comment]
Further invesigastion has  shown that i need to pass viewElement i want to scroll to as parameter of ScrollTo. All is working now
