### ISSUE TITLE
Images in docs

### ISSUE THREAD

**Issue by CMThre3** [fsprojects/Fabulous#475]
Creating an issue to add images to the docs for the view elements

**Comment by CMThre3** [comment]
![editor triplescreenshot](https://user-images.githubusercontent.com/52166903/60175348-3ef7cc00-980b-11e9-980d-de470e30f94e.png)

**Comment by dsyme** [comment]
These have been added for the core elements.  They link to the github user content for the above images.  We can add them in-repo if necessary

**Comment by TimLariviere** [comment]
Add missing image
![basicboxview](https://user-images.githubusercontent.com/6429007/60753625-c1377b80-9fd5-11e9-91cc-eaef04a372cf.png)
