### ISSUE TITLE
macOS fsprojs complain on load

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#487]
```
C:\Users\Admin\source\repos\Fabulous\Fabulous.XamarinForms\samples\AllControls\macOS\AllControls.macOS.fsproj : error  : The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.FSharp.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Mac\Xamarin.Mac.FSharp.targets

C:\Users\Admin\source\repos\Fabulous\Fabulous.XamarinForms\samples\Calculator\macOS\Calculator.macOS.fsproj : error  : The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.FSharp.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Mac\Xamarin.Mac.FSharp.targets

C:\Users\Admin\source\repos\Fabulous\Fabulous.StaticView\samples\StaticViewCounterApp\macOS\StaticViewCounterApp.macOS.fsproj : error  : The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.FSharp.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Mac\Xamarin.Mac.FSharp.targets

C:\Users\Admin\source\repos\Fabulous\Fabulous.XamarinForms\samples\CounterApp\macOS\CounterApp.macOS.fsproj : error  : The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.FSharp.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Mac\Xamarin.Mac.FSharp.targets

C:\Users\Admin\source\repos\Fabulous\Fabulous.XamarinForms\samples\TicTacToe\macOS\TicTacToe.macOS.fsproj : error  : The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.FSharp.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Mac\Xamarin.Mac.FSharp.targets

```

Is this intended?

**Comment by TimLariviere** [comment]
I think it's an issue for the F# Xamarin team.

We only reference the file `$(MSBuildExtensionsPath)\Xamarin\Mac\Xamarin.Mac.FSharp.targets`.
From your logs and what I found on my Windows machine, this targets file does exist.
(Resolves to `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Mac\Xamarin.Mac.FSharp.targets`)

But then, this file tries to import "Microsoft.FSharp.Targets".
It tries a few paths, before defaulting on the one it's complaining about in your logs.

I just checked, the file `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\FSharp\Microsoft.FSharp.targets` exists, and it should even be the first one to be tested...

From `Xamarin.Mac.FSharp.targets`:
```xml
<Import Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets')"
        Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets" />
```

On my machine, the variables resolve to:
- MSBuildExtensionsPath32 = C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild
- VisualStudioVersion = 16.0

**Comment by TimLariviere** [comment]
Hmm ok, fixed it by renaming the file `Microsoft.FSharp.targets` to `Microsoft.FSharp.Targets` to match what's expected in `Xamarin.Mac.FSharp.targets`.
It fixed the error messages. MSBuild on Windows appears to be sensible to casing apparently...

Maybe @nosami would know more about this?

**Comment by nosami** [comment]
I guess the MacOS targets have never been well tested on Windows 😄 

Did this ever work? Maybe it's a regression in MSBuild?

**Comment by nosami** [comment]
The MacOS project should probably be disabled via configuration when running on Windows.

**Comment by TimLariviere** [comment]
Opened https://github.com/xamarin/xamarin-macios/issues/6721 and https://github.com/xamarin/xamarin-macios/pull/6722

**Comment by TimLariviere** [comment]
The fix has been merged. I guess it will be released in the next version of Visual Studio.

**Comment by dsyme** [comment]
I haven't seen this problem, will close
