### ISSUE TITLE
Any plans for adding RecyclerView?

### ISSUE THREAD

**Issue by vshapenko** [fsprojects/Fabulous#495]
Hi! I am wondering  are there any plans to add RecyclerView to Fabulous?

**Comment by mallibone** [comment]
Hi @vshapenko, do you mean the Android RecyclerView? If so, probably not anytime soon. Mainly due to Fabulous using Xamarin.Forms under the hood - and this would require that Fabulous would start wrapping Xamarin Android directly. Or did I misunderstand your question?

**Comment by Happypig375** [comment]
`RecyclerView` in Android is available as `CollectionView` in Xamarin Forms starting in 4.0. Fabulous includes this control since 0.36.0.

**Comment by vshapenko** [comment]
@Happypig375 Thank you very much

**Comment by SergejDK** [comment]
@vshapenko 
A hint on this: CollectionView could be broken right now!

with the next release it will work without problems. There was a bug in 4.0 which is fixed in 4.1 so when we get the PR done, you can use it without problems.

**Comment by SergejDK** [comment]
With the release of Fabulous 0.41 CollectionView is usable now!
