### ISSUE TITLE
Is there any way to memoize the real view?

### ISSUE THREAD

**Issue by vshapenko** [fsprojects/Fabulous#524]
So, the problem. I need to keep up the scroll position on one of my views and i am wondering if there is a way to "memoize" the view state and later just use that view as a base of later model updates? 
In Android there is an Activity with view attached to it, in iOS it is SceneManager (AFAIR). In Fabulous i have only model and do not have a state of a visual, and in some scenarios it hurts alot (like show chat page, move scroll, go back, go chat page again, ensure that scroll position stays the same as the previous one). For me current mvu behavior looks like a design flaw in terms of mobile app development. It is very good for web i believe, but for mobile there is a lot of questions. One way we could achieve it, i think, would be mixing StaticView and dynamic view (i.e. give possibility to use static views in mvu cycle). @TimLariviere @dsyme @SergejDK  What do you think?

**Comment by dsyme** [comment]
> In Android there is an Activity with view attached to it, in iOS it is SceneManager (AFAIR). In Fabulous i have only model and do not have a state of a visual, and in some scenarios it hurts alot (like show chat page, move scroll, go back, go chat page again, ensure that scroll position stays the same as the previous one). For me current mvu behavior looks like a design flaw in terms of mobile app development. It is very good for web i believe, but for mobile there is a lot of questions. One way we could achieve it, i think, would be mixing StaticView and dynamic view (i.e. give possibility to use static views in mvu cycle). @TimLariviere @dsyme @SergejDK What do you think?

Have you used [the "dependsOn" technique](https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/views-perf.html) to improve performance, avoiding view recomputations (and zero-effect diffing) for parts that do not change?

If any parts of your view are static then you should also definitely ensure they are computed statically and the precise same values (same object identity) are used on each computation of the view

**Comment by dsyme** [comment]
> ensure that scroll position stays the same as the previous one

Hmmm in this case the scroll position should be part of the app model, updated as the scrolling is done at an appropriate rate, with a very carefully written view function to avoid recomputation.

@TimLariviere Do you have an idea of the right approach for this?

**Comment by vshapenko** [comment]
> Have you used [the "dependsOn" technique](https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/views-perf.html) to improve performance, avoiding view recomputations (and zero-effect diffing) for parts that do not change?
Yes, i am using it alot. But the problem is in states which are not part of model (i.e. scroll position)

> If any parts of your view are static then you should also definitely ensure they are computed statically and the precise same values (same object identity) are used on each computation of the view

I tried a technique to store viewelement by key into some store (mailbox) and later retrieve it, but it looks like no "hardlink" on real view is persisted due to nature of ViewRef

**Comment by vshapenko** [comment]
> > ensure that scroll position stays the same as the previous one
> 
> Hmmm in this case the scroll position should be part of the app model, updated as the scrolling is done at an appropriate rate, with a very carefully written view function to avoid recomputation.

I tried some tricks to calculate scroll position, but they are not accurate, sadly, cause they operate in terms of "currently visible items", not in terms "i see n items and 0.3 of one more item".

So, the above suggestions is the reason i created this issue, because on mobile platforms afaik is common to keep view state for some time (reasonable). And, @dsyme , if  i summoned you here, coul i please you take a look at  https://github.com/fsprojects/Fabulous/issues/518 ? It looks like quite a big problem for fabulous-style view management. I stopped there at trying to break myself thorugh autogenerated Xamarin.Forms.Core.fs hoping to understand what is going wrong.

**Comment by dsyme** [comment]
#518 is very long, I haven't been following it, which specific comment should I look at?  I may not be able to help

I do agree that some kind of mechanism to persist view elements longer may be useful, especially when there is view state in those elements not easily reconstructable via exterrnally settable properties (e.g. view state for scrolling).  It would be sort of a backdoor - for example the scroll position would not be preserved on application restart.

I think all that's required would be a special "id"-like property that would serve as a key into a hash table mapping to underlying XF elements and then reusing those on re-creation when id's match.  There are potential risks to this approach - the creation logic assumes that elements are being created from defaults. It would certainly address some performance issues too when page switching.

**Comment by vshapenko** [comment]
> #518 is very long, I haven't been following it, which specific comment should I look at? I may not be able to help
I am agree that it is very long
> 
> I do agree that some kind of mechanism to persist view elements longer may be useful, especially when there is view state in those elements not easily reconstructable via exterrnally settable properties (e.g. view state for scrolling). It would be sort of a backdoor - for example the scroll position would not be preserved on application restart.
> 
> I think all that's required would be a special "id"-like property that would serve as a key into a hash table mapping to underlying XF elements and then reusing those on re-creation when id's match. There are potential risks to this approach - the creation logic assumes that elements are being created from defaults. It would certainly address some performance issues too when page switching.

**Comment by vshapenko** [comment]
> I think all that's required would be a special "id"-like property that would serve as a key into a hash table mapping to underlying XF elements and then reusing those on re-creation when id's match. There are potential risks to this approach - the creation logic assumes that elements are being created from defaults. It would certainly address some performance issues too when page switching.

I understand such risks, but there are cases when it is needed (for example, in messengers, when you go to chat page and back, it would be good to store chat state with scrolling etc.)

**Comment by TimLariviere** [comment]
>@TimLariviere Do you have an idea of the right approach for this?

For this specific case, the idea is that the scroll position is tied to the current session more than the page itself.
So I think it's achievable by storing the value inside a higher model (app root model maybe?) and go from there.

The way I would have done it is by using the `Scrolled` event of the `ScrollView` and store the scroll position in the global state.
Then upon reentering the chat page, you could use the `ScrollTo` attribute using the previously stored scroll position.

```fsharp
type Model = { InitialScrollPosition: int option }
type Msg = Scrolled of float
type ExternalMsg= NoOp | SaveScrollPosition of int

let init (initialScrollPosition: int option) =
    { InitialScrollPosition = initialScrollPosition }, Cmd.none, ExternalMsg.NoOp

let update msg model =
    match msg with
    | Scrolled y -> { InitialScrollPosition = None }, Cmd.none, (ExternalMsg.SaveScrollPosition y)

let view model dispatch =
    View.ContentPage(
        View.ScrollView(
            scrolled=(fun args -> dispatch (Scrolled args.ScrollY)),
            ?scrollTo=
                match model.InitialScrollPosition with
                | None -> None
                | Some position -> Some ((0.0, position), NotAnimated)
```

Alternatively a mutable static store for those kinds of session tied values could be a valid option in my opinion, because I don't think it makes much sense to store those in the model.
```fsharp
UserSession.Values["LastScrollPosition"] <- y
```

**Comment by vshapenko** [comment]
@TimLariviere, does this work for ListView?

**Comment by TimLariviere** [comment]
`ScrollTo` exists on ListView but we don't expose it.

`Scrolled` is not exposed by Xamarin.Forms though.
Apparently it's possible to create it by writing a custom control (https://criticalhittech.com/2017/11/14/observing-listview-scrolling-in-xamarin-forms/)

**Comment by vshapenko** [comment]
> `ScrollTo` exists on ListView but we don't expose it.
> 
> `Scrolled` is not exposed by Xamarin.Forms though.
> Apparently it's possible to create it by writing a custom control (https://criticalhittech.com/2017/11/14/observing-listview-scrolling-in-xamarin-forms/)

Thanks alot, i will give it a try

**Comment by vshapenko** [comment]
Played a little with a sample provided by @TimLariviere.  Looks like reasonable path to store first visible item index. Unforunately, ListView does not have methods to scroll to position, not the item. So, looks like i have a kind of restriction here implementing behavior of my app.
And another question: I used a techinque described here https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/views-extending.html to "inject" my list view instead of standard one, but now my items do not draw(red labels ListElementData instead). What am i doing wrong?

**Comment by TimLariviere** [comment]
@vshapenko Ah yes, we created our own ListView to support ViewElement as items.
You need to inherit from Fabulous.XamarinForms.CustomListView

Then
```fsharp
let update (prevOpt: ViewElement voption) (source: ViewElement) (target: YourLisView) =
    ViewBuilders.UpdateListView(prevOpt, source, target)
```
should be enough

**Comment by vshapenko** [comment]
@TimLariviere and one more question. Is there a way to extend current ListView with new properties? I want to add callback with some scroll info to put it into model. In my current solution i use ViewRef<ListView>, but it looks strange. So, i would like to add a new key to ListView, i.e. scrolled:int->unit, for example

**Comment by TimLariviere** [comment]
@vshapenko Yes you can.
It's a little verbose, but you can follow what I did in FabulousContacts
https://github.com/TimLariviere/FabulousContacts/blob/master/FabulousContacts/Controls/BorderedEntry.fs

**Comment by vshapenko** [comment]
> @vshapenko Yes you can.
> It's a little verbose, but you can follow what I did in FabulousContacts
> https://github.com/TimLariviere/FabulousContacts/blob/master/FabulousContacts/Controls/BorderedEntry.fs

Ah, i see. I plan to expose event callback int->unit to make my scroll postition to be stored in cache

**Comment by vshapenko** [comment]
Ok, i have managed to got a scroll position in my listview. Next step is to inject it into model without passing Ref. @TimLariviere  is where a recommended method to do such a thing, i.e. adding a method callback : 'T->unit in View constructor?

**Comment by TimLariviere** [comment]
@vshapenko Adding the method callback to the View constructor is good.
That's what we do for all events in Fabulous.

Just one thing though:
We store the EventHandler in the ViewElement, not the callback itself. (to be able to unsubscribe from the events in case the callback changes)
You will need to create the EventHandler before setting the attribute key.
Then in the update function, you can call directly `source.UpdateEvent(prevOpt, YourAttributeKey, target.YourEvent)`.

```fsharp
let MyControlScrolledAttributeKey = AttributeKey<_> "MyControl_Scrolled"

type Fabulous.XamarinForms.View with
    static member MyControl(?scrolled: ScrolledEventArgs -> unit) =
        let attribCount = match scrolled with None -> 0 | Some _ -> 1
        let attribs = View.BuildElement(attribCount)

        match scrolled with
        | None -> ()
        | Some callback ->
            let eventHandler = System.EventHandler<ScrolledEventArgs>(fun _sender args -> callback args)
            attribs.Add(MyControlScrolledAttributeKey, eventHandler)

        let update (prevOpt: ViewElement voption) (source: ViewElement) (target: MyControl) =
            ViewBuilders.UpdateElement(prevOpt, source, target)
            source.UpdateEvent(prevOpt, MyControlScrolledAttributeKey, target.Scrolled)

        ViewElement.Create(MyControl, update, attribs)
```

Could be either `System.EventHandler` or `System.EventHandler<T>` based on what you need

**Comment by TimLariviere** [comment]
@vshapenko Have you managed to get everything working?

**Comment by vshapenko** [comment]
> @vshapenko Have you managed to get everything working?

To be honest,  i had no the time to try approach you described above. I think, i will try it at Monday. Basing on your sample, it looks like i should repeat ListView extension and add one single param to it to be able write things like MyListView (scrollPosition=....,items=...)

**Comment by TimLariviere** [comment]
Closing stalled issue
