### ISSUE TITLE
No Resource found

### ISSUE THREAD

**Issue by nanodesu88** [fsprojects/Fabulous#533]
I am trying do use css file for styles, but Xamarin can't find it.
What do i do wrong? 
![Image of Error](https://downloader.disk.yandex.ru/preview/518097ba7c66629ae7e86110efaa4bfecd8288f886b0b2c47545409b209135c5/5d41dbf4/I9T2fll9irImOygTxHRs5WbeVuIeThWMi94Zr4lwuCjtwNHHLUoKMNz7XqKsxuQSiT9XszDiWLmb6cEaOAlDVQ%3D%3D?uid=0&filename=2019-07-31_16-16-54.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&owner_uid=0&tknv=v2&size=2048x2048)

**Comment by TimLariviere** [comment]
@nanodesu88 Loading embedded resources is not the most intuitive thing. :)
The expected name is not the file itself `main.css` but its full name inside the assembly `SqueakyApp2.main.css`

(For example, if you had put the css file under a directory, the path would have been `SqueakyApp2.DirectoryName.main.css`)

See https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/css/#c

**Comment by TimLariviere** [comment]
@nanodesu88 Is your problem fixed?

**Comment by nanodesu88** [comment]
Yes
