### ISSUE TITLE
How to use the View.Entry

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fabulous#537]
I’m trying to work with the View.Entry so when a user edit text box then clicks off something happens (validation maybe?).  I can see there are 2 events I could hook into:

> Completed - Occurs when the user finalizes the text in an entry with the return key.
> TextChanged - Event that is raised when the text in this Entry element is changed.

But trying both I can’t seem to get anywhere.

The Completed event only fires of the user clicks the return key (the tick on android), not if you click off the entry box or click any other buttons which is how a lot of uses (including myself) interact with the app.

The TextChanged essentially fires on every key press which creates a message, updates the model, redraws the Entry and loses focus.

With both events you don’t (reliably) know when the users has finished editing the text box so I'm not sure what to do?

**Comment by davidtme** [comment]
This is what happens with the AllControls sample:

![update](https://user-images.githubusercontent.com/1804141/62367123-9bdc5580-b520-11e9-93d8-2935e007e2d6.gif)

**Comment by Happypig375** [comment]
Usually `TextChanged` is used. The view is updated every key press.

**Comment by Happypig375** [comment]
Fabulous has view diffing so the same Entry is reused.

**Comment by TimLariviere** [comment]
@davidtme You can use the `Unfocused` event for detecting when the user is deselecting the entry field

**Comment by davidtme** [comment]
I had my entry inside a custom `Stateful` control.  After fixing this the `View.Entry` got reused and no longer lose focus so I could use the `TextChanged` event
