### ISSUE TITLE
Fabulous watcher

### ISSUE THREAD

**Issue by Pipsy100** [fsprojects/Fabulous#539]
How do I start up the Fabulous watcher in VS 2019?

**Comment by TimLariviere** [comment]
@Pipsy100 The documentation should contain everything you need:
https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/tools.html

**Comment by Pipsy100** [comment]
Thanks. Tim. I followed the instructions. Now I am getting this message i cannot resolve. "fscd: ERROR SENDING TO WEBHOOK: "System.Exception: error converting  rhs of .ctor" System. Exception: NYI: extension of generic type, needs FCS Support

**Comment by SergejDK** [comment]
@Pipsy100 
Sorry for the late response. 

So which OS are you using?
What exactly steps did you do to get the exception?
VS Version would be nice too.

Or did you already solve the problem ?

Did you try to run as administrator?

**Comment by TimLariviere** [comment]
Closing since the original question has been answered.

**Comment by Pipsy100** [comment]
Hello Timothé.

I do not have any experience with Fabulous

Cloned the repo. Build the project. And send Calculator.Droid as startup.

But these are my errors.

Do I forget something?

Gr.

Willem

Van: Timothé Larivière <notifications@github.com>
Verzonden: zaterdag 3 augustus 2019 12:36
Aan: fsprojects/Fabulous <Fabulous@noreply.github.com>
CC: Pipsy100 <w_hoogland@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [fsprojects/Fabulous] Fabulous watcher (#539)


@Pipsy100<https://github.com/Pipsy100> The documentation should contain everything you need:
https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/tools.html

**Comment by TimLariviere** [comment]
Hi @Pipsy100 

This issue is closed.

Could you please open a new issue restating your problem?
Also I don't see any errors attached to your message, could you please add them in the new issue so we can help?
