### ISSUE TITLE
Fabulous.XamarinForms.SkiaSharp does not handle gestures on Android

### ISSUE THREAD

**Issue by cannorin** [fsprojects/Fabulous#541]
Assume we have this:
```fsharp
  View.SKCanvasView(
    paintSurface = drawImpl model,
    invalidate = model.redrawRequested,
    gestureRecognizers = [
      View.TapGestureRecognizer(fun () -> dispatch CanvasTapped)
    ]
  )
```

On iOS build tapping the canvas correctly fires `CanvasTapped`, while nothing happens on Android build.

Confirmed on Fabulous 0.41.0.

**Comment by TimLariviere** [comment]
@cannorin I don't reproduce with only the given code.
I think there is a crash happening somewhere else preventing Fabulous to finish refreshing the UI.

Could you check the application output log when you tap the canvas?
There should be a stack trace in there if something happened.

**Comment by cannorin** [comment]
Ah, I figured out it was because I added an effect to handle long press gesture via `created`. I removed it and it got working. Since iOS is working with both gestore recognizer and effect added, it seems it's a bug in Xamarin itself rather than Fabulous.Forms. Sorry 😅
