### ISSUE TITLE
Fabulous 0.41.1 LiveUpdate is not working

### ISSUE THREAD

**Issue by poborin** [fsprojects/Fabulous#546]
By creating a new project from scratch and following the [LiveUpdate instructions](https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/tools.html) I have uncommented 
```fsharp
do runner.EnableLiveUpdate()
```
and got the following error:
```
The field, constructor or member 'EnableLiveUpdate' is not defined.
```

**Comment by TimLariviere** [comment]
Thanks for the report!
Indeed, the docs are missing one step.

You need to add `open Fabulous.XamarinForms.LiveUpdate` at the top of the file to reference the extension method `EnableLiveUpdate`.

**Comment by poborin** [comment]
Perfect! That works

**Comment by poborin** [comment]
created a pull request #547
