### ISSUE TITLE
A Visual Studio template in addition to CLI

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#555]
Just like Avalonia.
https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaforVisualStudio&ssr=false#qna
![image](https://user-images.githubusercontent.com/19922066/63704801-67796200-c85e-11e9-9f7a-2883db201431.png)

**Comment by TimLariviere** [comment]
As nice as it sounds, in my opinion it is actually not something we should do.

Unfortunately Visual Studio Templates are extremely limited.
There's 2 ways to write templates for Visual Studio, the simplest is by wrapping our solution in a zip file, the other is to write an actual VSIX (Visual Studio extension) which is definitely way harder.

The zip file way is almost useless when you want to go beyond "copy-paste-rename".
- You have to use specific tokens in the file names and source code to make sure it will be replaced at creation time (like the project name).
- These tokens break your code, making it not testable (like our templates)
-  There is no built-in tools to help automating the conversion of a valid project into a VS template zip.
- You can't do conditionals (so we can't reuse our flags --WPF --GTK)

The wizard way (VSIX) would be better to handle that.
But still, it would be redeveloping `dotnet new` for not much added value...

The best solution for us would be that Visual Studio finally support `dotnet new` out of the box.
Jetbrains Rider already supports that to some extent.

And with the upcoming of .NET 5, I would dare to say that Visual Studio will most likely add that feature in a not too distant future.

**Comment by Happypig375** [comment]
The corresponding issue https://github.com/dotnet/templating/issues/481 has been open for 2 years with no updates.

**Comment by TimLariviere** [comment]
Seems like Visual Studio will finally display .NET Core templates in its New Project dialog in 16.8
https://twitter.com/timheuer/status/1298716833852166144?s=20
