### ISSUE TITLE
Upgrade Xamrin.Forms to 4.2.0.709249

### ISSUE THREAD

**Issue by SergejDK** [fsprojects/Fabulous#556]
We can update XF from 4.1 to 4.2.

It was released 9 days ago so I think we can do the upgrade. [https://www.nuget.org/packages/Xamarin.Forms/](https://www.nuget.org/packages/Xamarin.Forms/)

**Comment by vshapenko** [comment]
Unfortunately, bug with NRE was not included in this update.

**Comment by Happypig375** [comment]
NRE fix is for 4.3.0
