### ISSUE TITLE
XamarinForms extensions have no ref and shell properties

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#560]
See:
https://github.com/fsprojects/Fabulous/blob/13b2a75521589629da7eaf0585741232f62e450c/Fabulous.XamarinForms/extensions/OxyPlot/OxyPlot.fs#L20-L26
There are no `ref` nor `shell*` properties.
Need to update the Generator to regenerate properties for extensions when base views are updated.

**Comment by SergejDK** [comment]
I think the extensions are currently written per hand and not auto generated. 
I think this will be different in the future.

**Comment by TimLariviere** [comment]
@SergejDK is right.
The extensions are currently written by hand, so we can easily fix this issue.

**Comment by SergejDK** [comment]
I will fix this the next days.
