### ISSUE TITLE
Missing Xamarin.Forms.Core.fs

### ISSUE THREAD

**Issue by shawn-martin** [fsprojects/Fabulous#568]
I feel like I'm missing something really simple or dumb here, but...
In the Fabulous.XamarinForms project there is a reference to Xamarin.Forms.Core.fs, but it does not exist.

Should the reference be deleted, or the file be added, or is there something else that I'm missing?

**Comment by TimLariviere** [comment]
Hi @shawn-martin 
It's completely normal, the `Xamarin.Forms.Core.fs` file is generated as part of the FAKE build process.

See: https://github.com/fsprojects/Fabulous/blob/master/DEVGUIDE.md#dev-notes---building
