### ISSUE TITLE
Convert Xamarin.Forms.VisualElement to Fabulous.ViewElement

### ISSUE THREAD

**Issue by luizhj** [fsprojects/Fabulous#572]
Hello

I'm trying to use FFImageLoad on Fabulous.
To show a image we have to use ChacedImage from FFImageLoad, it derives from VisualElement of Xamarin.Forms.
But Fabulous need Viewelement.

There is a simple way to convert a VisualElement from Xamarin Forms to ViewElement of fabulous?

open FFImageLoading.Forms
open Xamarin.Forms

let source = FileImageSource()
source.File <- "some_image.jpg"

let image = CachedImage()
image.Source <- source

let iamge2 = image :> Xamarin.Forms.VisualElement
let image3 = iamge2 :> Fabulous.ViewElement
// The type VisualElement is not compatible with type ViewElement

**Comment by TimLariviere** [comment]
Hi @luizhj 

`VisualElement` is not convertible to `ViewElement`.

`ViewElement` is actually a virtual representation of your view, and it contains instruction to instantiate the real control when needed (or update it if necessary). That's where your `CachedImage` will be created.

To be able to use your `FFImageLoading.Forms.CachedImage`, you will need to write an extension for it. (see https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/views-extending.html)

This will be something like that
```fsharp
[<AutoOpen>]
module MyViewExtensions =

    open Fabulous
    open Fabulous.XamarinForms
    open FFImageLoading.Forms

    let SourceAttribKey = AttributeKey<string> "CachedImage_Source"

    // Fully-qualified name to avoid extending by mistake
    // another View class (like Xamarin.Forms.View)
    type Fabulous.XamarinForms.View with
        /// Describes a CachedImage in the view
        /// The inline keyword is important for performance
        static member inline CachedImage(?source: string) =

            // Count the number of attributes
            let attribCount = 0
            let attribCount = match source with Some _ -> attribCount + 1 | None -> attribCount
            let attribs = AttributesBuilder(attribCount)

            // Add our own attributes.
            match source with None -> () | Some v -> attribs.Add (SourceAttribKey, v)

            // The creation method
            let create () = new CachedImage()

            // The incremental update method
            let update (prev: ViewElement voption) (source: ViewElement) (target: CachedImage) =
                let updateSource (target: CachedImage) (v: string) =
                    let imageSource = FileImageSource()
                    imageSource.File <- v
                    target.Source <- imageSource

                source.UpdatePrimitive (prev, target, SourceAttribKey, (fun target -> target.Source), updateSource)

            // Create a ViewElement with the instruction to create and update a CachedImage
            ViewElement.Create<CachedImage>(create, update, attribs)
```

You will then be able to write

```fsharp
View.CachedImage(source = "some_image.jpg")
```

**Comment by luizhj** [comment]
Thank you very much!
It worked with some litlle modifications

`

[<AutoOpen>]
module MyViewExtensions =

    open Fabulous
    open Fabulous.XamarinForms
    open FFImageLoading.Forms
    open Xamarin.Forms

    let SourceAttribKey = AttributeKey<_> "CachedImage_Source"

    // Fully-qualified name to avoid extending by mistake
    // another View class (like Xamarin.Forms.View)
    type Fabulous.XamarinForms.View with
        /// Describes a CachedImage in the view
        /// The inline keyword is important for performance
        static member inline CachedImage(?source: string) =

            // Count the number of attributes
            let attribCount = 0
            let attribCount = match source with Some _ -> attribCount + 1 | None -> attribCount
            let attribs = AttributesBuilder(attribCount)

            // Add our own attributes.
            match source with None -> () | Some v -> attribs.Add (SourceAttribKey, v)

            // The creation method
            let create () = new CachedImage()

            // The incremental update method
            let update (prev: ViewElement voption) (curr: ViewElement) (target: CachedImage) =
                
                let updateSource (v: string) =
                    let imageSource = FileImageSource()
                    imageSource.File <- v
                    imageSource

                curr.UpdatePrimitive (prev, target, SourceAttribKey, (fun target v -> target.Source <- updateSource v ))

            // Create a ViewElement with the instruction to create and update a CachedImage
            ViewElement.Create<CachedImage>(create, update, attribs)
`

And the use:
`  View.CachedImage(source =  "file.jpg")`
