### ISSUE TITLE
0.43.0

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#573]
I really need the bugfixes in XF4.3.0. However, I can't update because of a name change in XF: `ListItemsLayout` -> `LinearItemsLayout`. I can't compile XF4.3 with Fabulous because of this. Please update ASAP!

**Comment by kierepka** [comment]
This same error 
FSC : error FS0193: The module/namespace 'Xamarin.Forms' from compilation unit 'Xamarin.Forms.Core' did not contain the namespace, module or type 'ListItemsLayout'

**Comment by TimLariviere** [comment]
Just published it to NuGet.org
Will be available in a few moments.
