### ISSUE TITLE
Fabulous.dll --> Fabulous.Core.dll?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#579]
(Am just getting back to the codebase, with a view to continuing to prototype FSharp.Data.Adaptive support)

Am wondering if the renaming `Fabulous.dll` --> `Fabulous.Core.dll` would make sense?

**Comment by dsyme** [comment]
Also what's the difference between Fabulous.XamarinForms and Fabulous.XamarinForms.Core? Thanks

![image](https://user-images.githubusercontent.com/7204669/67863996-d6a05a80-fb1c-11e9-8f51-665cacf0f1d3.png)

**Comment by TimLariviere** [comment]
>Am wondering if the renaming Fabulous.dll --> Fabulous.Core.dll would make sense?

Have you a specific idea in mind? What do you think it would provide?

With #481, I renamed each project to match the name of its corresponding "product" (`Fabulous.Core` => `Fabulous`) to make it easier for people when searching on NuGet.

Other packages named `Fabulous.*` are an extension of sorts for Fabulous.

>Also what's the difference between Fabulous.XamarinForms and Fabulous.XamarinForms.Core? 

It's also related to #481 

`Fabulous.XamarinForms` is the only package we ship to NuGet.
`Fabulous.XamarinForms.Core` is just an internal build dependency, we build it (with all the custom controls) before running the Generator.

`Fabulous.XamarinForms.Core` will be read by `Fabulous.XamarinForms.Generator` to generate `Xamarin.Forms.Core.fs` which will be compiled into `Fabulous.XamarinForms`

Initially I wanted to use a private project reference between `Fabulous.XamarinForms.Core` and `Fabulous.XamarinForms` and ship a single package with the 2 dlls.

But `dotnet pack` doesn't support that.
Instead it will add a dependency to a package we don't ship to NuGet, preventing to install `Fabulous.XamarinForms`.

So I managed to achieve what I wanted but using linked files.

Typically, one would only need to change the F# code inside the Core project, and not touch `Fabulous.XamarinForms` except for the JSON file.

**Comment by dsyme** [comment]
> > Am wondering if the renaming Fabulous.dll --> Fabulous.Core.dll would make sense?

> Have you a specific idea in mind? What do you think it would provide?

I think it's rare to name a DLL like `Fabulous.dll` unless it's the "whole technology".  In this case `Fabulous.dll` is really just the core root DLL of the Fabulous stack, so Fabulous.Core.dll just looks right to me I guess.

BTW the context is I'm going over the stack trialling adding support for FSharp.Data.Adaptive, branch is here https://github.com/fsprojects/Fabulous/compare/master...dsyme:adaptive?expand=1. As one example, when specifying attributes an adaptive value is used instead of a normal value https://github.com/fsprojects/Fabulous/compare/master...dsyme:adaptive?expand=1#diff-f2f6cc7fee2ef493cc0b56b6b0e117c0R239.

Very much wet paint, will keep you informed, will also push some minor cleanup changes through in a separate PR.  Of course none of this would actually go into Fabulous unless we convincingly demonstrate better performance in UI update. at realistic data levels

> > Also what's the difference between Fabulous.XamarinForms and Fabulous.XamarinForms.Core?

> It's also related to #481

Sorry for wasting your time with this one, I should have searched the code, I understand now :-)

**Comment by dsyme** [comment]
Closing this - I don't really ind what the DLL is called, I guess Fabulous.Core.dll feels right to me but I'll leave it to you  :)
