### ISSUE TITLE
Xamarin.Essentials OpenAsync not reliably working on iOS

### ISSUE THREAD

**Issue by KijongHan** [fsprojects/Fabulous#583]
It looks like OpenAsync doesn't work (the dialog window shows up showing apps able to open the file, but once you select an app nothing happens) if the update function runs after Launcher.OpenAsync has finished execution.

I've created a minimal repro of the issue here: https://github.com/KijongHan/Fabulous_OpenPdfIssue 

- Not Working Scenario
Enable the timer and tap on the open button, then select an app to open the pdf. Nothing should happen

- Working Scenario
Tap on the open button, then select an app to open the pdf. It expectedly opens the app with the pdf content loaded

**Comment by TimLariviere** [comment]
Thanks for the report and the repro.
Will take a look soon

**Comment by SergejDK** [comment]
@TimLariviere this seems to be a specific essentials problem. We should check this before trying to fix this in fabulous.

**Comment by KijongHan** [comment]
If anybody else encounters this issue, we were able to resolve the issue by invoking the Launcher.OpenAsync function call directly within the function delegate passed into the command argument, as opposed to routing the call to the Launcher.OpenAsync function via fabulous messaging/update loop

**Comment by TimLariviere** [comment]
Closing since this is a Xamarin.Essentials issue.
Please check if a new version of Essentials fixes the problem, otherwise use the workaround provided above.
