### ISSUE TITLE
Missing View.TimePicker after upgrading to Fabulous 0.50-alpha.7

### ISSUE THREAD

**Issue by KijongHan** [fsprojects/Fabulous#586]
Missing Fabulous.XamarinForms.View.TimePicker after upgrading the Fabulous and Fabulous.XamarinForms libraries to 0.50-alpha.7. Xamarin.Forms library is the latest stable release as of writing this issue (4.3.0.908675)

**Comment by TimLariviere** [comment]
Thanks! This will be fixed in the 0.50 release.
In 0.50.0-alpha.7, it's currently named `CustomTimePicker`.
