### ISSUE TITLE
System.InvalidCastException on completed event of View.Entry and View.Editor with 0.50 + Android

### ISSUE THREAD

**Issue by TheDevKnight** [fsprojects/Fabulous#588]
Hi, 

i switch the compled event to the textChanged event in my app. But before i do that i get the following Exception 

```
System.InvalidCastException
  Nachricht = Specified cast is not valid.
```

when i enter some chars into the Editor or Entry and change the focus (touch to other place on gui). It take 1-2 seconds before the excepion apears in Visual Studio 2019.
 
These SampleApp works yesterday with version 0.43

    type Model = { 
        Text: string
        Count: int}

    type Msg = 
        | UpdateText of string

    let initModel = { Text= ""; Count = 0 }

    let init () = initModel, Cmd.none

    let update msg model =
        match msg with
        | UpdateText text -> { model with Text = text; Count = model.Count + 1 }, Cmd.none

    let view (model: Model) dispatch =
        View.ContentPage(
            content = View.StackLayout(padding = Thickness 20.0, verticalOptions = LayoutOptions.Center,
                children = [ 
                    View.Label(text = "Count: " + model.Count.ToString())
                    View.Editor(text = model.Text, 
                        //textChanged = (fun args -> dispatch (UpdateText args.NewTextValue)) Works
                        completed = (fun text -> dispatch (UpdateText text))
                        )
                    View.Entry(text = model.Text, 
                        //textChanged = (fun args -> dispatch (UpdateText args.NewTextValue)) Works
                        completed = (fun text -> dispatch (UpdateText text))
                        )
                ]))

Any ideas?

The Knight

**Comment by TimLariviere** [comment]
My bad. I was too quick on copy-paste...
I will release a hotfix for this one.
