### ISSUE TITLE
View.ListView throwing System.InvalidCastException on render

### ISSUE THREAD

**Issue by KijongHan** [fsprojects/Fabulous#595]
Example call to render ListView that throws System.InvalidCastException:

`View.ListView(
                items = [ View.Label() ]
            )`

**Comment by TimLariviere** [comment]
@KijongHan This is a recent breaking change in v0.50.
ListView no longer accepts direct elements. Instead you need to pass a Cell like you would in Xamarin.Forms itself.
https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/migration-guide-to-0.50.html#listview-and-listviewgrouped-now-require-items-and-group-headers-to-be-cells-adds-support-for-textcell--imagecell--switchcell--entrycell--viewcell

**Comment by KijongHan** [comment]
Thanks Tim! The renders are working fine now, but setting the selectedItem parameter (to Some int) throws the same exception

**Comment by TimLariviere** [comment]
Oh. I will take a look as soon as I can.
