### ISSUE TITLE
LaunchScreen.storyboard in iOS project from template cannot be opened

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#599]
![image](https://user-images.githubusercontent.com/19922066/68539653-9dd86f00-03c1-11ea-9d4a-4992eae0dc3b.png)

**Comment by Happypig375** [comment]
The equivalent file in F# iOS template fails with the same error. However, the version from C# successfully opens. Seems that the C# version is up-to-date.

**Comment by TimLariviere** [comment]
@Happypig375 Could you open a PR with this new file from the C# template please? Thanks

**Comment by Happypig375** [comment]
After copying the C# version to an F# iOS project, a similar error popped up. Seems like an F# tooling issue 😐

**Comment by TimLariviere** [comment]
Closing since this is not an issue with Fabulous.
