### ISSUE TITLE
Fabulous.FFImageSource is not ready for production yet

### ISSUE THREAD

**Issue by vshapenko** [fsprojects/Fabulous#600]
I have an alternate realization, may be would be worth to take some code from it:

[FFImageLoading.zip](https://github.com/fsprojects/Fabulous/files/3830309/FFImageLoading.zip)

At least transformations and cache keys are missing in current implementation

**Comment by Happypig375** [comment]
`Option.count` and `Option.map` are not used in the current implementation because they are not inlined when called. Thus, they carry a performance hit.

**Comment by vshapenko** [comment]
> `Option.count` and `Option.map` are not used in the current implementation because they are not inlined when called. Thus, they carry a performance hit.

I am talking about transfomations mostly and other properties, which should be deffer from ViewElement

**Comment by marto83** [comment]
Thanks @vshapenko. I've got your wrapper working. I tried with Fabulous.FFImageSource but it doesn't support `transformations`.

**Comment by luizhj** [comment]
transformations only work with another nuget package.
That's why it doesn't works with the actual template.

https://www.nuget.org/packages/Xamarin.FFImageLoading.Transformations/

**Comment by TimLariviere** [comment]
Closing stalled issue
