### ISSUE TITLE
Strange ListView issue

### ISSUE THREAD

**Issue by vshapenko** [fsprojects/Fabulous#602]
Upgrading to fabulous 0.50.3, i am getting strange behavior of listview - looks like view cells are not recycling.

**Comment by SergejDK** [comment]
Do you have an example code and the error message? This would help a lot to investigate on this

**Comment by vshapenko** [comment]
@SergejDK  there is no errors, just on scrolling i see wrong item containers, and it looks weird

**Comment by vshapenko** [comment]
@SergejDK  Here is sample
[CounterApp.zip](https://github.com/fsprojects/Fabulous/files/3869763/CounterApp.zip)

**Comment by SergejDK** [comment]
@vshapenko 
what do you mean with "that jumps"? 
The color is swapped or that the scrolling is more like a jump ?

**Comment by vshapenko** [comment]
@SergejDK  Color and position is swapped. I think this means ViewCell recycling

**Comment by SergejDK** [comment]
If it was caused by the Recycling part then it should be fixed by now. 
Tested it on Android and iOS and your example was working as expected. 

Could you test this with the latest version?

**Comment by vshapenko** [comment]
@SergejDK  checked it, works ok on latest version. Looks like isuue is fixed, thank you.
