### ISSUE TITLE
AutomationId cannot be set for ViewCell

### ISSUE THREAD

**Issue by vshapenko** [fsprojects/Fabulous#603]
Throws "AutomationId may only be set one time". Is such behavior default?

**Comment by vshapenko** [comment]
> Throws "AutomationId may only be set one time"

**Comment by SergejDK** [comment]
@vshapenko 
it seems like XF guarded the automationid https://github.com/xamarin/Xamarin.Forms/issues/6157

**Comment by TimLariviere** [comment]
@SergejDK Normally Fabulous.XamarinForms should not reuse a control if the AutomationId changed. But for some reasons, it's not applying in this case.
https://github.com/fsprojects/Fabulous/blob/6700d6f4143e88a60b3e1125159c9c3da795797a/Fabulous.XamarinForms/src/Fabulous.XamarinForms.Core/ViewHelpers.fs#L41

**Comment by SergejDK** [comment]
@TimLariviere 
Somehow the functions `canReuseAutomationId` and `canReuseView` for ViewCell are not getting called...

**Comment by SergejDK** [comment]
@vshapenko 
could you show how your listview and items in it looks like?

**Comment by TimLariviere** [comment]
@SergejDK Where are you getting this behavior? I tried to reproduce with only the code you shown but there's no exception.

**Comment by SergejDK** [comment]
@TimLariviere 
I changed the AllControls part of `TabbedPage 2` with the ListView to the code I mentioned before.

**Comment by SergejDK** [comment]
Was taking another look into this.
It seems to be working fine on iOS but Android complains. Tried different Emulators and real devices but the issue remains. Release and Debug shows the same results.

**Comment by SergejDK** [comment]
@TimLariviere 
I think I got the problem. 

Currently we have 
https://github.com/fsprojects/Fabulous/blob/a0754429261ff15cdc1aae2adfda63ce18e75632/Fabulous.XamarinForms/src/Fabulous.XamarinForms.Core/CustomControls.fs#L143

Removing the `ListViewCachingStrategy.RecycleElement` solves this problem. RecycleElement overrides the context of one cell and that's why I got the issue. 

What do you think @TimLariviere ?

**Comment by vshapenko** [comment]
@SergejDK , @TimLariviere  do you have any progress on this issue?
