### ISSUE TITLE
scrollTo for CollectionView/ListView/CarouselView

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#607]
`scrollTo` is exposed for ScrollView but not for CollectionView/ListView.

**Comment by Happypig375** [comment]
Also CarouselView.

**Comment by vshapenko** [comment]
@Happypig375  there is a parameter named scrolled

**Comment by Happypig375** [comment]
No. ScrollView has both.

**Comment by Happypig375** [comment]
@TimLariviere Since Fabulous' CollectionView/CarouselView is based on ViewElements, it would make more sense to use the overload that takes item indexes to maintain scroll position in the event of view recreation.
