### ISSUE TITLE
Update SkiaSharp to 1.68.1

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#619]
I believe SkiaSharp now supports WPF in its Xamarin.Forms binding, we should update I think.

I'm double checking this now

**Comment by dsyme** [comment]
Note to self: I found I needed to add this to AllControls.WPF.fsproj
```
      <PreferredNativeSkiaSharp>x64</PreferredNativeSkiaSharp>
      <PlatformTarget>x64</PlatformTarget>
```

**Comment by TimLariviere** [comment]
Closing since we did the update and the SkiaSharp extension works in AllControls.WPFe
