### ISSUE TITLE
Add extension examples to AllControlls 

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#620]
For the sake of testing and adding a bit more coverage I guess we should add the following to AllControls

* [ ] Skia
* [ ] Maps
* [ ] VideoManager
* [ ] FFImage
* [ ] OxyPlot

**Comment by vshapenko** [comment]
FFImage is not ready for production, see [https://github.com/fsprojects/Fabulous/issues/600](url)

**Comment by Happypig375** [comment]
@vshapenko Is your comment really related to this issue? AllControls sample is obviously internal-only.

**Comment by vshapenko** [comment]
> @vshapenko Is your comment really related to this issue? AllControls sample is obviously internal-only. And please test your link before posting.

There is no reason to make a sample of FFImage without transformations, because, imho, it is one of most important features of this library

**Comment by Happypig375** [comment]
>And please test your link before posting.

Apparently this sentence got ignored.

**Comment by vshapenko** [comment]
> > And please test your link before posting.
> 
> Apparently this sentence got ignored.

Sorry, missed it, Thanks for correction.

**Comment by TimLariviere** [comment]
Done in https://github.com/fsprojects/Fabulous/pull/621
