### ISSUE TITLE
View.Grid content not updating correctly

### ISSUE THREAD

**Issue by KijongHan** [fsprojects/Fabulous#622]
It looks like when trying to conditionally render a new View.Grid element inside a Page content, if the previous content was a View.Grid element with a different layout the old View.Grid layout scheme (coldefs, rowdefs) remain

Repro of the above issue:
https://github.com/KijongHan/Fabulous_ViewGridRerenderIssue

**Comment by vshapenko** [comment]
I confirm such behavior.

**Comment by TimLariviere** [comment]
Thanks. I'm looking into it.
