### ISSUE TITLE
Xamarin.Shell Command to detect switch of ShellSection

### ISSUE THREAD

**Issue by TheDevKnight** [fsprojects/Fabulous#631]
HI,

i have an andriod app with 3 shellSections and i will now split them into separate moduls (see https://www.youtube.com/watch?v=-Oc4xJivY78). I also added a CurentPage value to my model. 

But i cannot find the right property/event to detect the current switch of the section to dispatch my message. 

`let view (model: Model) dispatch =
    
        View.Shell(
                flyoutBehavior = FlyoutBehavior.Disabled,
                items = [
                    View.ShellItem(
                        items = [

                            View.ShellSection(
                                title = "Rollladen", 
                                icon =  Image.Path "rollladen.png",
                                //clicked = (fun () -> dispatch (NavigateTo Rollladen)),
                                //command = (fun () -> dispatch (NavigateTo Rollladen)),
                                items = [...
                                ])

                            View.ShellSection(
                                title = "Lichtschalter",
                                icon =  Image.Path "lichtschalter.png",
                                //clicked = (fun () -> dispatch (NavigateTo Lichtschalter)),
                                //command = (fun () -> dispatch (NavigateTo Lichtschalter)),
                                items = [...

`
 
Is this feature supported in Fabulous?

Regards

**Comment by TimLariviere** [comment]
The way Shell works in Xamarin.Forms is slightly different.
There's no event or command that can notify you a section has been selected.

Instead, you can use `ShellContent` and its `content` property in which you can call your submodule `view` function. This view will only be instantiated when the user will really navigate to it.
https://github.com/fsprojects/Fabulous/blob/4ea1dd1fd268272478d357fc140357f19d9ec332/Fabulous.XamarinForms/samples/Shell/Fabimals/Fabimals/App.fs#L198-L203

The Fabimals sample can help you see how scaling works with Shell.
https://github.com/fsprojects/Fabulous/tree/master/Fabulous.XamarinForms/samples/Shell/Fabimals/Fabimals

**Comment by TheDevKnight** [comment]
@TimLariviere  thank you for the hint, i will check it out! :)
