### ISSUE TITLE
How to access  MarkerClicked and InfoWindowClicked of Pin Class?

### ISSUE THREAD

**Issue by madeinquant** [fsprojects/Fabulous#638]
According to the "https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Maps/Pin.cs". There are two event MarkerClicked and InfoWindowClicked of Pin Class(Clicked has been obsoleted). No `ref` can be found and try to access the event with the helper `With` unsuccessfully. Please feel free to comment.

```
let jpnPins =
    jpnDatas
    |> List.map (fun (_, a, _, _, b, c) -> View.Pin(Position(b, c), label = a, pinType = PinType.Place)).With(Clicked=(fun () -> dispatch PinClicked))
    |> Some
```

**Comment by TimLariviere** [comment]
The Pin extension is currently ultra basic. So they're not accessible, unfortunately...
Though if you need them, it's fairly simple to add support for those (and more).

https://github.com/fsprojects/Fabulous/blob/9b3e09866c7d75e041bc9354cd1c8f3990d4a9f7/Fabulous.XamarinForms/extensions/Maps/Xamarin.Forms.Maps.fs#L86

https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/views-extending.html

**Comment by madeinquant** [comment]
Over the last few days, I tried to extend the Pin Class, make them (MarkerClicked and InfoWindowClicked) accessible. Pins can be created on the map successfully, however, ref is None.
Both MarkerClicked and InfoWindowClicked are inaccessible.

 ```
static member CustomPin(?position: Position, ?label: string, ?pinType: PinType, ?address: string
                                // inherited attributes common to all views
                                ,?ref) =
...

    // Unbox the ViewRef
    let viewRef = match ref with None -> None | Some(ref: ViewRef<Pin>) -> Some ref.Unbox
...

 let attribs = 
                ViewBuilders.BuildView(attribCount, ?ref=viewRef)
...

let setPinCallBack(a:string, b:float, c:float) = 
         let pinRef = ViewRef<Pin>()
         let pin = View.CustPin(Position(b, c), label = a, pinType = PinType.Place, ref = pinRef)  created=(fun l -> l.MarkerClicked.Add(PinClickedAsync)))
         //pinRef.MarkerClicked.Add(PinClickedAsync)
         match pinRef.TryValue with
         | None -> ()
         | Some obj -> //obj is inaccessible, no error was found and the pinRef is None. 
                let mypin = obj 
                mypin.MarkerClicked.Add(PinClickedAsync)
         pin


```
