### ISSUE TITLE
Xamarin.Forms Slider with minimum value of 1.0 results in crash

### ISSUE THREAD

**Issue by abrevinci** [fsprojects/Fabulous#639]
This particular value is exactly equal to the previous/default maximum value and we need to set the maximum value first, just like we do when the minimum is larger than the previous/default maximum.
Otherwise this triggers a validation error in Xamarin.Forms which requires Minimum to be strictly less than maximum.

**Comment by TimLariviere** [comment]
Thanks for the report!

Guess we just need to make `>=` to fix the issue.
https://github.com/fsprojects/Fabulous/blob/46001549c5c1424a30ba0fc414d280e1ef4541de/Fabulous.XamarinForms/src/Fabulous.XamarinForms.Core/ViewUpdaters.fs#L398-L403

**Comment by Happypig375** [comment]
@TimLariviere You pointed to the code for Stepper, not Slider.

**Comment by abrevinci** [comment]
I created a PR for this fix.

**Comment by TimLariviere** [comment]
>@TimLariviere You pointed to the code for Stepper, not Slider.

Oh yes. Sorry
But isn't it the same problem?

**Comment by Happypig375** [comment]
@abrevinci Does stepper have the same problem?

**Comment by TimLariviere** [comment]
Fixed by #640 and #643
