### ISSUE TITLE
SwipeView/IndicatorView 

### ISSUE THREAD

**Issue by Liminiens** [fsprojects/Fabulous#641]
In 4.4 Xamarin added support for [SwipeVIew](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/swipeview) and [IndicatorView](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/indicatorview). It would be nice to have them in Fabulous.

**Comment by TimLariviere** [comment]
We will work on Xamarin.Forms 4.4 support as soon as possible.
That will include those 2 new controls. :)
