### ISSUE TITLE
Is it possible to use Fabulous generator to generate separate view elements based on Xamarin.Android and Xamarin.Ios?

### ISSUE THREAD

**Issue by vshapenko** [fsprojects/Fabulous#642]
Hello! I have an idea to generate separate view elements based on native controls for each platform, and then use them as ViewElement in main app cycle. Is it possible in theory?

**Comment by TimLariviere** [comment]
Fabulous.CodeGen is about creating alternatives to Fabulous.XamarinForms.
So yes, you can wrap native controls and use them in a "dynamic views" way (see [Fabulous.iOS](https://github.com/TimLariviere/Fabulous.iOS)).

But, if you mean it as [native views embedding](https://docs.microsoft.com/xamarin/xamarin-forms/platform/native-views/code) (native controls inside Xamarin.Forms), then it's possible but not easy to achieve.

Nothing prevents you from overriding the last step of Fabulous.CodeGen that generates the F# code and add the `.ToView()` extension method used for native embedding.
But it would first require that you map controls from all the platforms that you want.
Hell of a job. :) (it took us a lot of time to support almost all XF controls)

Alternatively, you can write extensions for Fabulous.XamarinForms and use native controls + `.ToView()` inside.

**Comment by vshapenko** [comment]
@TimLariviere  thank you for sample! I will take a look and may have time and resources to achieve this task

**Comment by TimLariviere** [comment]
Closing since the original question has been answered
