### ISSUE TITLE
View.CollectionView does not have scrollToRequested

### ISSUE THREAD

**Issue by vshapenko** [fsprojects/Fabulous#646]
Hello! Looks like CollectionView.ScrollToRequested event is missing in fabulous implementation.  It might be useful in scenarios when we should determine that user tries to scroll  on top/end of the list. For example, when i am trying to  scroll above top, i should show additional action panel on ui (my case)

**Comment by TimLariviere** [comment]
Actually, just noticed this event is considered "For internal use only" on ListView in XF, so Fabulous shouldn't surface it.

Also this event doesn't let you know when a user scrolls, but when you call `control.ScrollTo(x, y)` yourself.
So I don't think it has any added value...

I'm closing this issue as `Won't fix`.
Though we can reopen it if there's a valid use case.
