### ISSUE TITLE
Incorrect Frame reuse

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#647]
```fs
// Fabulous.XamarinForms v0.51
module App = 

    let init () = false, Cmd.none

    let update () model = not model, Cmd.none

    let view model dispatch =
        View.ContentPage(
            View.StackLayout [
                View.Button("Switch", dispatch)
                if model then View.Frame(View.BoxView(Color.Blue)) else View.Frame(hasShadow=true)
            ]
          )

    // Note, this declaration is needed if you enable LiveUpdate
    let program = Program.mkProgram init update view
```
Expected: The blue color appears and disappears during clicks.
Actual:
![visualized](https://i.imgur.com/y4ke6Ze.gif)

**Comment by SergejDK** [comment]
For anyone who will take a look into this. This is still an issue in VS 2019 version 16.10 and Fabulous 1.1.0. This seems to only occur on UWP. WPF and others are working fine - maybe this is a general bug with UWP but this needs to be investigated.
