### ISSUE TITLE
Should ContentPage sizeAllocated be raised every single update?

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#648]
This is the current behavior as of Fabulous.XamarinForms 0.51. An alternative would be to only raise this event when the width or height actually change.

**Comment by TimLariviere** [comment]
As this is behaviour of Xamarin.Forms and not specific to Fabulous, I don't think we will do custom logic ourselves.
v2 now allows to very easily add custom modifiers, so you could write your own implementation of sizeAllocated that triggers following the rules you need.
