### ISSUE TITLE
Problem with Xamarin.Forms 4.4

### ISSUE THREAD

**Issue by sameertotey** [fsprojects/Fabulous#649]
The SqueakyApp sample stops working form Xamarin.iOS project after upgrading the nuget to use Xamarin.Forms (4.4)

`/Users/sameer/temp/FSharp/SqueakyApp/SqueakyApp.iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.Void Xamarin.Forms.ItemsView::set_ItemSizingStrategy(Xamarin.Forms.ItemSizingStrategy)', referenced from the method 'System.Void Fabulous.XamarinForms.ViewBuilders::UpdateItemsView(Microsoft.FSharp.Core.FSharpValueOption`1<Fabulous.ViewElement>,Fabulous.ViewElement,Xamarin.Forms.ItemsView)' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (SqueakyApp.iOS)`

**Comment by SergejDK** [comment]
For bigger updates (4.3 -> 4.4) we have to update FabulousXamarinForms so we can support the latest features. 
This is currently in progress: #644  and the support should be there with the next release of Fabulous.

**Comment by TimLariviere** [comment]
Closing it since #644 already tracks XF 4.4 update.
