### ISSUE TITLE
Template project fails static analysis

### ISSUE THREAD

**Issue by mlooney** [fsprojects/Fabulous#651]
An untouched template project, generated with `dotnet new fabulous-xf-app -n name`  generates code that will build, but fails code analysis in the VS editor.

The call to AppName.App is underlined in red as `"Error: The type 'App is not defined in 'AppName'"`, though there is no red mark in the gutter for some reason.

This is clearly incorrect, as the project will build and run.  Interestingly, MainActivity.fs is also flagged exactly the same way.

Adding `open MyAppName` has no effect.

Clearly not a huge issue, but as a new user, it's driving me nuts that it's there, and I can't figure out why (obviously App is defined in that namespace).  

I've updated & restored all packages, and even moved my VS install up to the preview channel (no change)

(macOS, VS 8.4 preview 2653, fab 0.51.0)

**Comment by TimLariviere** [comment]
Not sure we can do something about it.

**Comment by TimLariviere** [comment]
The code Fabulous generates is correct, so IDEs shouldn't display such errors.
If it still happens, please contact the people responsible for your IDE.
