### ISSUE TITLE
View.Frame GridColumn is not defined

### ISSUE THREAD

**Issue by metatron-the-chronicler** [fsprojects/Fabulous#656]
```View.Frame(content = someContent).GridRow(i).GridColumn(y))```
In Fabulous 0.42 this general sort of construct worked as expected.  However in 0.51 trying to build code with this construct says that GridColumn/GridRow is not defined.  Is there a new way to set the grid row and column indexes or do I need to use a different control?

**Comment by SergejDK** [comment]
@metatron-the-chronicler 
I think this is missed in the migration guide.

`GridRow` is now `Row`
and
`GridColumn` is now `Column`

Hope that helps!

**Comment by metatron-the-chronicler** [comment]
@SergejDK that did it. Thank you.
