### ISSUE TITLE
 Bindings for third-party libraries

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/Fabulous#658]
Is there a common registry of bindings for third-party libraries?
In particular, I'm interested in ZXing.

Or what is the simplest way of integrating a third-party component without developing a binding?

**Comment by TimLariviere** [comment]
Currently, you can find all the public bindings in the `extensions` folder in this repository. We don't have one for ZXing yet.

https://github.com/fsprojects/Fabulous/tree/master/Fabulous.XamarinForms/extensions

They each have their corresponding NuGet packages.

>what is the simplest way of integrating a third-party component without developing a binding?

There's no official way for now to do this, but if you don't actually need to update the control once it has been created, you can do this:
```fsharp
ViewElement.Create(
    // Create function
    (fun () -> 
        new ZXingBarcodeImageView(
            WidthRequest = 300.,
            HeightRequest = 100.,
            BarcodeValue = 1337,
            BarcodeFormat = "CODE_39"
        )
    ),

    // Update function. Can be ignored since we don't use attributes
   (fun _ _ _ -> ()),

    // Attributes list
   AttributesBuilder(0)
)
```
