### ISSUE TITLE
Add docs on making web requests

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#66]
Add simple docs on making web requests akin to this:

https://github.com/SAFE-Stack/SAFE-BookStore/blob/master/src/Client/pages/Login.fs#L57

**Comment by SergejDK** [comment]
Is this still needed?

If yes - should there be used a lib e.g. [http://fsharp.github.io/FSharp.Data/library/Http.html](http://fsharp.github.io/FSharp.Data/library/Http.html)  or any other approach?
