### ISSUE TITLE
Any RelativeLayout sample with RelativeToView?

### ISSUE THREAD

**Issue by vshapenko** [fsprojects/Fabulous#680]
Hello all! I am in need of RelativeLayout sample with constraint related to view.  Fabulous samples have only RelatedToParent cases, which is interesting, but not so useful in my case.

**Comment by Happypig375** [comment]
Use a viewRef?

**Comment by vshapenko** [comment]
> Use a viewRef?

Unfortunately, viewref is usually available on the next layout pass. And i think, that is not a case for view ref
