### ISSUE TITLE
Static View submodel sample

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/Fabulous#683]
I don't understand I it function of `Binding.subModel` and how binding names correspond.
Is there any sample available?
For parameter binding it would be very helpful too

**Comment by xperiandri** [comment]
@dsyme do you have any samples of that?

**Comment by Yakimych** [comment]
@xperiandri I was just looking into this yesterday, and managed to make it work: https://github.com/Yakimych/relogify-fabulous-app/blob/static-view/src/Relogify/Relogify.fs#L51
I don't really understand the `init`-parameter type signature, so I opened an issue regarding it: https://github.com/fsprojects/Fabulous/issues/693. Calling the `init`-function of the subPage and ignoring both the input parameter, as well as the result does seem to work, however.

Another tricky part I've encountered was in the XAML file itself - the binding path looks like this: `Text="{Binding [AboutPageModel].[SomeText]}"`: https://github.com/Yakimych/relogify-fabulous-app/blob/static-view/src/Relogify/AboutPage.xaml#L11

**Comment by xperiandri** [comment]
Yesterday I was managed to run https://github.com/xperiandri/Elmish.Uno so currently, I'm in favor of trying to go with Uno

**Comment by xperiandri** [comment]
Thanks for the sample! Could you fix it to be fully functional?

**Comment by Yakimych** [comment]
Elmish.Uno looks interesting - can it be used for iOS/Android app development?
The `static-view` branch is fully functional, at least when it comes to `AboutPage.xaml` - it binds to the text and re-renders correctly after the `SetSomeText` gets dispatched.

What I didn't manage to get to work is the MVU loop inside a page shown via `shell.Navigation.PushModalAsync`, but maybe you don't need this scenario in your case?

**Comment by xperiandri** [comment]
``` F#
module Biblioteko.Mobile.Program

open System
open Elmish
open Elmish.Uno

type Model =
  { Count: int
    StepSize: int }

let init () =
  { Count = 0
    StepSize = 1 }

type Msg =
  | Increment
  | Decrement
  | SetStepSize of int
  | Reset

let update msg m =
  match msg with
  | Increment -> { m with Count = m.Count + m.StepSize }
  | Decrement -> { m with Count = m.Count - m.StepSize }
  | SetStepSize x -> { m with StepSize = x }
  | Reset -> init ()

let bindings model dispatch =
  [
    "CounterValue" |> Binding.oneWay (fun m -> m.Count)
    "Increment" |> Binding.cmd (fun m -> Increment)
    "Decrement" |> Binding.cmd (fun m -> Decrement)
    "StepSize" |> Binding.twoWay
      (fun m -> float m.StepSize)
      (fun v m -> int v |> SetStepSize)
    "Reset" |> Binding.cmdIf (fun _ -> Reset) (fun m -> m <> init ())
  ]

let createApp windowBuilder =
    let program = Program.mkSimple init update bindings
    program |> Program.createApp ElmConfig.Default windowBuilder
```
``` F#
namespace Frebo.Biblioteko.Mobile

open System

open Android.App
open Com.Nostra13.Universalimageloader.Core
open Windows.UI.Xaml
open Windows.UI.Xaml.Media

open Elmish.Uno

open Microsoft.AppCenter
open Microsoft.AppCenter.Analytics
open Microsoft.AppCenter.Crashes

open Biblioteko.Mobile
open Biblioteko.Mobile.Constants

[<Application(
#if DEBUG
    Debuggable = true,
#else
    Debuggable = false,
#endif
    Label = "@string/ApplicationName",
    LargeHeap = true,
    HardwareAccelerated = true,
    Theme = "@style/AppTheme"
    )>]
type MainApplication private (windowBuilder, javaReference, transer) =
    inherit NativeApplication (Program.createApp windowBuilder, javaReference, transer)

    new (javaReference, transer) as this =
        let builder () = new MainPage() :> FrameworkElement
        new MainApplication (builder, javaReference, transer)
        then
            do this.ConfigureUniversalImageLoader()

    member private this.ConfigureUniversalImageLoader () =
        // Create global configuration and initialize ImageLoader with this config
        let config =
            (new ImageLoaderConfiguration
                .Builder(NativeApplication.Context))
                .Build();
        ImageLoader.Instance.Init (config)
        ImageSource.DefaultImageLoader <-
            ImageSource.ImageLoaderHandler(fun ct uri imageView targetSize ->  ImageLoader.Instance.LoadImageAsync (ct, uri, imageView, targetSize))
        ()
```

This is how it looks:
C# Views projects reference shared project (because XAML must be rewritten to C# by Uno code generation package). Then F# Android and F# iOS apps reference views projects

![image](https://user-images.githubusercontent.com/2365592/76700576-87b92300-66c1-11ea-8edc-31ec494cce4d.png)
