### ISSUE TITLE
Fab Breaks after upgrade to .52

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/Fabulous#688]
I upgraded my fabulous version to 0.52
I had to change the namespace to Fabulous.XamarinForms
Now all of my existing code is broken with multiple errors:

<img width="1165" alt="Screen Shot 2020-03-05 at 9 50 18 PM" src="https://user-images.githubusercontent.com/1394644/76045536-5e62ff00-5f2b-11ea-8a85-906edd5fceb5.png">

Is there an upgrade page somewhere?

**Comment by Happypig375** [comment]
Those are part of the v0.50 changes:
https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/migration-guide-to-0.50.html

**Comment by jamessdixon** [comment]
Thanks - that page solves most of my errors.  However, I am getting errors on positioning of items in a grid: .GridRow(1) for example:

<img width="531" alt="Screen Shot 2020-03-07 at 1 06 18 AM" src="https://user-images.githubusercontent.com/1394644/76138026-7c0a9400-6011-11ea-9394-725041e25da9.png">

and Image.FadeTo:
<img width="576" alt="Screen Shot 2020-03-07 at 1 16 15 AM" src="https://user-images.githubusercontent.com/1394644/76138030-87f65600-6011-11ea-9b2a-c1b3605e8095.png">

Is there a guide for those?

**Comment by jamessdixon** [comment]
Never mind, I found th answer.  I'll update the docs:
"GridColumn" becomes "Grid"
and Image now conflicts with Xamarin.Forms.Image so I needed to fully qualify the parameter
