### ISSUE TITLE
Gestures receiving parameters and forwarding to a function

### ISSUE THREAD

**Issue by luizhj** [fsprojects/Fabulous#692]
Can I pass some object to the function inside of a gesture just like this?
`<StackLayout.GestureRecognizers>
<TapGestureRecognizer Command="{Binding Source={x:Reference View}, Path=BindingContext.ItemTappedCommand}" CommandParameter="{Binding .}" />
</StackLayout.GestureRecognizers>`

[TapGesture in XAML](https://gist.github.com/luizhj/6849d738b02af842aa3f29b76acc288e)

gesture in Fabulous
`gestureRecognizers =[ View.TapGestureRecognizer(command=(fun (param) -> dispatch PushPage ("ServantDetail",param))) ]`

**Comment by vshapenko** [comment]
You may use closure: let param = ....  fun()->dispatch PushPage param

**Comment by luizhj** [comment]
I don't express myself correctly. 
How do I get a parameter to pass to a Gesture?
When I stop it in breakpoint at that function it doesn't have any param of any kind.

Just have the dispach.
![image](https://user-images.githubusercontent.com/16191002/76445417-23861e80-63a4-11ea-9da6-014ef1a40cea.png)


![image](https://user-images.githubusercontent.com/16191002/76445376-11a47b80-63a4-11ea-9667-ed8d7e0d1948.png)

**Comment by TimLariviere** [comment]
@luizhj Since the function is redeclared along with the controls at each update, you have access to the latest `model` and can use it as your parameter.

```xaml
<StackLayout>
    <StackLayout.GestureRecognizers>
        <TapGestureRecognizer Command="{Binding Source={x:Reference View}, Path=BindingContext.ItemTappedCommand}"
                              CommandParameter="{Binding .}" />
    </StackLayout.GestureRecognizers>
</StackLayout>
```
is equivalent to
```fs
type Model =
    { SomeData: string }

type Msg = PushPage of string

let view model dispatch =
    View.StackLayout(
        gestureRecognizers = [
            View.TapGestureRecognizer(
                command = fun () -> dispatch (PushPage model.SomeData)
            )
        ]
    )

```

**Comment by luizhj** [comment]
I've tried to something like that, but I'm starting to learn f# and Fabulous, everything is new for me =]

What is the right way of do this to identify the item tapped from a flexlayout?
The flex layout items is one list of StackLayout with a Image.

![image](https://user-images.githubusercontent.com/16191002/76446680-2c77ef80-63a6-11ea-8825-00c39b224295.png)

***[Entire FS App](https://gist.github.com/luizhj/cce26a732823448b6281e453774d7f45)

**Comment by TimLariviere** [comment]
If you set the GestureRecognizer on the FlexLayout, you won't be able to identify a specific child because you're really listening for the FlexLayout.

What you can do though is to set one TapGestureRecognizer on each children.

```fs
children = [
    for i in servants do
        yield (servantImageFrame i.Image)
            .GestureRecognizers([
                View.TapGestureRecognizer(
                    command = fun () -> dispatch (PushPage i.Name) // here, you have access to the current item
                )
            ])
]
```

Better yet would be to pass your "page parameter" as a parameter to your `servantImageFrame` function so you can directly use `gestureRecognizers` in that function.

**Comment by luizhj** [comment]
Thank you @TimLariviere, it worked!

I changed the pushpage message
`  type Msg = 
        | PushPage of (string * Servant)`

the update 
` | PushPage (page,servant) -> { model with PageStack = Some page :: model.PageStack;Servant = servant}, Cmd.none`

and the gesture
` for i in servants do
                                                                                              yield (servantImage i.Image).GestureRecognizers([
                                                                                                             View.TapGestureRecognizer(
                                                                                                                 command = fun () -> dispatch (PushPage ("ServantDetail",i)) // here, you have access to the current item
                                                                                                             )
                                                                                                         ])`
