### ISSUE TITLE
Add native main menu to MacOS template

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#696]
Related to #312 and #252 

The following code should be added to the MacOS template to enable creating a main menu with Xamarin.Forms.

`AppDelegate.fs`
```fs
member this.SetupNativeMenu() =
    let menuBar = new NSMenu()
    let appMenuItem = new NSMenuItem()
    menuBar.AddItem(appMenuItem)
    
    let appMenu = new NSMenu()
    appMenuItem.Submenu <- appMenu
    
    let quitMenuItem = new NSMenuItem(sprintf "Quit %s" window.Title, "q", EventHandler(fun _ _ ->
        NSApplication.SharedApplication.Terminate(menuBar)
    ))
    appMenu.AddItem(quitMenuItem)
        
    NSApplication.SharedApplication.MainMenu <- menuBar
```

The `quitMenuItem` is optional. The rest is not, or it will crash!

Then, this method needs to be called during `DidFinishLaunching`
```fs
    override this.DidFinishLaunching(notification: NSNotification) =
        Forms.Init()
        
        this.SetupNativeMenu()
        this.LoadApplication(AppWithMenu.App())

        base.DidFinishLaunching(notification)
```

**Comment by TimLariviere** [comment]
Explanation:

**A little reminder about `Xamarin.Forms.Menu`:**

Menu is used in multiple ways in Xamarin.Forms (Main menu, Shell, etc.), so we provided access to it via `View.Menu()`.
But `View.Menu()` can't be used to declare a main menu since the menu is linked to the application instance and not to a UI page/control.
This means a main menu will always have to be created through classic code, outside Fabulous MVU loop.

**Creating a main menu in a Fabulous application:**

Finally found how `Xamarin.Forms.Menu` is supposed to be used to create menu items in the main toolbar on MacOS.
It was a lot of guessing work since there's no proper documentation about it on Xamarin.Forms.

So, here's the steps:

1. `NSApplication.SharedApplication.MainMenu` should be initialized in the MacOS project

Xamarin.Forms expects it to be initialized before the end of `DidFinishLoading`, otherwise it will consider there is no menu.

This is usually done in the `Main.storyboard` file, but in Fabulous.XamarinForms' template, we don't have this file.
So the file need to be created, or we can add the following code in `AppDelegate.fs`
```fs
member this.SetupNativeMenu() =
    let menuBar = new NSMenu()
    let appMenuItem = new NSMenuItem()
    menuBar.AddItem(appMenuItem)
    
    let appMenu = new NSMenu()
    appMenuItem.Submenu <- appMenu
    
    let quitMenuItem = new NSMenuItem(sprintf "Quit %s" window.Title, "q", EventHandler(fun _ _ ->
        NSApplication.SharedApplication.Terminate(menuBar)
    ))
    appMenu.AddItem(quitMenuItem)
        
    NSApplication.SharedApplication.MainMenu <- menuBar
```

The `quitMenuItem` is optional. The rest is not, or it will crash!

Then, this method can be called during `DidFinishLoading`
```fs
    override this.DidFinishLaunching(notification: NSNotification) =
        Forms.Init()
        
        this.SetupNativeMenu()
        this.LoadApplication(AppWithMenu.App())

        base.DidFinishLaunching(notification)
```

2. In the `App.fs` file in the shared project, you can declare your main menu when setting up the `Program` instance

You will need to call `Xamarin.Forms.Element.SetMenu(application, menu)` where `application` is your Application instance and `menu` is a `Xamarin.Forms.Menu`.

This menu is required to have at least one submenu.
The first submenu will always be the one named after the application.

You can then add actions to the menu items through the `Command` property.
If you want to dispatch messages to the Fabulous MVU loop, you can do so by using the program instance.

```fs
type App () as app = 
    inherit Application ()

    // We isolate the program to be able to dispatch messages from the main menu
    let program = Program.mkProgram ...
    
    do
        let menu = Menu()
        
        let appMenu = Menu()
        appMenu.Items.Add(MenuItem(Text = "Click me"))
        menu.Add(appMenu)
        
        let fileMenu = Menu(Text = "File")
        fileMenu.Items.Add(MenuItem(Text = "New", Command = Command(fun () -> program.Dispatch SomeMsg)))
        fileMenu.Items.Add(MenuItem(Text = "Open"))
        menu.Add(fileMenu)
        
        Element.SetMenu(app, menu)

    let runner = program |> XamarinFormsProgram.run app
```

cc @realvictorprm

**Comment by x-ji** [comment]
Thanks. This example is definitely helpful.

**Comment by jwosty** [comment]
@TimLariviere that's a phenomenal writeup there. Thank you very much.
