### ISSUE TITLE
How to attach an event handler to a NSStatusBarButton?

### ISSUE THREAD

**Issue by x-ji** [fsprojects/Fabulous#704]
Sorry if this question doesn't make sense or if this is not the right place to post it. I've just started exploring this project and Xamarin. I'm trying to create an app which has a menu bar icon on MacOS. There is [a sample project written in C#](https://github.com/krdmllr/CrossTrayApplicationSample), and I'm trying to port it to F# first. But I'm stuck at [this point](https://github.com/krdmllr/CrossTrayApplicationSample/blob/b559709a1773ced44d16a415938bedda36eecb63/CrossTrayApplicationSample.MacOS/AppDelegate.cs#L32):

```csharp
            // Listen to touches on the status bar item
            _statusBarItem.Button.SendActionOn( NSEventType.OtherMouseUp);
            _statusBarItem.Button.Activated += StatusItemActivated;
```

From https://github.com/fsprojects/Fabulous/issues/696, I am able to see how to create a `MenuItem` with an event handler already attached, e.g.

```fsharp
        let quitMenuItem = new NSMenuItem(sprintf "Quit %s" window.Title, "q", EventHandler(fun _ _ -> NSApplication.SharedApplication.Terminate(menuBar)
        ))
```

My idea is to create a new `NSStatusBarButton` and assign it to `statusBarItem.Button`, seeing that we don't seem to normally attach an event handler post-construction in Fabulous. But I checked the constructors of `NSStatusBarButton`, and they don't seem to take any event handler as an argument.

How am I able to achieve an effect equivalent to the two lines in the C# project? Essentially I need the menu bar to do something when clicked.

**Comment by TimLariviere** [comment]
Events in F# are a bit more complex to use than C#, but the idea is the same.
Instead of doing `object.EventName += delegate`, you can write `object.EventName.Add(function)`.
See https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/events#handling-events

Here, this should become something like that:

```fsharp
let statusBarItem = NSStatusBar.SystemStatusBar.CreateStatusItem(NSStatusItemLength.Variable)
statusBarItem.Button.SendActionOn(NSEventType.OtherMouseUp)
statusBarItem.Button.Activated.Add(fun (sender, e) -> ...)
```

**Comment by x-ji** [comment]
Thanks for the help, seems to be a matter of looking up how event handlers for such apps are handled in F#. I just couldn't find similar examples in Fabulous itself.

The code that worked (no `sender` argument seems to be required for the event handler):

```fsharp
        let StatusItemActivatedHandler (evArgs) =
            match NSApplication.SharedApplication.CurrentEvent.Type with
            | NSEventType.RightMouseDown -> statusBarItem.PopUpStatusItemMenu(menuBarMenu)
            | _ -> ()
            
        statusBarItem.Button.SendActionOn(NSEventType.OtherMouseUp) |> ignore
        statusBarItem.Button.Activated.Add(StatusItemActivatedHandler)
```
