### ISSUE TITLE
Logo, getting started links for fsharp.org

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#710]
I've just been over https://fsharp.org cleaning things up.  Thousands of people visit that site each year and click on the [Use F# for Mobile Apps](https://fsharp.org/use/mobile-apps/) getting started and ["F# for Mobile Apps Guide"](https://fsharp.org/guides/apps-and-games/) links.  

Fabulous is now listed as one of the options there, however

* The getting started material likely needs to be improved in Fabulous docs. We currently link to https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/index.html#getting-started.

* There is no thumb logo for Fabulous.

It would be great to improve these things

**Comment by dsyme** [comment]
Maybe we could rip off the FsBolero home page and adapt :-) https://fsbolero.io/

It's very good!

**Comment by TimLariviere** [comment]
>Maybe we could rip off the FsBolero home page and adapt :-)

Yes. Fabulous needs a proper website now.
Kinda hard to read the docs currently.
I know @SergejDK wanted to improve that.

>There is no thumb logo for Fabulous.

Tried my hand at a logo for Fabulous and Fabulous.XamarinForms.
Let me know what you think.

- Small icons
<img src="https://user-images.githubusercontent.com/6429007/79755321-3a138400-8319-11ea-8e38-435995c07c22.png" height="50" />
<img src="https://user-images.githubusercontent.com/6429007/79755327-3aac1a80-8319-11ea-9428-b14fa486806b.png" height="50" />

- Banners
![Fabulous Hero Banner](https://user-images.githubusercontent.com/6429007/79755318-397aed80-8319-11ea-985a-bb32265feb34.png)

![Fabulous.XamarinForms Hero Banner](https://user-images.githubusercontent.com/6429007/79755326-3a138400-8319-11ea-9b80-0198978dc960.png)

**Comment by dsyme** [comment]
Somehow the logo doesn't feel quite right - something more with the circular flow feel of redux/react feels more right?

(I don't think Fabulous XF needs a logo - the "brand" can just be Fabulous - marketing should be really really simple - we sell something as technical as Azure with pictures of blue skies and fluffy clouds)

**Comment by TimLariviere** [comment]
Another idea with 3 components getting mixed in another bigger one:
- Small icon
<img src="https://user-images.githubusercontent.com/6429007/79781972-a359be00-833e-11ea-8a10-150065c75856.png" height="50" />

- Banner
<img src="https://user-images.githubusercontent.com/6429007/79781969-a2c12780-833e-11ea-9f6a-5c500f7ce741.png" />

**Comment by dsyme** [comment]
I like that. Maybe a few too many elements (implies complexity?).  But the swirl is great

**Comment by TimLariviere** [comment]
Removed the inner circle and enlarged the hole inside the swirl.

<img src="https://user-images.githubusercontent.com/6429007/79787830-e8ceb900-8347-11ea-9931-97c95492ca4e.png" height="200" />

**Comment by TimLariviere** [comment]
<img src="https://user-images.githubusercontent.com/6429007/79793640-36035880-8351-11ea-8a79-362bf408286a.png" height="200" />

I do like it the same way than before, just without the inner orange circle.

**Comment by SergejDK** [comment]
> Yes. Fabulous needs a proper website now.
Kinda hard to read the docs currently.
I know @SergejDK wanted to improve that.

Yes I am slowly getting back to work on OSS-Stuff.

----

@TimLariviere it looks pretty much like chrome, don't you think?

**Comment by TimLariviere** [comment]
>it looks pretty much like chrome, don't you think?

Hmm, indeed. There are some similarities to Chromium...

Maybe it feels less similar if I keep the orange circle, but with a slim swirl?
<img src="https://user-images.githubusercontent.com/6429007/79797765-22a7bb80-8358-11ea-9b7f-5d4f0e69b3b7.png" height="200" />

**Comment by dsyme** [comment]
Can we get the logo on the home page ? https://fsprojects.github.io/Fabulous/

**Comment by Lleutch** [comment]
Hello everyone, 
It seems that I might arrive a little bit too late to propose a design (though I am not a designer myself :D ). 

I will however post the idea I had for the logo (inspired from redux), it's just a .png.
The intent here is not to change the decision that has already been taken with the current choice, I just wanted to share the idea that I have.
![Logo (1)](https://user-images.githubusercontent.com/15655919/80412068-8c324780-88cd-11ea-9da2-502fac72655b.png)

Thank you for your time

**Comment by dsyme** [comment]
That is a very nice logo!

**Comment by plombeer31** [comment]
2 ideas - 
first is just old logo rework
second is a bit more creative (I love it) 

![Artboard – 7](https://user-images.githubusercontent.com/19537764/83058784-9331ae80-a061-11ea-98f3-b0c4d9e1c051.png)
![Artboard – 8](https://user-images.githubusercontent.com/19537764/83058791-9462db80-a061-11ea-83b1-fef35bf79bc0.png)

**Comment by TimLariviere** [comment]
I've started to use Fornax to build a website for Fabulous.
Still super rough: https://fabulousfx.github.io/

**Comment by dsyme** [comment]
It's looking good as a first start

* The logo is not showing for me

* I always think the rule "do not make promises, show what's real today" is best.  So remove "MAUI
(Coming 2021)"

* The layout makes it feel a bit like a web technology.  I think you need 3 or more visuals of desktop and mobile apps to say this this is an app technology
