### ISSUE TITLE
Fabulous XamarinForms Span.ForegroundColor attribute was (accidentally?) removed in 0.53

### ISSUE THREAD

**Issue by franko-franicevich** [fsprojects/Fabulous#717]
Hey folks, I uncovered this while investigating why our project broken with a linking error when upgrading to `fab 0-52`. I tracked it down to fabulous-simple-element, and raised an issue with full details here:

https://github.com/Zaid-Ajaj/fabulous-simple-elements/issues/20

Obviously you're asking 'But what does it have to do with The Fab?' 
It does appear that the issue is actually with fabulous rather than simple-elements. The full details are in the above referenced issue, but I'll summarise here:

`simple-elements references fabulous span.foregroundColor, which has been (I think) incorrectly *removed* from fabulous.xamarinForms 0.53`

https://github.com/fsprojects/Fabulous/blame/v0.52/Fabulous.XamarinForms/src/Fabulous.XamarinForms/Xamarin.Forms.Core.json
https://github.com/fsprojects/Fabulous/blame/v0.53/Fabulous.XamarinForms/src/Fabulous.XamarinForms/Xamarin.Forms.Core.json

(see line 385 in 0.52:  The following appears in .52 for the description of `span`, and not in .53:

```
385
          "source": "ForegroundColor"
386
        },).
```

Checking the official microsoft xamarinForms docs, `'Span` still has foregroundColor listed as a property, so it appears that this removal from fabulous is likely accidental, rather than intentional.

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.span.foregroundcolor?view=xamarin-forms

I'd issue a pull request adding those couple lines back to `Fabulous.XamarinForms/src/Fabulous.XamarinForms/Xamarin.Forms.Core.json`, but I honestly don't know if that's sufficient, or if that file is generated elsewhere, or if there's other things to change; so I'll have to (unfortunately) leave that to the experts.

Please let me know how I can help further.

**Comment by TimLariviere** [comment]
Hi @franko-franicevich

We removed it because it has been marked obsolete for some times in Xamarin.Forms, and replaced with TextColor.
In Xamarin.Forms, IntelliSense stopped showing it (it's only there to allow migration from Xamarin.Forms 3.1).
https://github.com/xamarin/Xamarin.Forms/blob/5eec0f5936d8c8a19ae6c9c4c3387b141f3acfe6/Xamarin.Forms.Core/Span.cs#L53-L55

I would recommend updating fabulous-simple-elements instead.

**Comment by franko-franicevich** [comment]
Thanks for the quick response and the clarification, Tim!

I've submitted a fix already to fabulous-simple-elements, so we're good on that front. 

I'll close this issue.
