### ISSUE TITLE
ListView - reordering items with drag n drop

### ISSUE THREAD

**Issue by katatunix** [fsprojects/Fabulous#722]
It is suprised that this common and important feature still has not been officially supported by Xamarin Forms: https://github.com/xamarin/Xamarin.Forms/issues/4676

Is there any chance that Fabulous will support this feature? It is fine if iOS and Android are targeted.

**Comment by TimLariviere** [comment]
@katatunix Unfortunately, Fabulous is not meant to add features missing in Xamarin.Forms.
We only provide wrappers over existing GUI frameworks like Xamarin.Forms so they can be used in a functional way with the MVU pattern.

For missing features, I recommend you look at 3rd party libraries such as SyncFusion, Telerik and others.

**Comment by TimLariviere** [comment]
Closing since this is a feature request for Xamarin.Forms but Fabulous is not meant to compensate missing features of Xamarin.Forms.
