### ISSUE TITLE
Modal page navigation samples needed

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#76]
@jimbobbennett mentioned that modal pages are not fully available in the framework and we need to give examples of these

**Comment by SergejDK** [comment]
Isn't this more or less already in the documentation: [https://fsprojects.github.io/Fabulous/views-navigation.html#navigationpage-using-pushpop](https://fsprojects.github.io/Fabulous/views-navigation.html#navigationpage-using-pushpop)

**Comment by dsyme** [comment]
Yes I think so
