### ISSUE TITLE
FSharp.Core is missing HintPath in the iOS template

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#776]
I have had the same exception on startup ( Could not load type of field 'Fabulous.ViewElement... Could not resolve type ...'Microsoft.FSharp.Core.FSharpValueOption  etc) happen to me a couple of times this week, but on iOS instead. Android has been fine.

In each case I have tracked down the problem to this line in my fsproj:

```
    <Reference Include="FSharp.Core">
      <Private>True</Private>
    </Reference>
```

which needed to be replaced with 
```
    <Reference Include="FSharp.Core">
      <HintPath>..\packages\FSharp.Core.4.7.2\lib\netstandard2.0\FSharp.Core.dll</HintPath>
    </Reference>
```

_Originally posted by @Ryan-Palmer-CIT in https://github.com/fsprojects/Fabulous/issues/385#issuecomment-656587527_

**Comment by TimLariviere** [comment]
@Ryan-Palmer-CIT I've duplicated your comment so we can track this.
Could you add some context to it, please?

Just checked, both the Android and iOS projects include the `HintPath` in the templates.

**Comment by Ryan-Palmer-CIT** [comment]
Sure no problem. I was going to add the issue as requested, sorry I hadn't managed to do it already it's just been a hectic week!

I just looked over the git history. My first commit was a clean Fabulous template installed and working. My second commit updates a few packages.  In the iOS project, this caused FSharp.Core to become private.

iOS .fsproj

![image](https://user-images.githubusercontent.com/66260121/87644234-c3cdc480-c743-11ea-8b96-62604ed839e2.png)

iOS packages.config

![image](https://user-images.githubusercontent.com/66260121/87644366-f37ccc80-c743-11ea-91db-0da680c2543d.png)

**Comment by Ryan-Palmer-CIT** [comment]
On a side note,  updating FSharpCore only updated the 'Update' refs in the core Forms project, ignoring the 'Include' one.

![image](https://user-images.githubusercontent.com/66260121/87644893-a5b49400-c744-11ea-9014-933bfcdaf780.png)

**Comment by SergejDK** [comment]
@Ryan-Palmer-CIT I think this issue is solved, right? I tested it and it seems to be fixed.

**Comment by Ryan-Palmer-CIT** [comment]
Maybe, I haven't tried using Fabulous since I wrote this post. Sorry I can't be any more help!

**Comment by SergejDK** [comment]
That's not a problem.
With the latest version of Fabulous and VS this does not seem to be a problem anymore. 
I am going to close this.

**Comment by Ryan-Palmer-CIT** [comment]
Hi @SergejDK , sorry to raise this from the dead but I just came back to Fabulous after a few months and had exactly this happen again. It seems it may be Windows related, so if you try to replicate you will need to use that rather than mac OS.

Just create a new Fabulous template project and update FSharp Core. It should mess up the fsharp refs. You will get an exception saying it can't find a ValueTuple definition in an FSharp 4.7.2 folder. The solution is to open the ios project file and make the replacements tim mentioned in the OP.

**Comment by TimLariviere** [comment]
@Ryan-Palmer-CIT I think it's a tooling issue in Visual Studio rather than a Fabulous issue...

We do have the hint path for FSharp.Core correctly declared in the iOS project
https://github.com/fsprojects/Fabulous/blob/ebcecbfcfcc598c9e8651b22f02652d2796f6ae6/Fabulous.XamarinForms/templates/content/blank/NewApp.iOS/NewApp.iOS.fsproj#L132-L134

How do you update the FSharp.Core package? Via the NuGet UI in VS?
Does VS replace `HintPath` with `Private = True`?

**Comment by Ryan-Palmer-CIT** [comment]
Hi Tim! It is the same issue we went over before.

>How do you update the FSharp.Core package? Via the NuGet UI in VS?
>Does VS replace HintPath with Private = True?

Yes and yes.

**Comment by TimLariviere** [comment]
Maybe the folks at https://github.com/xamarin/xamarin-macios can help fix that behavior?

**Comment by Ryan-Palmer-CIT** [comment]
Do you think it is worth a note in the docs or something? I lost many hours to it!

**Comment by TimLariviere** [comment]
I think we can include a note on it on this page: https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/dev-pitfalls.html
I already added some notes on limitations about IDEs and F# 5.0 in it, so it should be a good place for this.

**Comment by Ryan-Palmer-CIT** [comment]
Ok great - would you like me to add it or would you rather?

**Comment by TimLariviere** [comment]
It would be great if you could do it :)
I'll merge as soon as I have some time.

**Comment by Ryan-Palmer-CIT** [comment]
No problem, thanks for your help :)

**Comment by Ryan-Palmer-CIT** [comment]
Done
