### ISSUE TITLE
Update the documentation for new usage of LiveUpdate

### ISSUE THREAD

**Issue by NatElkins** [fsprojects/Fabulous#794]
I believe under step 7 here https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/tools.html#live-update it should be `dotnet fabulous --watch --send` not `fabulous --watch --send`.

**Comment by TimLariviere** [comment]
@NatElkins Yes you are right. We forgot to update the documentation as well as the printed commands on start up.
It should be updated to match real usage.

https://github.com/fsprojects/Fabulous/blob/5f370b148e82f256e7839daae380eaccd074c452/Fabulous.XamarinForms/src/Fabulous.XamarinForms.LiveUpdate/LiveUpdate.fs#L18-L43
