### ISSUE TITLE
Fabulous nuget pacakge not listing an FSharp.Core dependency

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#795]
I notice the FSHarp.Core dependency is not being listed on the Fabulous nuget package, I'm not sure why, I guess it just needs an entry in the nuspec

https://www.nuget.org/packages/Fabulous/0.57.0

**Comment by dsyme** [comment]
Also components like Fabulous.XamarinForms.FFImageLoading are listing upward bound dependencies like `(>= 0.55.0-preview3)` for Fabulous and Fabulous.XamarinForms.  

I think this should be more like ` 0.55.*` or just `= 0.55.0-preview3` since there's no guarantee of any binary API compat between Fabulous versions at the moment.

This came up in https://github.com/dotnet/fsharp/issues/9370 which was using a mix of versions of components which were assuming binary compat

**Comment by TimLariviere** [comment]
Regarding FSharp,Core, I tried to follow the [Notes and Guidance](https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#libraries-should-target-lower-versions-of-fsharpcore), but wasn't really sure what to do and ended up making it private.
I'll change that and pin it to `4.7.0` I guess? (it's the first targeting .NET Standard 2.0 directly)
https://github.com/fsprojects/Fabulous/blob/b75d01881c5c1c86d2989faf19dae9ce960422ba/Packages.targets#L23

For `Fabulous.XamarinForms.FFImageLoading`, it's a limitation of the new SDK-style projects.
NuGet automatically infers a `>=` constraint based on the package version used in `PackageReference`.
AFAIK there's no way to change that, except via writing an actual nuspec file.
