### ISSUE TITLE
Fabulous 0.60- preview1 issues

### ISSUE THREAD

**Issue by vshapenko** [fsprojects/Fabulous#808]
Hello! Looks like Fabulous 0.60 has some issues with attached properties. In some cases no margin/padding etc is applied.

**Comment by vshapenko** [comment]
Still have issues after applying udatexxxattachedpriperties

**Comment by TimLariviere** [comment]
In Fabulous v0.60.0-preview2, I disabled memoization for structs (Color, Thickness & LayoutOptions) which was the source of errors. I need to find another way to avoid boxing structs each time.
