### ISSUE TITLE
After update to fabulous 0.60 iOS project will not build with: error MT3001: Could not AOT the assembly

### ISSUE THREAD

**Issue by Stuey2** [fsprojects/Fabulous#828]
After an update to 0.60 and an update of FSharp.Core to 5.0.0 my iOS project fails with: `error MT3001: Could not AOT the assembly`

The issue seems to relate to typerefs if FSharp.Core. I've tried downgrading it to 4.7.2 but to no avail. Please can you help - I cannot get this thing to build and don't know if it's my side or a bug on yours.

Tail end of build-logs follow (verbosity Detailed)

    1>Target "_CompileToNative" in file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets" from project "C:\dev\yebo\src\MYAPP.iOS\MYAPP.iOS.fsproj" (target "_CreateAppBundle" depends on it):
    1>	Building target "_CompileToNative" completely.
    1>	Output file "bin\iPhone\Debug\MYAPP.iOS.app\MYAPP.iOS" does not exist.
    1>	Using "MTouch" task from assembly "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Tasks.dll".
    1>	Task "MTouch"
    1>		MTouch: 2020-12-28T19:42:48.5160737+00:00 - Started
    1>		MTouch: 2020-12-28T19:42:48.5160737+00:00 - Initializing
    1>		[xma]: Trying to get a Build Connection for Session '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef': Xamarin.VisualStudio.Build.BuildConnection.1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef, Lifetime: Build
    1>		MTouch: 2020-12-28T19:42:48.5200857+00:00 - Initialized
    1>		MTouch: 2020-12-28T19:42:48.5210177+00:00 - Determining the modified inputs that should be copied to the Mac (18 files)
    1>		[xma]: Determining task items to copy to the server for 'MYAPP.iOS'...
    1>		[xma]: The following items should be copied to the server for 'MYAPP.iOS': bin\iPhone\Debug\MYAPP.iOS.exe
    1>		MTouch: 2020-12-28T19:42:49.0242393+00:00 - Copying inputs (1 files)
    1>		[xma]: SCP uploading 'bin/iPhone/Debug/MYAPP.iOS.exe' to 'bin/iPhone/Debug/MYAPP.iOS.exe' for 'MYAPP.iOS'...
    1>		[xma]: Uploading 'MYAPP.iOS.exe' (9/9 KB) 100.00%...
    1>		MTouch: 2020-12-28T19:42:49.0941131+00:00 - Serializing intputs
    1>		MTouch: 2020-12-28T19:42:49.1170388+00:00 - Executing
    1>		[xma]: Starting remote task execution for 'MYAPP.iOS': Xamarin.iOS.Tasks.MTouch
    1>		MTouch: 2020-12-28T19:43:41.1112889+00:00 - Logging messages
    1>		/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/response-file.rsp 
    1>		Xamarin.iOS 14.6.0.15 (d16-8: 87a1b18d8 using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk
    1>		AOT Compilation exited with code 1, command:
    1>		MONO_PATH=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/14.6.0.15/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32 --aot=mtriple=arm64-ios,data-outfile=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/arm64/MYAPP.aotdata.arm64,static,asmonly,direct-icalls,interp,full,soft-debug,dwarfdebug,no-direct-calls,outfile=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/arm64/MYAPP.dll.s /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/MYAPP.dll
    1>		Mono Ahead of Time compiler - compiling assembly /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/MYAPP.dll
    1>		AOTID F5A8773E-567E-71FB-FC62-384FC6BEE64E
    1>		Failed to load method 0x60001fb from '/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/MYAPP.dll' due to Could not resolve type with token 0100000f from typeref (expected class 'Microsoft.FSharp.Core.FSharpValueOption`1' in assembly 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:Microsoft.FSharp.Core.FSharpValueOption`1 member:(null).
    1>		Run with MONO_LOG_LEVEL=debug for more information.
    1>		AOT of image /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/MYAPP.dll failed.
    1>		AOT Compilation exited with code 1, command:
    1>		MONO_PATH=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/14.6.0.15/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32 --aot=mtriple=arm64-ios,data-outfile=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/arm64/Fabulous.aotdata.arm64,static,asmonly,direct-icalls,interp,full,soft-debug,dwarfdebug,no-direct-calls,outfile=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/arm64/Fabulous.dll.s /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/Fabulous.dll
    1>		Failed to load method 0x6000025 from '/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/Fabulous.dll' due to Could not resolve signature of method Fabulous.ViewElement:Create.
    1>		Run with MONO_LOG_LEVEL=debug for more information.
    1>		AOT of image /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/Fabulous.dll failed.
    1>		Mono Ahead of Time compiler - compiling assembly /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/Fabulous.dll
    1>		AOTID B2EE169F-1F97-4948-12BD-54C28A87C3F0
    1>		Could not load signature of Fabulous.ViewElement:Create due to: Could not resolve type with token 01000013 from typeref (expected class 'Microsoft.FSharp.Core.FSharpValueOption`1' in assembly 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:Microsoft.FSharp.Core.FSharpValueOption`1 member:(null)
    1>		AOT Compilation exited with code 1, command:
    1>		MONO_PATH=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/14.6.0.15/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32 --aot=mtriple=arm64-ios,data-outfile=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/arm64/Fabulous.XamarinForms.aotdata.arm64,static,asmonly,direct-icalls,interp,full,soft-debug,dwarfdebug,no-direct-calls,outfile=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/arm64/Fabulous.XamarinForms.dll.s /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/Fabulous.XamarinForms.dll
    1>		Mono Ahead of Time compiler - compiling assembly /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/Fabulous.XamarinForms.dll
    1>		AOTID 7749AE1B-DAC0-7BC8-B730-863F8E7BBCF5
    1>		Could not load signature of Fabulous.XamarinForms.ViewBuilders:UpdateMultiPageOfT due to: Could not resolve type with token 0100001b from typeref (expected class 'Microsoft.FSharp.Core.FSharpValueOption`1' in assembly 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:Microsoft.FSharp.Core.FSharpValueOption`1 member:(null)
    1>		Failed to load method 0x60000dd from '/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/Fabulous.XamarinForms.dll' due to Could not resolve signature of method Fabulous.XamarinForms.ViewBuilders:UpdateMultiPageOfT.
    1>		Run with MONO_LOG_LEVEL=debug for more information.
    1>		AOT of image /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/Fabulous.XamarinForms.dll failed.
    1>		AOT Compilation exited with code 1, command:
    1>		MONO_PATH=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/14.6.0.15/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32 --aot=mtriple=arm64-ios,data-outfile=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/arm64/UtilFs.aotdata.arm64,static,asmonly,direct-icalls,interp,full,soft-debug,dwarfdebug,no-direct-calls,outfile=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/arm64/UtilFs.dll.s /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/UtilFs.dll
    1>		Mono Ahead of Time compiler - compiling assembly /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/UtilFs.dll
    1>		AOTID 8F51A9AB-FE08-94AB-C051-0E6AE23A8AF8
    1>		Failed to load method 0x6000129 from '/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/UtilFs.dll' due to Could not resolve type with token 01000011 from typeref (expected class 'Microsoft.FSharp.Control.AsyncActivation`1' in assembly 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:Microsoft.FSharp.Control.AsyncActivation`1 member:(null).
    1>		Run with MONO_LOG_LEVEL=debug for more information.
    1>		AOT of image /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/UtilFs.dll failed.
    1>		AOT Compilation exited with code 1, command:
    1>		MONO_PATH=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/14.6.0.15/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32 --aot=mtriple=arm64-ios,data-outfile=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/arm64/Fabulous.LiveUpdate.aotdata.arm64,static,asmonly,direct-icalls,interp,full,soft-debug,dwarfdebug,no-direct-calls,outfile=/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/arm64/Fabulous.LiveUpdate.dll.s /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/Fabulous.LiveUpdate.dll
    1>		Failed to load method 0x6000058 from '/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/Fabulous.LiveUpdate.dll' due to Could not resolve type with token 01000011 from typeref (expected class 'Microsoft.FSharp.Control.AsyncActivation`1' in assembly 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:Microsoft.FSharp.Control.AsyncActivation`1 member:(null).
    1>		Run with MONO_LOG_LEVEL=debug for more information.
    1>		AOT of image /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/Fabulous.LiveUpdate.dll failed.
    1>		Mono Ahead of Time compiler - compiling assembly /Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/Fabulous.LiveUpdate.dll
    1>		AOTID C6712972-8A09-A799-426F-F113805765D0
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(711,3): error MT3001: Could not AOT the assembly '/Users/_bob/Library/Caches/Xamarin/mtbs/builds/MYAPP.iOS/1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef/obj/iPhone/Debug/mtouch-cache/3-Build/MYAPP.dll'
    1>				
    1>		The command exited with code 1.
    1>		MTouch: 2020-12-28T19:43:41.1122726+00:00 - Finished
    1>Done building project "MYAPP.iOS.fsproj" -- FAILED.
    1>
    1>Build FAILED.
    ========== Build: 0 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========

**Comment by SergejDK** [comment]
@Stuey2 

I have some questions before I can directly help you.
1. Are you on windows ?
2. which Visual Studio version do you use? Maybe just try to update.
3. How did you upgrade the packages ? Normally over nuget?
4. How did you run your application? Do you have special configurations?

**Comment by Stuey2** [comment]
Hi SergejDK, thanks for getting back to me so quickly. 

Happily though I've found a 'fix' in [issue 385](https://github.com/fsprojects/Fabulous/issues/385#issuecomment-656587527).

In answer to your questions although there's no need to continue this thread:
1. Yes
2. VS 2019 16.8.3
3. Yup over nuget
4. No nothing out of the ordinary
