### ISSUE TITLE
My attempt to update the user docs

### ISSUE THREAD

**Issue by reigam** [fsprojects/Fabulous#857]
## Proposal

My attempt to update the user docs (still work in progress, not all pages linked): 
https://github.com/reigam/Fabulous/tree/docs/docs/Fabulous.XamarinForms

My intentions: 
- Make it more accessible for beginners (like me)
- Structure the controls according to the structure given here: Controls Reference - Xamarin | Microsoft Docs
  - https://github.com/reigam/Fabulous/blob/docs/docs/Fabulous.XamarinForms/images/guide-organisation.jpg
- Show which pages / topics are up to date

What do you think?

Also, for internal links, shoud I use:
....](introduction.html)
or 
....](introduction.md)
?

**Comment by SergejDK** [comment]
@reigam 
I think the structure is great and more readable. I am currently working on a complete new documentation website for fabulous with Fornax which will generate a complete documentation from .md files.

for internal links the .md is preferred afaik. 

How would you represent pages/topics which are up to date.

**Comment by reigam** [comment]
@SergejDK 
Thanks for the feedback. Will you use the existing docs for your new website? Any use continuing working on these?

> How would you represent pages/topics which are up to date.

Lacking a better idea I just added 
##### (topic last updated: v 0.61.0)
or 
##### (topic last updated: pending)

under the name of the page or sub-topic.

**Comment by SergejDK** [comment]
@reigam 
The idea is that we use the current .md files but we will have sth. like a sidemenu and searchbar which will make it easier to find stuff and just display the .md files in the main content.

So I think it is fine if you keep working on it. The image on how to split the folders is sth. I was thinking about, too and we can definetly use your idea here. 


> (topic last updated: v 0.61.0)
or
(topic last updated: pending)


I think this is a great idea. This way everyone knows at which version it is possible. maybe a TimeStamp isn't wrong either sth. like

`topic last updated: v 0.61.0 - 31.03.2021 - 11:15am`

**Comment by TimLariviere** [comment]
Closing in favour of #927
