### ISSUE TITLE
[Bug]  New App from template UWP/WPF FileNotFoundException

### ISSUE THREAD

**Issue by SergejDK** [fsprojects/Fabulous#881]
### Steps to Reproduce

1. Create a new app -->  dotnet new fabulous-xf-app -n SqueakyApp --WPF --UWP
2. Open .sln in VS 2019
3. Run WPF or UWP on your local computer
4. `System.IO.FileNotFoundException: "Could not load file or assembly 'Fabulous, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'. `

### Expected Behavior
Runs without an error

### Actual Behavior
`System.IO.FileNotFoundException: "Could not load file or assembly 'Fabulous, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'. `

### Basic Information

- Version with issue: Fabulous.XamarinForms 1.1.0 & Fabulous 1.0.0
- Last known good version: no information
- Platform Target Frameworks: 
  - UWP: 1809
  - WPF: 

### Environment

```
Microsoft Visual Studio Community 2019
Version 16.10.2
VisualStudio.16.Release/16.10.2+31410.357
Microsoft .NET Framework
Version 4.8.04084

Installierte Version: Community
```

### Build Logs

`System.IO.FileNotFoundException`  --> `Could not load file or assembly 'Fabulous, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'`

### Workaround

Adding the Fabulous Nuget package will fix the issue but we have to include it into the template files.

**Comment by ChristophSchmidpeter** [comment]
@TimLariviere  @SergejDK It seems on the main branch the package references are not added yet, or have they been added already? In order to make it possible to run new user apps created from the templates again: Will be there a bugfix release soon?

**Comment by SergejDK** [comment]
@ChristophSchmidpeter 
I will push a fix for this in the next days. After this we (@TimLariviere and I) can check about making a release.

**Comment by ChristophSchmidpeter** [comment]
@SergejDK Awesome, thank you

**Comment by auslavs** [comment]
I'm still having this issue downloading the template and starting a new project for the first time today.
> System.IO.FileNotFoundException: 'Could not load file or assembly 'Fabulous, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'
