### ISSUE TITLE
Simplify Fabulous template(from packages.config to PackageReferences) 

### ISSUE THREAD

**Issue by edgarfgp** [fsprojects/Fabulous#896]
## Question / Discussion

The existing template uses packages.config which adds +100 lines of references paths and it is difficult to maintain in any app. 

If there is not a limitation I think we can migrate the templates to use PackageReferences to make it more maintainable and less verbose. 

What do you think ?

**Comment by edgarfgp** [comment]
Also I'm happy to contribute if you think is reasonable to do it .

**Comment by TimLariviere** [comment]
https://github.com/dotnet/fsharp/issues/5849

Unfortunately MS won't add support for `PackageReference` for old-style fsproj.

With MAUI, we'll be able to use the new SDK-style fsproj which supports `PackageReference`.
But you'll need to wait for Fabulous v2 and MAUI support, which will take a few months before it happens (MAUI is hard to work with right now 😞).

One way you could help is by trying out https://github.com/TimLariviere/Fabulous-new and giving your feedback.
Just bear in mind that it is still very limited right now.
