### ISSUE TITLE
Cannot run default project on linux

### ISSUE THREAD

**Issue by jinyus** [fsprojects/Fabulous#906]
## Question / Discussion
Hello, I followed the guide here : [https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/getting-started.html](https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/getting-started.html), and created a new sln with:

```
dotnet new fabulous-xf-app -n DemoApp --GTK --Android=false --iOS=false
```
This is the sln that it created: [https://github.com/jinyus/fabulous-demo-app](https://github.com/jinyus/fabulous-demo-app)
I navigated to the folder and ran:
```
dotnet run --project DemoApp.Gtk
```
This is the error that I received:
```bash
/projects/fs/DemoApp/DemoApp.Gtk/DemoApp.Gtk.fsproj : error MSB4057: The target "Build" does not exist in the project.

The build failed. Fix the build errors and run again.
```

I use VSCode on linux and couldn't find a tutorial on how to run/build the project from the command line. I'd appreciate any help.

**Comment by TimLariviere** [comment]
Hello @jinyus
Please see https://github.com/fsprojects/Fabulous/discussions/905 for the reason why.
If you have any other question about this, you can continue the discussion there.
