### ISSUE TITLE
App size: Remove F# compilation resources during linking

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#94]
See https://github.com/mono/linker/issues/329
> The linker can/should automatically remove any .NET manifest assembly resources named FSharpSignatureData.* and FSharpOptimizationData.* during linking.
> 
> These are only ever needed for F# compilation which doesn't happen on-device and given the aims of the linker it is reasonable to assume this data is unreachable.
> 
> My understanding is that removing these would trim about 1.5MB off the size of all applications using FSharp.Core.dll, and about 3MB off all applications using Elmish.XamarinForms.dll.

**Comment by dsyme** [comment]
As an aside, I have checed that the facade code in `Elmish.XamarinForms.dll` related to unused controls is being correctly trimmed out by the Xamarin linker (mono/linker)

For example here is the remaining view code for `CounterApp`, just the controls that are actually used:

![image](https://user-images.githubusercontent.com/7204669/42222500-4d6687ca-7ecd-11e8-92b1-2386ce9a97ab.png)

**Comment by dsyme** [comment]
This was using these settings:

![image](https://user-images.githubusercontent.com/7204669/42222786-1096c20a-7ece-11e8-99d6-e1c63a6a2f30.png)

**Comment by dsyme** [comment]
I added some notes on checking app size here: https://github.com/fsprojects/Elmish.XamarinForms/blob/master/DEVGUIDE.md#dev-notes---checking-app-size

**Comment by dsyme** [comment]
It's pretty cool that the rest of the stuff gets trimmed out!

**Comment by xperiandri** [comment]
Is this a recommended Liker setup? We had issues with Linker
```
Xamarin.Android.Common.targets(2056,5): 
error XALNK7000: 
Mono.Linker.MarkException: 
Error processing method: 
'System.Void Fabulous.XamarinForms.ViewBuilders::UpdateItemsView(Microsoft.FSharp.Core.FSharpValueOption`1<Fabulous.ViewElement>,Fabulous.ViewElement,Xamarin.Forms.ItemsView)' in assembly: 
'Fabulous.XamarinForms.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.ItemsView::set_ItemSizingStrategy(Xamarin.Forms.ItemSizingStrategy)
```
until we disabled it

**Comment by heytherewill** [comment]
I assume this can be safely closed now that the associated linker issue has been resolved

**Comment by TimLariviere** [comment]
v2 does a great job at trimming all unused code
